/*
 * dbghelp.dll proxy. Generated by scripts/gen_proxy_from_spec.py - paste into proxy_dll/.
 */

#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <Windows.h>
#include <string>

static HMODULE g_dbghelp_module = nullptr;

static bool LoadRealDbghelp() {
    if (g_dbghelp_module != nullptr) return true;
    WCHAR system_path[MAX_PATH];
    if (GetSystemDirectoryW(system_path, MAX_PATH) == 0) return false;
    std::wstring path = std::wstring(system_path) + L"\\dbghelp.dll";
    g_dbghelp_module = LoadLibraryW(path.c_str());
    return g_dbghelp_module != nullptr;
}

extern "C" LONG WINAPI DbgHelpCreateUserDump(void) {
    return 0;
}

extern "C" LONG WINAPI DbgHelpCreateUserDumpW(void) {
    return 0;
}

extern "C" BOOL WINAPI EnumDirTree(LONG p0, LPCSTR p1, LPCSTR p2, LPVOID p3, LPVOID p4, LPVOID p5) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, LPCSTR, LPCSTR, LPVOID, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "EnumDirTree") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5);
}

extern "C" BOOL WINAPI EnumDirTreeW(LONG p0, LPCWSTR p1, LPCWSTR p2, LPVOID p3, LPVOID p4, LPVOID p5) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, LPCWSTR, LPCWSTR, LPVOID, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "EnumDirTreeW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5);
}

extern "C" LONG WINAPI EnumerateLoadedModules64(LONG p0, LPVOID p1, LPVOID p2) {
    if (!LoadRealDbghelp()) return 0;
    typedef LONG (WINAPI *PFN)(LONG, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "EnumerateLoadedModules64") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" LONG WINAPI EnumerateLoadedModules(LONG p0, LPVOID p1, LPVOID p2) {
    if (!LoadRealDbghelp()) return 0;
    typedef LONG (WINAPI *PFN)(LONG, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "EnumerateLoadedModules") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" LONG WINAPI EnumerateLoadedModulesEx(LONG p0, LPVOID p1, LPVOID p2) {
    if (!LoadRealDbghelp()) return 0;
    typedef LONG (WINAPI *PFN)(LONG, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "EnumerateLoadedModulesEx") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" LONG WINAPI EnumerateLoadedModulesW64(LONG p0, LPVOID p1, LPVOID p2) {
    if (!LoadRealDbghelp()) return 0;
    typedef LONG (WINAPI *PFN)(LONG, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "EnumerateLoadedModulesW64") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" LONG WINAPI EnumerateLoadedModulesExW(LONG p0, LPVOID p1, LPVOID p2) {
    if (!LoadRealDbghelp()) return 0;
    typedef LONG (WINAPI *PFN)(LONG, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "EnumerateLoadedModulesExW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" DWORD WINAPI ExtensionApiVersion(void) {
    if (!LoadRealDbghelp()) return 0;
    typedef DWORD (WINAPI *PFN)(void);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "ExtensionApiVersion") : nullptr);
    if (!fn) return 0;
    return fn();
}

extern "C" LONG WINAPI FindDebugInfoFile(LPCSTR p0, LPCSTR p1, LPVOID p2) {
    if (!LoadRealDbghelp()) return 0;
    typedef LONG (WINAPI *PFN)(LPCSTR, LPCSTR, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "FindDebugInfoFile") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" LONG WINAPI FindDebugInfoFileEx(LPCSTR p0, LPCSTR p1, LPVOID p2, LPVOID p3, LPVOID p4) {
    if (!LoadRealDbghelp()) return 0;
    typedef LONG (WINAPI *PFN)(LPCSTR, LPCSTR, LPVOID, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "FindDebugInfoFileEx") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4);
}

extern "C" LONG WINAPI FindDebugInfoFileExW(void) {
    return 0;
}

extern "C" LONG WINAPI FindExecutableImage(LPCSTR p0, LPCSTR p1, LPCSTR p2) {
    if (!LoadRealDbghelp()) return 0;
    typedef LONG (WINAPI *PFN)(LPCSTR, LPCSTR, LPCSTR);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "FindExecutableImage") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" LONG WINAPI FindExecutableImageEx(LPCSTR p0, LPCSTR p1, LPVOID p2, LPVOID p3, LPVOID p4) {
    if (!LoadRealDbghelp()) return 0;
    typedef LONG (WINAPI *PFN)(LPCSTR, LPCSTR, LPVOID, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "FindExecutableImageEx") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4);
}

extern "C" LONG WINAPI FindExecutableImageExW(LPCWSTR p0, LPCWSTR p1, LPVOID p2, LPVOID p3, LPVOID p4) {
    if (!LoadRealDbghelp()) return 0;
    typedef LONG (WINAPI *PFN)(LPCWSTR, LPCWSTR, LPVOID, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "FindExecutableImageExW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4);
}

extern "C" LONG WINAPI FindFileInPath(void) {
    return 0;
}

extern "C" LONG WINAPI FindFileInSearchPath(void) {
    return 0;
}

extern "C" LONG WINAPI GetTimestampForLoadedLibrary(LONG p0) {
    if (!LoadRealDbghelp()) return 0;
    typedef LONG (WINAPI *PFN)(LONG);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "GetTimestampForLoadedLibrary") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" BOOL WINAPI ImageDirectoryEntryToData(LPVOID p0, LONG p1, LONG p2, LPVOID p3) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LPVOID, LONG, LONG, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "ImageDirectoryEntryToData") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" BOOL WINAPI ImageDirectoryEntryToDataEx(LPVOID p0, LONG p1, LONG p2, LPVOID p3, LPVOID p4) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LPVOID, LONG, LONG, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "ImageDirectoryEntryToDataEx") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4);
}

extern "C" BOOL WINAPI ImageNtHeader(LPVOID p0) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "ImageNtHeader") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" BOOL WINAPI ImageRvaToSection(LPVOID p0, LPVOID p1, LONG p2) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LPVOID, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "ImageRvaToSection") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" BOOL WINAPI ImageRvaToVa(LPVOID p0, LPVOID p1, LONG p2, LPVOID p3) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LPVOID, LPVOID, LONG, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "ImageRvaToVa") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" BOOL WINAPI ImagehlpApiVersion(void) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(void);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "ImagehlpApiVersion") : nullptr);
    if (!fn) return 0;
    return fn();
}

extern "C" BOOL WINAPI ImagehlpApiVersionEx(LPVOID p0) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "ImagehlpApiVersionEx") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" LONG WINAPI MakeSureDirectoryPathExists(LPCSTR p0) {
    if (!LoadRealDbghelp()) return 0;
    typedef LONG (WINAPI *PFN)(LPCSTR);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "MakeSureDirectoryPathExists") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" LONG WINAPI MiniDumpReadDumpStream(LPVOID p0, LONG p1, LPVOID p2, LPVOID p3, LPVOID p4) {
    if (!LoadRealDbghelp()) return 0;
    typedef LONG (WINAPI *PFN)(LPVOID, LONG, LPVOID, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "MiniDumpReadDumpStream") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4);
}

extern "C" LONG WINAPI MiniDumpWriteDump(LPVOID p0, LONG p1, LPVOID p2, LONG p3, LPVOID p4, LPVOID p5, LPVOID p6) {
    if (!LoadRealDbghelp()) return 0;
    typedef LONG (WINAPI *PFN)(LPVOID, LONG, LPVOID, LONG, LPVOID, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "MiniDumpWriteDump") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5, p6);
}

extern "C" LONG WINAPI SearchTreeForFile(LPCSTR p0, LPCSTR p1, LPVOID p2) {
    if (!LoadRealDbghelp()) return 0;
    typedef LONG (WINAPI *PFN)(LPCSTR, LPCSTR, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SearchTreeForFile") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" LONG WINAPI SearchTreeForFileW(LPCWSTR p0, LPCWSTR p1, LPVOID p2) {
    if (!LoadRealDbghelp()) return 0;
    typedef LONG (WINAPI *PFN)(LPCWSTR, LPCWSTR, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SearchTreeForFileW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" LONG WINAPI StackWalk64(LONG p0, LONG p1, LONG p2, LPVOID p3, LPVOID p4, LPVOID p5, LPVOID p6, LPVOID p7, LPVOID p8) {
    if (!LoadRealDbghelp()) return 0;
    typedef LONG (WINAPI *PFN)(LONG, LONG, LONG, LPVOID, LPVOID, LPVOID, LPVOID, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "StackWalk64") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5, p6, p7, p8);
}

extern "C" LONG WINAPI StackWalk(LONG p0, LONG p1, LONG p2, LPVOID p3, LPVOID p4, LPVOID p5, LPVOID p6, LPVOID p7, LPVOID p8) {
    if (!LoadRealDbghelp()) return 0;
    typedef LONG (WINAPI *PFN)(LONG, LONG, LONG, LPVOID, LPVOID, LPVOID, LPVOID, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "StackWalk") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5, p6, p7, p8);
}

extern "C" LONG WINAPI StackWalkEx(LONG p0, LONG p1, LONG p2, LPVOID p3, LPVOID p4, LPVOID p5, LPVOID p6, LPVOID p7, LPVOID p8, LONG p9) {
    if (!LoadRealDbghelp()) return 0;
    typedef LONG (WINAPI *PFN)(LONG, LONG, LONG, LPVOID, LPVOID, LPVOID, LPVOID, LPVOID, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "StackWalkEx") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9);
}

extern "C" BOOL WINAPI SymAddSourceStream(void) {
    return 0;
}

extern "C" BOOL WINAPI SymAddSourceStreamA(void) {
    return 0;
}

extern "C" BOOL WINAPI SymAddSourceStreamW(void) {
    return 0;
}

extern "C" BOOL WINAPI SymAddSymbol(LPVOID p0, DWORD64 p1, LPCSTR p2, DWORD64 p3, LONG p4, LONG p5) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LPVOID, DWORD64, LPCSTR, DWORD64, LONG, LONG);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymAddSymbol") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5);
}

extern "C" BOOL WINAPI SymAddSymbolW(LPVOID p0, DWORD64 p1, LPCWSTR p2, DWORD64 p3, LONG p4, LONG p5) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LPVOID, DWORD64, LPCWSTR, DWORD64, LONG, LONG);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymAddSymbolW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5);
}

extern "C" BOOL WINAPI SymAddrIncludeInlineTrace(LONG p0, DWORD64 p1) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, DWORD64);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymAddrIncludeInlineTrace") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" BOOL WINAPI SymCleanup(LONG p0) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymCleanup") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" BOOL WINAPI SymCompareInlineTrace(void) {
    return 0;
}

extern "C" BOOL WINAPI SymDeleteSymbol(void) {
    return 0;
}

extern "C" BOOL WINAPI SymDeleteSymbolW(void) {
    return 0;
}

extern "C" BOOL WINAPI SymEnumLines(LPVOID p0, DWORD64 p1, LPCSTR p2, LPCSTR p3, LPVOID p4, LPVOID p5) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LPVOID, DWORD64, LPCSTR, LPCSTR, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymEnumLines") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5);
}

extern "C" BOOL WINAPI SymEnumLinesW(void) {
    return 0;
}

extern "C" BOOL WINAPI SymEnumProcesses(void) {
    return 0;
}

extern "C" BOOL WINAPI SymEnumSourceFileTokens(void) {
    return 0;
}

extern "C" BOOL WINAPI SymEnumSourceFiles(LPVOID p0, DWORD64 p1, LPCSTR p2, LPVOID p3, LPVOID p4) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LPVOID, DWORD64, LPCSTR, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymEnumSourceFiles") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4);
}

extern "C" BOOL WINAPI SymEnumSourceFilesW(LPVOID p0, DWORD64 p1, LPCWSTR p2, LPVOID p3, LPVOID p4) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LPVOID, DWORD64, LPCWSTR, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymEnumSourceFilesW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4);
}

extern "C" BOOL WINAPI SymEnumSourceLines(LPVOID p0, DWORD64 p1, LPCSTR p2, LPCSTR p3, LONG p4, LONG p5, LPVOID p6, LPVOID p7) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LPVOID, DWORD64, LPCSTR, LPCSTR, LONG, LONG, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymEnumSourceLines") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5, p6, p7);
}

extern "C" BOOL WINAPI SymEnumSourceLinesW(LPVOID p0, DWORD64 p1, LPCWSTR p2, LPCWSTR p3, LONG p4, LONG p5, LPVOID p6, LPVOID p7) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LPVOID, DWORD64, LPCWSTR, LPCWSTR, LONG, LONG, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymEnumSourceLinesW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5, p6, p7);
}

extern "C" BOOL WINAPI SymEnumSym(void) {
    return 0;
}

extern "C" BOOL WINAPI SymEnumSymbols(LPVOID p0, DWORD64 p1, LPCSTR p2, LPVOID p3, LPVOID p4) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LPVOID, DWORD64, LPCSTR, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymEnumSymbols") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4);
}

extern "C" BOOL WINAPI SymEnumSymbolsForAddr(void) {
    return 0;
}

extern "C" BOOL WINAPI SymEnumSymbolsForAddrW(void) {
    return 0;
}

extern "C" BOOL WINAPI SymEnumSymbolsW(LPVOID p0, DWORD64 p1, LPCWSTR p2, LPVOID p3, LPVOID p4) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LPVOID, DWORD64, LPCWSTR, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymEnumSymbolsW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4);
}

extern "C" BOOL WINAPI SymEnumTypes(LPVOID p0, DWORD64 p1, LPVOID p2, LPVOID p3) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LPVOID, DWORD64, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymEnumTypes") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" BOOL WINAPI SymEnumTypesByName(LPVOID p0, DWORD64 p1, LPCSTR p2, LPVOID p3, LPVOID p4) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LPVOID, DWORD64, LPCSTR, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymEnumTypesByName") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4);
}

extern "C" BOOL WINAPI SymEnumTypesByNameW(LPVOID p0, DWORD64 p1, LPCWSTR p2, LPVOID p3, LPVOID p4) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LPVOID, DWORD64, LPCWSTR, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymEnumTypesByNameW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4);
}

extern "C" BOOL WINAPI SymEnumTypesW(LPVOID p0, DWORD64 p1, LPVOID p2, LPVOID p3) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LPVOID, DWORD64, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymEnumTypesW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" BOOL WINAPI SymEnumerateModules64(LONG p0, LPVOID p1, LPVOID p2) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymEnumerateModules64") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" BOOL WINAPI SymEnumerateModules(LONG p0, LPVOID p1, LPVOID p2) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymEnumerateModules") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" BOOL WINAPI SymEnumerateModulesW64(LONG p0, LPVOID p1, LPVOID p2) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymEnumerateModulesW64") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" BOOL WINAPI SymEnumerateSymbols64(LONG p0, DWORD64 p1, LPVOID p2, LPVOID p3) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, DWORD64, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymEnumerateSymbols64") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" BOOL WINAPI SymEnumerateSymbols(LONG p0, DWORD64 p1, LPVOID p2, LPVOID p3) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, DWORD64, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymEnumerateSymbols") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" BOOL WINAPI SymEnumerateSymbolsW(void) {
    return 0;
}

extern "C" BOOL WINAPI SymEnumerateSymbolsW64(void) {
    return 0;
}

extern "C" BOOL WINAPI SymFindDebugInfoFile(void) {
    return 0;
}

extern "C" BOOL WINAPI SymFindDebugInfoFileW(void) {
    return 0;
}

extern "C" BOOL WINAPI SymFindExecutableImage(void) {
    return 0;
}

extern "C" BOOL WINAPI SymFindExecutableImageW(void) {
    return 0;
}

extern "C" BOOL WINAPI SymFindFileInPath(LONG p0, LPCSTR p1, LPCSTR p2, LPVOID p3, LONG p4, LONG p5, LONG p6, LPVOID p7, LPVOID p8, LPVOID p9) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, LPCSTR, LPCSTR, LPVOID, LONG, LONG, LONG, LPVOID, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymFindFileInPath") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9);
}

extern "C" BOOL WINAPI SymFindFileInPathW(LONG p0, LPCWSTR p1, LPCWSTR p2, LPVOID p3, LONG p4, LONG p5, LONG p6, LPVOID p7, LPVOID p8, LPVOID p9) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, LPCWSTR, LPCWSTR, LPVOID, LONG, LONG, LONG, LPVOID, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymFindFileInPathW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9);
}

extern "C" BOOL WINAPI SymFromAddr(LPVOID p0, DWORD64 p1, LPVOID p2, LPVOID p3) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LPVOID, DWORD64, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymFromAddr") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" BOOL WINAPI SymFromAddrW(LPVOID p0, DWORD64 p1, LPVOID p2, LPVOID p3) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LPVOID, DWORD64, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymFromAddrW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" BOOL WINAPI SymFromIndex(LONG p0, DWORD64 p1, LONG p2, LPVOID p3) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, DWORD64, LONG, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymFromIndex") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" BOOL WINAPI SymFromIndexW(LONG p0, DWORD64 p1, LONG p2, LPVOID p3) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, DWORD64, LONG, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymFromIndexW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" BOOL WINAPI SymFromInlineContext(LONG p0, DWORD64 p1, LONG p2, LPVOID p3, LPVOID p4) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, DWORD64, LONG, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymFromInlineContext") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4);
}

extern "C" BOOL WINAPI SymFromInlineContextW(LONG p0, DWORD64 p1, LONG p2, LPVOID p3, LPVOID p4) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, DWORD64, LONG, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymFromInlineContextW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4);
}

extern "C" BOOL WINAPI SymFromName(LONG p0, LPCSTR p1, LPVOID p2) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, LPCSTR, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymFromName") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" BOOL WINAPI SymFromNameW(LONG p0, LPCWSTR p1, LPVOID p2) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, LPCWSTR, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymFromNameW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" BOOL WINAPI SymFromToken(void) {
    return 0;
}

extern "C" BOOL WINAPI SymFromTokenW(void) {
    return 0;
}

extern "C" BOOL WINAPI SymFunctionTableAccess64(LONG p0, DWORD64 p1) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, DWORD64);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymFunctionTableAccess64") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" BOOL WINAPI SymFunctionTableAccess(LONG p0, DWORD64 p1) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, DWORD64);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymFunctionTableAccess") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" BOOL WINAPI SymGetFileLineOffsets64(void) {
    return 0;
}

extern "C" BOOL WINAPI SymGetHomeDirectory(void) {
    return 0;
}

extern "C" BOOL WINAPI SymGetHomeDirectoryW(void) {
    return 0;
}

extern "C" BOOL WINAPI SymGetExtendedOption(LONG p0) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymGetExtendedOption") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" BOOL WINAPI SymGetLineFromAddr64(LONG p0, DWORD64 p1, LPVOID p2, LPVOID p3) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, DWORD64, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymGetLineFromAddr64") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" BOOL WINAPI SymGetLineFromAddr(LONG p0, DWORD64 p1, LPVOID p2, LPVOID p3) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, DWORD64, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymGetLineFromAddr") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" BOOL WINAPI SymGetLineFromAddrW(void) {
    return 0;
}

extern "C" BOOL WINAPI SymGetLineFromAddrW64(LONG p0, DWORD64 p1, LPVOID p2, LPVOID p3) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, DWORD64, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymGetLineFromAddrW64") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" BOOL WINAPI SymGetLineFromInlineContext(LONG p0, DWORD64 p1, LONG p2, DWORD64 p3, LPVOID p4, LPVOID p5) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, DWORD64, LONG, DWORD64, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymGetLineFromInlineContext") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5);
}

extern "C" BOOL WINAPI SymGetLineFromInlineContextW(LONG p0, DWORD64 p1, LONG p2, DWORD64 p3, LPVOID p4, LPVOID p5) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, DWORD64, LONG, DWORD64, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymGetLineFromInlineContextW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5);
}

extern "C" BOOL WINAPI SymGetLineFromName64(LONG p0, LPCSTR p1, LPCSTR p2, LONG p3, LPVOID p4, LPVOID p5) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, LPCSTR, LPCSTR, LONG, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymGetLineFromName64") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5);
}

extern "C" BOOL WINAPI SymGetLineFromName(LONG p0, LPCSTR p1, LPCSTR p2, LONG p3, LPVOID p4, LPVOID p5) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, LPCSTR, LPCSTR, LONG, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymGetLineFromName") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5);
}

extern "C" BOOL WINAPI SymGetLineFromNameW64(LONG p0, LPCWSTR p1, LPCWSTR p2, LONG p3, LONG p4, LPVOID p5, LPVOID p6) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, LPCWSTR, LPCWSTR, LONG, LONG, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymGetLineFromNameW64") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5, p6);
}

extern "C" BOOL WINAPI SymGetLineNext64(LONG p0, LPVOID p1) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymGetLineNext64") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" BOOL WINAPI SymGetLineNext(LONG p0, LPVOID p1) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymGetLineNext") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" BOOL WINAPI SymGetLineNextW64(LONG p0, LPVOID p1) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymGetLineNextW64") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" BOOL WINAPI SymGetLinePrev64(LONG p0, LPVOID p1) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymGetLinePrev64") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" BOOL WINAPI SymGetLinePrev(LONG p0, LPVOID p1) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymGetLinePrev") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" BOOL WINAPI SymGetLinePrevW64(LONG p0, LPVOID p1) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymGetLinePrevW64") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" BOOL WINAPI SymGetModuleBase64(LONG p0, DWORD64 p1) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, DWORD64);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymGetModuleBase64") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" BOOL WINAPI SymGetModuleBase(LONG p0, DWORD64 p1) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, DWORD64);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymGetModuleBase") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" BOOL WINAPI SymGetModuleInfo64(LONG p0, DWORD64 p1, LPVOID p2) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, DWORD64, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymGetModuleInfo64") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" BOOL WINAPI SymGetModuleInfo(LONG p0, DWORD64 p1, LPVOID p2) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, DWORD64, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymGetModuleInfo") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" BOOL WINAPI SymGetModuleInfoW64(LONG p0, DWORD64 p1, LPVOID p2) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, DWORD64, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymGetModuleInfoW64") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" BOOL WINAPI SymGetModuleInfoW(LONG p0, DWORD64 p1, LPVOID p2) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, DWORD64, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymGetModuleInfoW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" BOOL WINAPI SymGetOmapBlockBase(void) {
    return 0;
}

extern "C" BOOL WINAPI SymGetOptions(void) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(void);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymGetOptions") : nullptr);
    if (!fn) return 0;
    return fn();
}

extern "C" BOOL WINAPI SymGetScope(void) {
    return 0;
}

extern "C" BOOL WINAPI SymGetScopeW(void) {
    return 0;
}

extern "C" BOOL WINAPI SymGetSearchPath(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymGetSearchPath") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" BOOL WINAPI SymGetSearchPathW(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymGetSearchPathW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" BOOL WINAPI SymGetSourceFile(void) {
    return 0;
}

extern "C" BOOL WINAPI SymGetSourceFileFromToken(void) {
    return 0;
}

extern "C" BOOL WINAPI SymGetSourceFileFromTokenW(void) {
    return 0;
}

extern "C" BOOL WINAPI SymGetSourceFileToken(LPVOID p0, DWORD64 p1, LPCSTR p2, LPVOID p3, LPVOID p4) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LPVOID, DWORD64, LPCSTR, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymGetSourceFileToken") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4);
}

extern "C" BOOL WINAPI SymGetSourceFileTokenW(LPVOID p0, DWORD64 p1, LPCWSTR p2, LPVOID p3, LPVOID p4) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LPVOID, DWORD64, LPCWSTR, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymGetSourceFileTokenW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4);
}

extern "C" BOOL WINAPI SymGetSourceFileW(void) {
    return 0;
}

extern "C" BOOL WINAPI SymGetSourceVarFromToken(void) {
    return 0;
}

extern "C" BOOL WINAPI SymGetSourceVarFromTokenW(void) {
    return 0;
}

extern "C" BOOL WINAPI SymGetSymFromAddr64(LONG p0, DWORD64 p1, LPVOID p2, LPVOID p3) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, DWORD64, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymGetSymFromAddr64") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" BOOL WINAPI SymGetSymFromAddr(LONG p0, DWORD64 p1, LPVOID p2, LPVOID p3) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, DWORD64, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymGetSymFromAddr") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" BOOL WINAPI SymGetSymFromName64(LONG p0, LPCSTR p1, LPVOID p2) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, LPCSTR, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymGetSymFromName64") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" BOOL WINAPI SymGetSymFromName(LONG p0, LPCSTR p1, LPVOID p2) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, LPCSTR, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymGetSymFromName") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" BOOL WINAPI SymGetSymNext64(LONG p0, LPVOID p1) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymGetSymNext64") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" BOOL WINAPI SymGetSymNext(LONG p0, LPVOID p1) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymGetSymNext") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" BOOL WINAPI SymGetSymPrev64(LONG p0, LPVOID p1) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymGetSymPrev64") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" BOOL WINAPI SymGetSymPrev(LONG p0, LPVOID p1) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymGetSymPrev") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" BOOL WINAPI SymGetSymbolFile(void) {
    return 0;
}

extern "C" BOOL WINAPI SymGetSymbolFileW(void) {
    return 0;
}

extern "C" BOOL WINAPI SymGetTypeFromName(LPVOID p0, DWORD64 p1, LPCSTR p2, LPVOID p3) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LPVOID, DWORD64, LPCSTR, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymGetTypeFromName") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" BOOL WINAPI SymGetTypeFromNameW(void) {
    return 0;
}

extern "C" BOOL WINAPI SymGetTypeInfo(LPVOID p0, DWORD64 p1, LONG p2, LONG p3, LPVOID p4) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LPVOID, DWORD64, LONG, LONG, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymGetTypeInfo") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4);
}

extern "C" BOOL WINAPI SymGetTypeInfoEx(void) {
    return 0;
}

extern "C" BOOL WINAPI SymGetUnwindInfo(void) {
    return 0;
}

extern "C" BOOL WINAPI SymInitialize(LONG p0, LPCSTR p1, LONG p2) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, LPCSTR, LONG);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymInitialize") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" BOOL WINAPI SymInitializeW(LONG p0, LPCWSTR p1, LONG p2) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, LPCWSTR, LONG);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymInitializeW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" BOOL WINAPI SymLoadModule64(LONG p0, LONG p1, LPCSTR p2, LPCSTR p3, DWORD64 p4, LONG p5) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, LONG, LPCSTR, LPCSTR, DWORD64, LONG);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymLoadModule64") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5);
}

extern "C" BOOL WINAPI SymLoadModule(LONG p0, LONG p1, LPCSTR p2, LPCSTR p3, DWORD64 p4, LONG p5) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, LONG, LPCSTR, LPCSTR, DWORD64, LONG);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymLoadModule") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5);
}

extern "C" BOOL WINAPI SymLoadModuleEx(LONG p0, LONG p1, LPCSTR p2, LPCSTR p3, DWORD64 p4, LONG p5, LPVOID p6, LONG p7) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, LONG, LPCSTR, LPCSTR, DWORD64, LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymLoadModuleEx") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5, p6, p7);
}

extern "C" BOOL WINAPI SymLoadModuleExW(LONG p0, LONG p1, LPCWSTR p2, LPCWSTR p3, DWORD64 p4, LONG p5, LPVOID p6, LONG p7) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, LONG, LPCWSTR, LPCWSTR, DWORD64, LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymLoadModuleExW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5, p6, p7);
}

extern "C" BOOL WINAPI SymMatchFileName(LPCSTR p0, LPCSTR p1, LPVOID p2, LPVOID p3) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LPCSTR, LPCSTR, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymMatchFileName") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" BOOL WINAPI SymMatchFileNameW(LPCWSTR p0, LPCWSTR p1, LPVOID p2, LPVOID p3) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LPCWSTR, LPCWSTR, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymMatchFileNameW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" BOOL WINAPI SymMatchStringA(LPCSTR p0, LPCSTR p1, LONG p2) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LPCSTR, LPCSTR, LONG);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymMatchStringA") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" BOOL WINAPI SymMatchString(LPCSTR p0, LPCSTR p1, LONG p2) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LPCSTR, LPCSTR, LONG);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymMatchString") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" BOOL WINAPI SymMatchStringW(LPCWSTR p0, LPCWSTR p1, LONG p2) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LPCWSTR, LPCWSTR, LONG);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymMatchStringW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" BOOL WINAPI SymNext(void) {
    return 0;
}

extern "C" BOOL WINAPI SymNextW(void) {
    return 0;
}

extern "C" BOOL WINAPI SymPrev(void) {
    return 0;
}

extern "C" BOOL WINAPI SymPrevW(void) {
    return 0;
}

extern "C" BOOL WINAPI SymQueryInlineTrace(LONG p0, DWORD64 p1, LONG p2, DWORD64 p3, DWORD64 p4, LPVOID p5, LPVOID p6) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, DWORD64, LONG, DWORD64, DWORD64, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymQueryInlineTrace") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5, p6);
}

extern "C" BOOL WINAPI SymRefreshModuleList(LONG p0) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymRefreshModuleList") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" BOOL WINAPI SymRegisterCallback64(LONG p0, LPVOID p1, LPVOID p2) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymRegisterCallback64") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" BOOL WINAPI SymRegisterCallback(LONG p0, LPVOID p1, LPVOID p2) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymRegisterCallback") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" BOOL WINAPI SymRegisterCallbackW64(LONG p0, LPVOID p1, DWORD64 p2) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, LPVOID, DWORD64);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymRegisterCallbackW64") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" BOOL WINAPI SymRegisterFunctionEntryCallback64(LONG p0, LPVOID p1, LPVOID p2) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymRegisterFunctionEntryCallback64") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" BOOL WINAPI SymRegisterFunctionEntryCallback(LONG p0, LPVOID p1, LPVOID p2) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymRegisterFunctionEntryCallback") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" BOOL WINAPI SymSearch(LONG p0, DWORD64 p1, LONG p2, LONG p3, LPCSTR p4, DWORD64 p5, LPVOID p6, LPVOID p7, LONG p8) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, DWORD64, LONG, LONG, LPCSTR, DWORD64, LPVOID, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymSearch") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5, p6, p7, p8);
}

extern "C" BOOL WINAPI SymSearchW(LONG p0, DWORD64 p1, LONG p2, LONG p3, LPCWSTR p4, DWORD64 p5, LPVOID p6, LPVOID p7, LONG p8) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, DWORD64, LONG, LONG, LPCWSTR, DWORD64, LPVOID, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymSearchW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5, p6, p7, p8);
}

extern "C" BOOL WINAPI SymSetContext(LONG p0, LPVOID p1, LPVOID p2) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymSetContext") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" BOOL WINAPI SymSetExtendedOption(LONG p0, LONG p1) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, LONG);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymSetExtendedOption") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" BOOL WINAPI SymSetHomeDirectory(LONG p0, LPCSTR p1) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, LPCSTR);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymSetHomeDirectory") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" BOOL WINAPI SymSetHomeDirectoryW(LONG p0, LPCWSTR p1) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, LPCWSTR);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymSetHomeDirectoryW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" BOOL WINAPI SymSetOptions(LONG p0) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymSetOptions") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" BOOL WINAPI SymSetParentWindow(LONG p0) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymSetParentWindow") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" BOOL WINAPI SymSetScopeFromAddr(LPVOID p0, DWORD64 p1) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LPVOID, DWORD64);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymSetScopeFromAddr") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" BOOL WINAPI SymSetScopeFromIndex(LPVOID p0, DWORD64 p1, LONG p2) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LPVOID, DWORD64, LONG);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymSetScopeFromIndex") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" BOOL WINAPI SymSetScopeFromInlineContext(LPVOID p0, DWORD64 p1, LONG p2) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LPVOID, DWORD64, LONG);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymSetScopeFromInlineContext") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" BOOL WINAPI SymSetSearchPath(LONG p0, LPCSTR p1) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, LPCSTR);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymSetSearchPath") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" BOOL WINAPI SymSetSearchPathW(LONG p0, LPCWSTR p1) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, LPCWSTR);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymSetSearchPathW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" BOOL WINAPI SymSrvDeltaName(void) {
    return 0;
}

extern "C" BOOL WINAPI SymSrvDeltaNameW(void) {
    return 0;
}

extern "C" BOOL WINAPI SymSrvGetFileIndexInfo(LPCSTR p0, LPVOID p1, LONG p2) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LPCSTR, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymSrvGetFileIndexInfo") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" BOOL WINAPI SymSrvGetFileIndexInfoW(LPCWSTR p0, LPVOID p1, LONG p2) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LPCWSTR, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymSrvGetFileIndexInfoW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" BOOL WINAPI SymSrvGetFileIndexString(void) {
    return 0;
}

extern "C" BOOL WINAPI SymSrvGetFileIndexStringW(void) {
    return 0;
}

extern "C" BOOL WINAPI SymSrvGetFileIndexes(LPCSTR p0, LPVOID p1, LPVOID p2, LPVOID p3, LONG p4) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LPCSTR, LPVOID, LPVOID, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymSrvGetFileIndexes") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4);
}

extern "C" BOOL WINAPI SymSrvGetFileIndexesW(LPCWSTR p0, LPVOID p1, LPVOID p2, LPVOID p3, LONG p4) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LPCWSTR, LPVOID, LPVOID, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymSrvGetFileIndexesW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4);
}

extern "C" BOOL WINAPI SymSrvGetSupplement(void) {
    return 0;
}

extern "C" BOOL WINAPI SymSrvGetSupplementW(void) {
    return 0;
}

extern "C" BOOL WINAPI SymSrvIsStore(void) {
    return 0;
}

extern "C" BOOL WINAPI SymSrvIsStoreW(void) {
    return 0;
}

extern "C" BOOL WINAPI SymSrvStoreFile(void) {
    return 0;
}

extern "C" BOOL WINAPI SymSrvStoreFileW(void) {
    return 0;
}

extern "C" BOOL WINAPI SymSrvStoreSupplement(void) {
    return 0;
}

extern "C" BOOL WINAPI SymSrvStoreSupplementW(void) {
    return 0;
}

extern "C" BOOL WINAPI SymSetSymWithAddr64(void) {
    return 0;
}

extern "C" BOOL WINAPI SymUnDName64(LPVOID p0, LPCSTR p1, LONG p2) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LPVOID, LPCSTR, LONG);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymUnDName64") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" BOOL WINAPI SymUnDName(LPVOID p0, LPCSTR p1, LONG p2) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LPVOID, LPCSTR, LONG);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymUnDName") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" BOOL WINAPI SymUnloadModule64(LONG p0, DWORD64 p1) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, DWORD64);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymUnloadModule64") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" BOOL WINAPI SymUnloadModule(LONG p0, DWORD64 p1) {
    if (!LoadRealDbghelp()) return 0;
    typedef BOOL (WINAPI *PFN)(LONG, DWORD64);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "SymUnloadModule") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" DWORD WINAPI UnDecorateSymbolName(LPCSTR p0, LPVOID p1, LONG p2, LONG p3) {
    if (!LoadRealDbghelp()) return 0;
    typedef DWORD (WINAPI *PFN)(LPCSTR, LPVOID, LONG, LONG);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "UnDecorateSymbolName") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" DWORD WINAPI UnDecorateSymbolNameW(LPCWSTR p0, LPVOID p1, LONG p2, LONG p3) {
    if (!LoadRealDbghelp()) return 0;
    typedef DWORD (WINAPI *PFN)(LPCWSTR, LPVOID, LONG, LONG);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "UnDecorateSymbolNameW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" LONG WINAPI WinDbgExtensionDllInit(LPVOID p0, LONG p1, LONG p2) {
    if (!LoadRealDbghelp()) return 0;
    typedef LONG (WINAPI *PFN)(LPVOID, LONG, LONG);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "WinDbgExtensionDllInit") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" LONG WINAPI wine_get_module_information(LONG p0, DWORD64 p1, LPVOID p2, LONG p3) {
    if (!LoadRealDbghelp()) return 0;
    typedef LONG (WINAPI *PFN)(LONG, DWORD64, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealDbghelp() ? GetProcAddress(g_dbghelp_module, "wine_get_module_information") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}
