/*
 * winmm.dll proxy. Generated by scripts/gen_proxy_from_spec.py - paste into proxy_dll/.
 */

#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <Windows.h>
#include <string>

#include "winmm_proxy_init.hpp"

static HMODULE g_winmm_module = nullptr;

static bool LoadRealWinMM() {
    if (g_winmm_module != nullptr) return true;
    HMODULE hSelf = GetModuleHandleW(L"winmm.dll");
    if (hSelf) {
        WCHAR self_path[MAX_PATH];
        if (GetModuleFileNameW(hSelf, self_path, MAX_PATH) != 0) {
            std::wstring dir(self_path);
            size_t last = dir.find_last_of(L"\\/");
            if (last != std::wstring::npos) dir.resize(last + 1);
            std::wstring hooked = dir + L"winmmHooked.dll";
            if (GetFileAttributesW(hooked.c_str()) != INVALID_FILE_ATTRIBUTES) {
                g_winmm_module = LoadLibraryW(hooked.c_str());
            }
        }
    }
    if (g_winmm_module == nullptr) {
        WCHAR system_path[MAX_PATH];
        if (GetSystemDirectoryW(system_path, MAX_PATH) != 0) {
            std::wstring path = std::wstring(system_path) + L"\\winmm.dll";
            g_winmm_module = LoadLibraryW(path.c_str());
        }
    }
    return g_winmm_module != nullptr;
}

void LoadRealWinMMFromDllMain() { (void)LoadRealWinMM(); }

extern "C" UINT WINAPI PlaySoundA(LPVOID p0, LONG p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LPVOID, LONG, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "PlaySoundA") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI WINMM_3(void) {
    return 0;
}

extern "C" UINT WINAPI WINMM_4(void) {
    return 0;
}

extern "C" UINT WINAPI CloseDriver(LONG p0, LONG p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LONG, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "CloseDriver") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI DefDriverProc(LONG p0, LONG p1, LONG p2, LONG p3, LONG p4) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LONG, LONG, LONG, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "DefDriverProc") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4);
}

extern "C" UINT WINAPI DriverCallback(LONG p0, LONG p1, LONG p2, LONG p3, LONG p4, LONG p5, LONG p6) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LONG, LONG, LONG, LONG, LONG, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "DriverCallback") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5, p6);
}

extern "C" UINT WINAPI DrvClose(LONG p0, LONG p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LONG, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "DrvClose") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI DrvDefDriverProc(LONG p0, LONG p1, LONG p2, LONG p3, LONG p4) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LONG, LONG, LONG, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "DrvDefDriverProc") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4);
}

extern "C" UINT WINAPI DrvGetModuleHandle(LONG p0) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "DrvGetModuleHandle") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" UINT WINAPI DrvOpen(LPCWSTR p0, LPCWSTR p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LPCWSTR, LPCWSTR, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "DrvOpen") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI DrvOpenA(LPCSTR p0, LPCSTR p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LPCSTR, LPCSTR, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "DrvOpenA") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI DrvSendMessage(LONG p0, LONG p1, LONG p2, LONG p3) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LONG, LONG, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "DrvSendMessage") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" UINT WINAPI GetDriverFlags(LONG p0) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "GetDriverFlags") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" UINT WINAPI GetDriverModuleHandle(LONG p0) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "GetDriverModuleHandle") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" UINT WINAPI OpenDriver(LPCWSTR p0, LPCWSTR p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LPCWSTR, LPCWSTR, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "OpenDriver") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI OpenDriverA(LPCSTR p0, LPCSTR p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LPCSTR, LPCSTR, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "OpenDriverA") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI PlaySound(LPVOID p0, LONG p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LPVOID, LONG, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "PlaySound") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI PlaySoundW(LPVOID p0, LONG p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LPVOID, LONG, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "PlaySoundW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI SendDriverMessage(LONG p0, LONG p1, LONG p2, LONG p3) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LONG, LONG, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "SendDriverMessage") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" UINT WINAPI auxGetDevCapsA(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "auxGetDevCapsA") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI auxGetDevCapsW(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "auxGetDevCapsW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI auxGetNumDevs(void) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(void);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "auxGetNumDevs") : nullptr);
    if (!fn) return 0;
    return fn();
}

extern "C" UINT WINAPI auxGetVolume(LONG p0, LPVOID p1) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "auxGetVolume") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" UINT WINAPI auxOutMessage(LONG p0, LONG p1, LONG p2, LONG p3) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LONG, LONG, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "auxOutMessage") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" UINT WINAPI auxSetVolume(LONG p0, LONG p1) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "auxSetVolume") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" UINT WINAPI joyConfigChanged(LONG p0) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "joyConfigChanged") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" UINT WINAPI joyGetDevCapsA(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "joyGetDevCapsA") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI joyGetDevCapsW(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "joyGetDevCapsW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI joyGetNumDevs(void) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(void);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "joyGetNumDevs") : nullptr);
    if (!fn) return 0;
    return fn();
}

extern "C" UINT WINAPI joyGetPos(LONG p0, LPVOID p1) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "joyGetPos") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" UINT WINAPI joyGetPosEx(LONG p0, LPVOID p1) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "joyGetPosEx") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" UINT WINAPI joyGetThreshold(LONG p0, LPVOID p1) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "joyGetThreshold") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" UINT WINAPI joyReleaseCapture(LONG p0) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "joyReleaseCapture") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" UINT WINAPI joySetCapture(LONG p0, LONG p1, LONG p2, LONG p3) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LONG, LONG, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "joySetCapture") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" UINT WINAPI joySetThreshold(LONG p0, LONG p1) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "joySetThreshold") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" UINT WINAPI mciDriverNotify(LONG p0, LONG p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LONG, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mciDriverNotify") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI mciDriverYield(LONG p0) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mciDriverYield") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" UINT WINAPI mciExecute(LPCSTR p0) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LPCSTR);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mciExecute") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" UINT WINAPI mciFreeCommandResource(LONG p0) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mciFreeCommandResource") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" UINT WINAPI mciGetCreatorTask(LONG p0) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mciGetCreatorTask") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" UINT WINAPI mciGetDeviceIDA(LPCSTR p0) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LPCSTR);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mciGetDeviceIDA") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" UINT WINAPI mciGetDeviceIDFromElementIDA(LONG p0, LPCSTR p1) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPCSTR);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mciGetDeviceIDFromElementIDA") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" UINT WINAPI mciGetDeviceIDFromElementIDW(LONG p0, LPCWSTR p1) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPCWSTR);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mciGetDeviceIDFromElementIDW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" UINT WINAPI mciGetDeviceIDW(LPCWSTR p0) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LPCWSTR);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mciGetDeviceIDW") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" UINT WINAPI mciGetDriverData(LONG p0) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mciGetDriverData") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" UINT WINAPI mciGetErrorStringA(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mciGetErrorStringA") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI mciGetErrorStringW(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mciGetErrorStringW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI mciGetYieldProc(LONG p0, LPVOID p1) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mciGetYieldProc") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" UINT WINAPI mciLoadCommandResource(LONG p0, LPCWSTR p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPCWSTR, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mciLoadCommandResource") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI mciSendCommandA(LONG p0, LONG p1, LONG p2, LONG p3) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LONG, LONG, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mciSendCommandA") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" UINT WINAPI mciSendCommandW(LONG p0, LONG p1, LONG p2, LONG p3) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LONG, LONG, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mciSendCommandW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" UINT WINAPI mciSendStringA(LPCSTR p0, LPVOID p1, LONG p2, LONG p3) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LPCSTR, LPVOID, LONG, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mciSendStringA") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" UINT WINAPI mciSendStringW(LPCWSTR p0, LPVOID p1, LONG p2, LONG p3) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LPCWSTR, LPVOID, LONG, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mciSendStringW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" UINT WINAPI mciSetDriverData(LONG p0, LONG p1) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mciSetDriverData") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" UINT WINAPI mciSetYieldProc(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mciSetYieldProc") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI midiConnect(LONG p0, LONG p1, LPVOID p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LONG, LPVOID);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "midiConnect") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI midiDisconnect(LONG p0, LONG p1, LPVOID p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LONG, LPVOID);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "midiDisconnect") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI midiInAddBuffer(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "midiInAddBuffer") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI midiInClose(LONG p0) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "midiInClose") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" UINT WINAPI midiInGetDevCapsA(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "midiInGetDevCapsA") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI midiInGetDevCapsW(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "midiInGetDevCapsW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI midiInGetErrorTextA(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "midiInGetErrorTextA") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI midiInGetErrorTextW(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "midiInGetErrorTextW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI midiInGetID(LONG p0, LPVOID p1) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "midiInGetID") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" UINT WINAPI midiInGetNumDevs(void) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(void);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "midiInGetNumDevs") : nullptr);
    if (!fn) return 0;
    return fn();
}

extern "C" UINT WINAPI midiInMessage(LONG p0, LONG p1, LONG p2, LONG p3) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LONG, LONG, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "midiInMessage") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" UINT WINAPI midiInOpen(LPVOID p0, LONG p1, LONG p2, LONG p3, LONG p4) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LPVOID, LONG, LONG, LONG, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "midiInOpen") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4);
}

extern "C" UINT WINAPI midiInPrepareHeader(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "midiInPrepareHeader") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI midiInReset(LONG p0) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "midiInReset") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" UINT WINAPI midiInStart(LONG p0) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "midiInStart") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" UINT WINAPI midiInStop(LONG p0) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "midiInStop") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" UINT WINAPI midiInUnprepareHeader(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "midiInUnprepareHeader") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI midiOutCacheDrumPatches(LONG p0, LONG p1, LPVOID p2, LONG p3) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "midiOutCacheDrumPatches") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" UINT WINAPI midiOutCachePatches(LONG p0, LONG p1, LPVOID p2, LONG p3) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "midiOutCachePatches") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" UINT WINAPI midiOutClose(LONG p0) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "midiOutClose") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" UINT WINAPI midiOutGetDevCapsA(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "midiOutGetDevCapsA") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI midiOutGetDevCapsW(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "midiOutGetDevCapsW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI midiOutGetErrorTextA(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "midiOutGetErrorTextA") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI midiOutGetErrorTextW(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "midiOutGetErrorTextW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI midiOutGetID(LONG p0, LPVOID p1) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "midiOutGetID") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" UINT WINAPI midiOutGetNumDevs(void) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(void);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "midiOutGetNumDevs") : nullptr);
    if (!fn) return 0;
    return fn();
}

extern "C" UINT WINAPI midiOutGetVolume(LONG p0, LPVOID p1) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "midiOutGetVolume") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" UINT WINAPI midiOutLongMsg(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "midiOutLongMsg") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI midiOutMessage(LONG p0, LONG p1, LONG p2, LONG p3) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LONG, LONG, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "midiOutMessage") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" UINT WINAPI midiOutOpen(LPVOID p0, LONG p1, LONG p2, LONG p3, LONG p4) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LPVOID, LONG, LONG, LONG, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "midiOutOpen") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4);
}

extern "C" UINT WINAPI midiOutPrepareHeader(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "midiOutPrepareHeader") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI midiOutReset(LONG p0) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "midiOutReset") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" UINT WINAPI midiOutSetVolume(LONG p0, LONG p1) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "midiOutSetVolume") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" UINT WINAPI midiOutShortMsg(LONG p0, LONG p1) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "midiOutShortMsg") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" UINT WINAPI midiOutUnprepareHeader(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "midiOutUnprepareHeader") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI midiStreamClose(LONG p0) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "midiStreamClose") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" UINT WINAPI midiStreamOpen(LPVOID p0, LPVOID p1, LONG p2, LONG p3, LONG p4, LONG p5) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LPVOID, LPVOID, LONG, LONG, LONG, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "midiStreamOpen") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5);
}

extern "C" UINT WINAPI midiStreamOut(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "midiStreamOut") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI midiStreamPause(LONG p0) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "midiStreamPause") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" UINT WINAPI midiStreamPosition(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "midiStreamPosition") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI midiStreamProperty(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "midiStreamProperty") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI midiStreamRestart(LONG p0) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "midiStreamRestart") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" UINT WINAPI midiStreamStop(LONG p0) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "midiStreamStop") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" UINT WINAPI mixerClose(LONG p0) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mixerClose") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" UINT WINAPI mixerGetControlDetailsA(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mixerGetControlDetailsA") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI mixerGetControlDetailsW(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mixerGetControlDetailsW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI mixerGetDevCapsA(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mixerGetDevCapsA") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI mixerGetDevCapsW(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mixerGetDevCapsW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI mixerGetID(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mixerGetID") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI mixerGetLineControlsA(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mixerGetLineControlsA") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI mixerGetLineControlsW(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mixerGetLineControlsW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI mixerGetLineInfoA(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mixerGetLineInfoA") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI mixerGetLineInfoW(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mixerGetLineInfoW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI mixerGetNumDevs(void) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(void);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mixerGetNumDevs") : nullptr);
    if (!fn) return 0;
    return fn();
}

extern "C" UINT WINAPI mixerMessage(LONG p0, LONG p1, LONG p2, LONG p3) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LONG, LONG, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mixerMessage") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" UINT WINAPI mixerOpen(LPVOID p0, LONG p1, LONG p2, LONG p3, LONG p4) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LPVOID, LONG, LONG, LONG, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mixerOpen") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4);
}

extern "C" UINT WINAPI mixerSetControlDetails(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mixerSetControlDetails") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI mmGetCurrentTask(void) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(void);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mmGetCurrentTask") : nullptr);
    if (!fn) return 0;
    return fn();
}

extern "C" UINT WINAPI mmTaskBlock(LONG p0) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mmTaskBlock") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" UINT WINAPI mmTaskCreate(LPVOID p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LPVOID, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mmTaskCreate") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI mmTaskSignal(LONG p0) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mmTaskSignal") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" UINT WINAPI mmTaskYield(void) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(void);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mmTaskYield") : nullptr);
    if (!fn) return 0;
    return fn();
}

extern "C" UINT WINAPI mmioAdvance(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mmioAdvance") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI mmioAscend(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mmioAscend") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI mmioClose(LONG p0, LONG p1) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mmioClose") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" UINT WINAPI mmioCreateChunk(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mmioCreateChunk") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI mmioDescend(LONG p0, LPVOID p1, LPVOID p2, LONG p3) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mmioDescend") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" UINT WINAPI mmioFlush(LONG p0, LONG p1) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mmioFlush") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" UINT WINAPI mmioGetInfo(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mmioGetInfo") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI mmioInstallIOProc16(void) {
    return 0;
}

extern "C" UINT WINAPI mmioInstallIOProcA(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mmioInstallIOProcA") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI mmioInstallIOProcW(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mmioInstallIOProcW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI mmioOpenA(LPCSTR p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LPCSTR, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mmioOpenA") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI mmioOpenW(LPCWSTR p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LPCWSTR, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mmioOpenW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI mmioRead(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mmioRead") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI mmioRenameA(LPCSTR p0, LPCSTR p1, LPVOID p2, LONG p3) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LPCSTR, LPCSTR, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mmioRenameA") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" UINT WINAPI mmioRenameW(LPCWSTR p0, LPCWSTR p1, LPVOID p2, LONG p3) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LPCWSTR, LPCWSTR, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mmioRenameW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" UINT WINAPI mmioSeek(LONG p0, LONG p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LONG, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mmioSeek") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI mmioSendMessage(LONG p0, LONG p1, LONG p2, LONG p3) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LONG, LONG, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mmioSendMessage") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" UINT WINAPI mmioSetBuffer(LONG p0, LPVOID p1, LONG p2, LONG p3) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mmioSetBuffer") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" UINT WINAPI mmioSetInfo(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mmioSetInfo") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI mmioStringToFOURCCA(LPCSTR p0, LONG p1) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LPCSTR, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mmioStringToFOURCCA") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" UINT WINAPI mmioStringToFOURCCW(LPCWSTR p0, LONG p1) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LPCWSTR, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mmioStringToFOURCCW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" UINT WINAPI mmioWrite(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mmioWrite") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI mmsystemGetVersion(void) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(void);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "mmsystemGetVersion") : nullptr);
    if (!fn) return 0;
    return fn();
}

extern "C" UINT WINAPI sndPlaySoundA(LPVOID p0, LONG p1) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "sndPlaySoundA") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" UINT WINAPI sndPlaySoundW(LPVOID p0, LONG p1) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "sndPlaySoundW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" UINT WINAPI timeBeginPeriod(LONG p0) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "timeBeginPeriod") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" UINT WINAPI timeEndPeriod(LONG p0) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "timeEndPeriod") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" UINT WINAPI timeGetDevCaps(LPVOID p0, LONG p1) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "timeGetDevCaps") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" UINT WINAPI timeGetSystemTime(LPVOID p0, LONG p1) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "timeGetSystemTime") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" UINT WINAPI timeGetTime(void) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(void);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "timeGetTime") : nullptr);
    if (!fn) return 0;
    return fn();
}

extern "C" UINT WINAPI timeKillEvent(LONG p0) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "timeKillEvent") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" UINT WINAPI timeSetEvent(LONG p0, LONG p1, LPVOID p2, LONG p3, LONG p4) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LONG, LPVOID, LONG, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "timeSetEvent") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4);
}

extern "C" UINT WINAPI waveInAddBuffer(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "waveInAddBuffer") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI waveInClose(LONG p0) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "waveInClose") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" UINT WINAPI waveInGetDevCapsA(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "waveInGetDevCapsA") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI waveInGetDevCapsW(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "waveInGetDevCapsW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI waveInGetErrorTextA(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "waveInGetErrorTextA") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI waveInGetErrorTextW(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "waveInGetErrorTextW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI waveInGetID(LONG p0, LPVOID p1) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "waveInGetID") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" UINT WINAPI waveInGetNumDevs(void) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(void);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "waveInGetNumDevs") : nullptr);
    if (!fn) return 0;
    return fn();
}

extern "C" UINT WINAPI waveInGetPosition(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "waveInGetPosition") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI waveInMessage(LONG p0, LONG p1, LONG p2, LONG p3) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LONG, LONG, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "waveInMessage") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" UINT WINAPI waveInOpen(LPVOID p0, LONG p1, LPVOID p2, LONG p3, LONG p4, LONG p5) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LPVOID, LONG, LPVOID, LONG, LONG, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "waveInOpen") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5);
}

extern "C" UINT WINAPI waveInPrepareHeader(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "waveInPrepareHeader") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI waveInReset(LONG p0) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "waveInReset") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" UINT WINAPI waveInStart(LONG p0) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "waveInStart") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" UINT WINAPI waveInStop(LONG p0) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "waveInStop") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" UINT WINAPI waveInUnprepareHeader(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "waveInUnprepareHeader") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI waveOutBreakLoop(LONG p0) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "waveOutBreakLoop") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" UINT WINAPI waveOutClose(LONG p0) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "waveOutClose") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" UINT WINAPI waveOutGetDevCapsA(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "waveOutGetDevCapsA") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI waveOutGetDevCapsW(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "waveOutGetDevCapsW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI waveOutGetErrorTextA(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "waveOutGetErrorTextA") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI waveOutGetErrorTextW(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "waveOutGetErrorTextW") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI waveOutGetID(LONG p0, LPVOID p1) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "waveOutGetID") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" UINT WINAPI waveOutGetNumDevs(void) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(void);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "waveOutGetNumDevs") : nullptr);
    if (!fn) return 0;
    return fn();
}

extern "C" UINT WINAPI waveOutGetPitch(LONG p0, LPVOID p1) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "waveOutGetPitch") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" UINT WINAPI waveOutGetPlaybackRate(LONG p0, LPVOID p1) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "waveOutGetPlaybackRate") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" UINT WINAPI waveOutGetPosition(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "waveOutGetPosition") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI waveOutGetVolume(LONG p0, LPVOID p1) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "waveOutGetVolume") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" UINT WINAPI waveOutMessage(LONG p0, LONG p1, LONG p2, LONG p3) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LONG, LONG, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "waveOutMessage") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" UINT WINAPI waveOutOpen(LPVOID p0, LONG p1, LPVOID p2, LONG p3, LONG p4, LONG p5) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LPVOID, LONG, LPVOID, LONG, LONG, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "waveOutOpen") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5);
}

extern "C" UINT WINAPI waveOutPause(LONG p0) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "waveOutPause") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" UINT WINAPI waveOutPrepareHeader(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "waveOutPrepareHeader") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI waveOutReset(LONG p0) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "waveOutReset") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" UINT WINAPI waveOutRestart(LONG p0) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "waveOutRestart") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" UINT WINAPI waveOutSetPitch(LONG p0, LONG p1) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "waveOutSetPitch") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" UINT WINAPI waveOutSetPlaybackRate(LONG p0, LONG p1) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "waveOutSetPlaybackRate") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" UINT WINAPI waveOutSetVolume(LONG p0, LONG p1) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "waveOutSetVolume") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" UINT WINAPI waveOutUnprepareHeader(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "waveOutUnprepareHeader") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" UINT WINAPI waveOutWrite(LONG p0, LPVOID p1, LONG p2) {
    if (!LoadRealWinMM()) return 0;
    typedef UINT (WINAPI *PFN)(LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealWinMM() ? GetProcAddress(g_winmm_module, "waveOutWrite") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}
