#!/usr/bin/env python3
"""
Generate opengl32_proxy.cpp: forwarding stubs for all gl* and wgl* exports.
Reads export names from Display Commander's exports.def (opengl32 section)
and uses embedded OpenGL 1.1 / WGL signatures to output the .cpp.
Run from repo root: python scripts/gen_opengl32_proxy.py
Output: src/addons/display_commander/proxy_dll/opengl32_proxy.cpp
"""

import re
import os

# (return_type, [(param_type, param_name), ...]) per symbol.
# Types must match Windows opengl32 ABI (GLenum, GLsizei, const GLvoid*, etc.).
SIGS = {
    "glAccum": ("void", [("GLenum", "op"), ("GLfloat", "value")]),
    "glAlphaFunc": ("void", [("GLenum", "func"), ("GLfloat", "ref")]),
    "glAreTexturesResident": ("GLboolean", [("GLsizei", "n"), ("const GLuint *", "textures"), ("GLboolean *", "residences")]),
    "glArrayElement": ("void", [("GLint", "i")]),
    "glBegin": ("void", [("GLenum", "mode")]),
    "glBindTexture": ("void", [("GLenum", "target"), ("GLuint", "texture")]),
    "glBitmap": ("void", [("GLsizei", "width"), ("GLsizei", "height"), ("GLfloat", "xorig"), ("GLfloat", "yorig"), ("GLfloat", "xmove"), ("GLfloat", "ymove"), ("const GLubyte *", "bitmap")]),
    "glBlendFunc": ("void", [("GLenum", "sfactor"), ("GLenum", "dfactor")]),
    "glCallList": ("void", [("GLuint", "list")]),
    "glCallLists": ("void", [("GLsizei", "n"), ("GLenum", "type"), ("const GLvoid *", "lists")]),
    "glClear": ("void", [("GLbitfield", "mask")]),
    "glClearAccum": ("void", [("GLfloat", "red"), ("GLfloat", "green"), ("GLfloat", "blue"), ("GLfloat", "alpha")]),
    "glClearColor": ("void", [("GLfloat", "red"), ("GLfloat", "green"), ("GLfloat", "blue"), ("GLfloat", "alpha")]),
    "glClearDepth": ("void", [("GLdouble", "depth")]),
    "glClearIndex": ("void", [("GLfloat", "c")]),
    "glClearStencil": ("void", [("GLint", "s")]),
    "glClipPlane": ("void", [("GLenum", "plane"), ("const GLdouble *", "equation")]),
    "glColor3b": ("void", [("GLbyte", "red"), ("GLbyte", "green"), ("GLbyte", "blue")]),
    "glColor3bv": ("void", [("const GLbyte *", "v")]),
    "glColor3d": ("void", [("GLdouble", "red"), ("GLdouble", "green"), ("GLdouble", "blue")]),
    "glColor3dv": ("void", [("const GLdouble *", "v")]),
    "glColor3f": ("void", [("GLfloat", "red"), ("GLfloat", "green"), ("GLfloat", "blue")]),
    "glColor3fv": ("void", [("const GLfloat *", "v")]),
    "glColor3i": ("void", [("GLint", "red"), ("GLint", "green"), ("GLint", "blue")]),
    "glColor3iv": ("void", [("const GLint *", "v")]),
    "glColor3s": ("void", [("GLshort", "red"), ("GLshort", "green"), ("GLshort", "blue")]),
    "glColor3sv": ("void", [("const GLshort *", "v")]),
    "glColor3ub": ("void", [("GLubyte", "red"), ("GLubyte", "green"), ("GLubyte", "blue")]),
    "glColor3ubv": ("void", [("const GLubyte *", "v")]),
    "glColor3ui": ("void", [("GLuint", "red"), ("GLuint", "green"), ("GLuint", "blue")]),
    "glColor3uiv": ("void", [("const GLuint *", "v")]),
    "glColor3us": ("void", [("GLushort", "red"), ("GLushort", "green"), ("GLushort", "blue")]),
    "glColor3usv": ("void", [("const GLushort *", "v")]),
    "glColor4b": ("void", [("GLbyte", "red"), ("GLbyte", "green"), ("GLbyte", "blue"), ("GLbyte", "alpha")]),
    "glColor4bv": ("void", [("const GLbyte *", "v")]),
    "glColor4d": ("void", [("GLdouble", "red"), ("GLdouble", "green"), ("GLdouble", "blue"), ("GLdouble", "alpha")]),
    "glColor4dv": ("void", [("const GLdouble *", "v")]),
    "glColor4f": ("void", [("GLfloat", "red"), ("GLfloat", "green"), ("GLfloat", "blue"), ("GLfloat", "alpha")]),
    "glColor4fv": ("void", [("const GLfloat *", "v")]),
    "glColor4i": ("void", [("GLint", "red"), ("GLint", "green"), ("GLint", "blue"), ("GLint", "alpha")]),
    "glColor4iv": ("void", [("const GLint *", "v")]),
    "glColor4s": ("void", [("GLshort", "red"), ("GLshort", "green"), ("GLshort", "blue"), ("GLshort", "alpha")]),
    "glColor4sv": ("void", [("const GLshort *", "v")]),
    "glColor4ub": ("void", [("GLubyte", "red"), ("GLubyte", "green"), ("GLubyte", "blue"), ("GLubyte", "alpha")]),
    "glColor4ubv": ("void", [("const GLubyte *", "v")]),
    "glColor4ui": ("void", [("GLuint", "red"), ("GLuint", "green"), ("GLuint", "blue"), ("GLuint", "alpha")]),
    "glColor4uiv": ("void", [("const GLuint *", "v")]),
    "glColor4us": ("void", [("GLushort", "red"), ("GLushort", "green"), ("GLushort", "blue"), ("GLushort", "alpha")]),
    "glColor4usv": ("void", [("const GLushort *", "v")]),
    "glColorMask": ("void", [("GLboolean", "red"), ("GLboolean", "green"), ("GLboolean", "blue"), ("GLboolean", "alpha")]),
    "glColorMaterial": ("void", [("GLenum", "face"), ("GLenum", "mode")]),
    "glColorPointer": ("void", [("GLint", "size"), ("GLenum", "type"), ("GLsizei", "stride"), ("const GLvoid *", "pointer")]),
    "glCopyPixels": ("void", [("GLint", "x"), ("GLint", "y"), ("GLsizei", "width"), ("GLsizei", "height"), ("GLenum", "type")]),
    "glCopyTexImage1D": ("void", [("GLenum", "target"), ("GLint", "level"), ("GLenum", "internalFormat"), ("GLint", "x"), ("GLint", "y"), ("GLsizei", "width"), ("GLint", "border")]),
    "glCopyTexImage2D": ("void", [("GLenum", "target"), ("GLint", "level"), ("GLenum", "internalFormat"), ("GLint", "x"), ("GLint", "y"), ("GLsizei", "width"), ("GLsizei", "height"), ("GLint", "border")]),
    "glCopyTexSubImage1D": ("void", [("GLenum", "target"), ("GLint", "level"), ("GLint", "xoffset"), ("GLint", "x"), ("GLint", "y"), ("GLsizei", "width")]),
    "glCopyTexSubImage2D": ("void", [("GLenum", "target"), ("GLint", "level"), ("GLint", "xoffset"), ("GLint", "yoffset"), ("GLint", "x"), ("GLint", "y"), ("GLsizei", "width"), ("GLsizei", "height")]),
    "glCullFace": ("void", [("GLenum", "mode")]),
    "glDeleteLists": ("void", [("GLuint", "list"), ("GLsizei", "range")]),
    "glDeleteTextures": ("void", [("GLsizei", "n"), ("const GLuint *", "textures")]),
    "glDepthFunc": ("void", [("GLenum", "func")]),
    "glDepthMask": ("void", [("GLboolean", "flag")]),
    "glDepthRange": ("void", [("GLdouble", "zNear"), ("GLdouble", "zFar")]),
    "glDisable": ("void", [("GLenum", "cap")]),
    "glDisableClientState": ("void", [("GLenum", "array")]),
    "glDrawArrays": ("void", [("GLenum", "mode"), ("GLint", "first"), ("GLsizei", "count")]),
    "glDrawBuffer": ("void", [("GLenum", "mode")]),
    "glDrawElements": ("void", [("GLenum", "mode"), ("GLsizei", "count"), ("GLenum", "type"), ("const GLvoid *", "indices")]),
    "glDrawPixels": ("void", [("GLsizei", "width"), ("GLsizei", "height"), ("GLenum", "format"), ("GLenum", "type"), ("const GLvoid *", "pixels")]),
    "glEdgeFlag": ("void", [("GLboolean", "flag")]),
    "glEdgeFlagPointer": ("void", [("GLsizei", "stride"), ("const GLvoid *", "pointer")]),
    "glEdgeFlagv": ("void", [("const GLboolean *", "flag")]),
    "glEnable": ("void", [("GLenum", "cap")]),
    "glEnableClientState": ("void", [("GLenum", "array")]),
    "glEnd": ("void", []),
    "glEndList": ("void", []),
    "glEvalCoord1d": ("void", [("GLdouble", "u")]),
    "glEvalCoord1dv": ("void", [("const GLdouble *", "u")]),
    "glEvalCoord1f": ("void", [("GLfloat", "u")]),
    "glEvalCoord1fv": ("void", [("const GLfloat *", "u")]),
    "glEvalCoord2d": ("void", [("GLdouble", "u"), ("GLdouble", "v")]),
    "glEvalCoord2dv": ("void", [("const GLdouble *", "u")]),
    "glEvalCoord2f": ("void", [("GLfloat", "u"), ("GLfloat", "v")]),
    "glEvalCoord2fv": ("void", [("const GLfloat *", "u")]),
    "glEvalMesh1": ("void", [("GLenum", "mode"), ("GLint", "i1"), ("GLint", "i2")]),
    "glEvalMesh2": ("void", [("GLenum", "mode"), ("GLint", "i1"), ("GLint", "i2"), ("GLint", "j1"), ("GLint", "j2")]),
    "glEvalPoint1": ("void", [("GLint", "i")]),
    "glEvalPoint2": ("void", [("GLint", "i"), ("GLint", "j")]),
    "glFeedbackBuffer": ("void", [("GLsizei", "size"), ("GLenum", "type"), ("GLfloat *", "buffer")]),
    "glFinish": ("void", []),
    "glFlush": ("void", []),
    "glFogf": ("void", [("GLenum", "pname"), ("GLfloat", "param")]),
    "glFogfv": ("void", [("GLenum", "pname"), ("const GLfloat *", "params")]),
    "glFogi": ("void", [("GLenum", "pname"), ("GLint", "param")]),
    "glFogiv": ("void", [("GLenum", "pname"), ("const GLint *", "params")]),
    "glFrontFace": ("void", [("GLenum", "mode")]),
    "glFrustum": ("void", [("GLdouble", "left"), ("GLdouble", "right"), ("GLdouble", "bottom"), ("GLdouble", "top"), ("GLdouble", "zNear"), ("GLdouble", "zFar")]),
    "glGenLists": ("GLuint", [("GLsizei", "range")]),
    "glGenTextures": ("void", [("GLsizei", "n"), ("GLuint *", "textures")]),
    "glGetBooleanv": ("void", [("GLenum", "pname"), ("GLboolean *", "params")]),
    "glGetClipPlane": ("void", [("GLenum", "plane"), ("GLdouble *", "equation")]),
    "glGetDoublev": ("void", [("GLenum", "pname"), ("GLdouble *", "params")]),
    "glGetError": ("GLenum", []),
    "glGetFloatv": ("void", [("GLenum", "pname"), ("GLfloat *", "params")]),
    "glGetIntegerv": ("void", [("GLenum", "pname"), ("GLint *", "params")]),
    "glGetLightfv": ("void", [("GLenum", "light"), ("GLenum", "pname"), ("GLfloat *", "params")]),
    "glGetLightiv": ("void", [("GLenum", "light"), ("GLenum", "pname"), ("GLint *", "params")]),
    "glGetMapdv": ("void", [("GLenum", "target"), ("GLenum", "query"), ("GLdouble *", "v")]),
    "glGetMapfv": ("void", [("GLenum", "target"), ("GLenum", "query"), ("GLfloat *", "v")]),
    "glGetMapiv": ("void", [("GLenum", "target"), ("GLenum", "query"), ("GLint *", "v")]),
    "glGetMaterialfv": ("void", [("GLenum", "face"), ("GLenum", "pname"), ("GLfloat *", "params")]),
    "glGetMaterialiv": ("void", [("GLenum", "face"), ("GLenum", "pname"), ("GLint *", "params")]),
    "glGetPixelMapfv": ("void", [("GLenum", "map"), ("GLfloat *", "values")]),
    "glGetPixelMapuiv": ("void", [("GLenum", "map"), ("GLuint *", "values")]),
    "glGetPixelMapusv": ("void", [("GLenum", "map"), ("GLushort *", "values")]),
    "glGetPointerv": ("void", [("GLenum", "pname"), ("GLvoid **", "params")]),
    "glGetPolygonStipple": ("void", [("GLubyte *", "mask")]),
    "glGetString": ("const GLubyte *", [("GLenum", "name")]),
    "glGetTexEnvfv": ("void", [("GLenum", "target"), ("GLenum", "pname"), ("GLfloat *", "params")]),
    "glGetTexEnviv": ("void", [("GLenum", "target"), ("GLenum", "pname"), ("GLint *", "params")]),
    "glGetTexGendv": ("void", [("GLenum", "coord"), ("GLenum", "pname"), ("GLdouble *", "params")]),
    "glGetTexGenfv": ("void", [("GLenum", "coord"), ("GLenum", "pname"), ("GLfloat *", "params")]),
    "glGetTexGeniv": ("void", [("GLenum", "coord"), ("GLenum", "pname"), ("GLint *", "params")]),
    "glGetTexImage": ("void", [("GLenum", "target"), ("GLint", "level"), ("GLenum", "format"), ("GLenum", "type"), ("GLvoid *", "pixels")]),
    "glGetTexLevelParameterfv": ("void", [("GLenum", "target"), ("GLint", "level"), ("GLenum", "pname"), ("GLfloat *", "params")]),
    "glGetTexLevelParameteriv": ("void", [("GLenum", "target"), ("GLint", "level"), ("GLenum", "pname"), ("GLint *", "params")]),
    "glGetTexParameterfv": ("void", [("GLenum", "target"), ("GLenum", "pname"), ("GLfloat *", "params")]),
    "glGetTexParameteriv": ("void", [("GLenum", "target"), ("GLenum", "pname"), ("GLint *", "params")]),
    "glHint": ("void", [("GLenum", "target"), ("GLenum", "mode")]),
    "glIndexMask": ("void", [("GLuint", "mask")]),
    "glIndexPointer": ("void", [("GLenum", "type"), ("GLsizei", "stride"), ("const GLvoid *", "pointer")]),
    "glIndexd": ("void", [("GLdouble", "c")]),
    "glIndexdv": ("void", [("const GLdouble *", "c")]),
    "glIndexf": ("void", [("GLfloat", "c")]),
    "glIndexfv": ("void", [("const GLfloat *", "c")]),
    "glIndexi": ("void", [("GLint", "c")]),
    "glIndexiv": ("void", [("const GLint *", "c")]),
    "glIndexs": ("void", [("GLshort", "c")]),
    "glIndexsv": ("void", [("const GLshort *", "c")]),
    "glIndexub": ("void", [("GLubyte", "c")]),
    "glIndexubv": ("void", [("const GLubyte *", "c")]),
    "glInitNames": ("void", []),
    "glInterleavedArrays": ("void", [("GLenum", "format"), ("GLsizei", "stride"), ("const GLvoid *", "pointer")]),
    "glIsEnabled": ("GLboolean", [("GLenum", "cap")]),
    "glIsList": ("GLboolean", [("GLuint", "list")]),
    "glIsTexture": ("GLboolean", [("GLuint", "texture")]),
    "glLightModelf": ("void", [("GLenum", "pname"), ("GLfloat", "param")]),
    "glLightModelfv": ("void", [("GLenum", "pname"), ("const GLfloat *", "params")]),
    "glLightModeli": ("void", [("GLenum", "pname"), ("GLint", "param")]),
    "glLightModeliv": ("void", [("GLenum", "pname"), ("const GLint *", "params")]),
    "glLightf": ("void", [("GLenum", "light"), ("GLenum", "pname"), ("GLfloat", "param")]),
    "glLightfv": ("void", [("GLenum", "light"), ("GLenum", "pname"), ("const GLfloat *", "params")]),
    "glLighti": ("void", [("GLenum", "light"), ("GLenum", "pname"), ("GLint", "param")]),
    "glLightiv": ("void", [("GLenum", "light"), ("GLenum", "pname"), ("const GLint *", "params")]),
    "glLineStipple": ("void", [("GLint", "factor"), ("GLushort", "pattern")]),
    "glLineWidth": ("void", [("GLfloat", "width")]),
    "glListBase": ("void", [("GLuint", "base")]),
    "glLoadIdentity": ("void", []),
    "glLoadMatrixd": ("void", [("const GLdouble *", "m")]),
    "glLoadMatrixf": ("void", [("const GLfloat *", "m")]),
    "glLoadName": ("void", [("GLuint", "name")]),
    "glLogicOp": ("void", [("GLenum", "opcode")]),
    "glMap1d": ("void", [("GLenum", "target"), ("GLdouble", "u1"), ("GLdouble", "u2"), ("GLint", "stride"), ("GLint", "order"), ("const GLdouble *", "points")]),
    "glMap1f": ("void", [("GLenum", "target"), ("GLfloat", "u1"), ("GLfloat", "u2"), ("GLint", "stride"), ("GLint", "order"), ("const GLfloat *", "points")]),
    "glMap2d": ("void", [("GLenum", "target"), ("GLdouble", "u1"), ("GLdouble", "u2"), ("GLint", "ustride"), ("GLint", "uorder"), ("GLdouble", "v1"), ("GLdouble", "v2"), ("GLint", "vstride"), ("GLint", "vorder"), ("const GLdouble *", "points")]),
    "glMap2f": ("void", [("GLenum", "target"), ("GLfloat", "u1"), ("GLfloat", "u2"), ("GLint", "ustride"), ("GLint", "uorder"), ("GLfloat", "v1"), ("GLfloat", "v2"), ("GLint", "vstride"), ("GLint", "vorder"), ("const GLfloat *", "points")]),
    "glMapGrid1d": ("void", [("GLint", "un"), ("GLdouble", "u1"), ("GLdouble", "u2")]),
    "glMapGrid1f": ("void", [("GLint", "un"), ("GLfloat", "u1"), ("GLfloat", "u2")]),
    "glMapGrid2d": ("void", [("GLint", "un"), ("GLdouble", "u1"), ("GLdouble", "u2"), ("GLint", "vn"), ("GLdouble", "v1"), ("GLdouble", "v2")]),
    "glMapGrid2f": ("void", [("GLint", "un"), ("GLfloat", "u1"), ("GLfloat", "u2"), ("GLint", "vn"), ("GLfloat", "v1"), ("GLfloat", "v2")]),
    "glMaterialf": ("void", [("GLenum", "face"), ("GLenum", "pname"), ("GLfloat", "param")]),
    "glMaterialfv": ("void", [("GLenum", "face"), ("GLenum", "pname"), ("const GLfloat *", "params")]),
    "glMateriali": ("void", [("GLenum", "face"), ("GLenum", "pname"), ("GLint", "param")]),
    "glMaterialiv": ("void", [("GLenum", "face"), ("GLenum", "pname"), ("const GLint *", "params")]),
    "glMatrixMode": ("void", [("GLenum", "mode")]),
    "glMultMatrixd": ("void", [("const GLdouble *", "m")]),
    "glMultMatrixf": ("void", [("const GLfloat *", "m")]),
    "glNewList": ("void", [("GLuint", "list"), ("GLenum", "mode")]),
    "glNormal3b": ("void", [("GLbyte", "nx"), ("GLbyte", "ny"), ("GLbyte", "nz")]),
    "glNormal3bv": ("void", [("const GLbyte *", "v")]),
    "glNormal3d": ("void", [("GLdouble", "nx"), ("GLdouble", "ny"), ("GLdouble", "nz")]),
    "glNormal3dv": ("void", [("const GLdouble *", "v")]),
    "glNormal3f": ("void", [("GLfloat", "nx"), ("GLfloat", "ny"), ("GLfloat", "nz")]),
    "glNormal3fv": ("void", [("const GLfloat *", "v")]),
    "glNormal3i": ("void", [("GLint", "nx"), ("GLint", "ny"), ("GLint", "nz")]),
    "glNormal3iv": ("void", [("const GLint *", "v")]),
    "glNormal3s": ("void", [("GLshort", "nx"), ("GLshort", "ny"), ("GLshort", "nz")]),
    "glNormal3sv": ("void", [("const GLshort *", "v")]),
    "glNormalPointer": ("void", [("GLenum", "type"), ("GLsizei", "stride"), ("const GLvoid *", "pointer")]),
    "glOrtho": ("void", [("GLdouble", "left"), ("GLdouble", "right"), ("GLdouble", "bottom"), ("GLdouble", "top"), ("GLdouble", "zNear"), ("GLdouble", "zFar")]),
    "glPassThrough": ("void", [("GLfloat", "token")]),
    "glPixelMapfv": ("void", [("GLenum", "map"), ("GLsizei", "mapsize"), ("const GLfloat *", "values")]),
    "glPixelMapuiv": ("void", [("GLenum", "map"), ("GLsizei", "mapsize"), ("const GLuint *", "values")]),
    "glPixelMapusv": ("void", [("GLenum", "map"), ("GLsizei", "mapsize"), ("const GLushort *", "values")]),
    "glPixelStoref": ("void", [("GLenum", "pname"), ("GLfloat", "param")]),
    "glPixelStorei": ("void", [("GLenum", "pname"), ("GLint", "param")]),
    "glPixelTransferf": ("void", [("GLenum", "pname"), ("GLfloat", "param")]),
    "glPixelTransferi": ("void", [("GLenum", "pname"), ("GLint", "param")]),
    "glPixelZoom": ("void", [("GLfloat", "xfactor"), ("GLfloat", "yfactor")]),
    "glPointSize": ("void", [("GLfloat", "size")]),
    "glPolygonMode": ("void", [("GLenum", "face"), ("GLenum", "mode")]),
    "glPolygonOffset": ("void", [("GLfloat", "factor"), ("GLfloat", "units")]),
    "glPolygonStipple": ("void", [("const GLubyte *", "mask")]),
    "glPopAttrib": ("void", []),
    "glPopClientAttrib": ("void", []),
    "glPopMatrix": ("void", []),
    "glPopName": ("void", []),
    "glPrioritizeTextures": ("void", [("GLsizei", "n"), ("const GLuint *", "textures"), ("const GLclampf *", "priorities")]),
    "glPushAttrib": ("void", [("GLbitfield", "mask")]),
    "glPushClientAttrib": ("void", [("GLbitfield", "mask")]),
    "glPushMatrix": ("void", []),
    "glPushName": ("void", [("GLuint", "name")]),
    "glRasterPos2d": ("void", [("GLdouble", "x"), ("GLdouble", "y")]),
    "glRasterPos2dv": ("void", [("const GLdouble *", "v")]),
    "glRasterPos2f": ("void", [("GLfloat", "x"), ("GLfloat", "y")]),
    "glRasterPos2fv": ("void", [("const GLfloat *", "v")]),
    "glRasterPos2i": ("void", [("GLint", "x"), ("GLint", "y")]),
    "glRasterPos2iv": ("void", [("const GLint *", "v")]),
    "glRasterPos2s": ("void", [("GLshort", "x"), ("GLshort", "y")]),
    "glRasterPos2sv": ("void", [("const GLshort *", "v")]),
    "glRasterPos3d": ("void", [("GLdouble", "x"), ("GLdouble", "y"), ("GLdouble", "z")]),
    "glRasterPos3dv": ("void", [("const GLdouble *", "v")]),
    "glRasterPos3f": ("void", [("GLfloat", "x"), ("GLfloat", "y"), ("GLfloat", "z")]),
    "glRasterPos3fv": ("void", [("const GLfloat *", "v")]),
    "glRasterPos3i": ("void", [("GLint", "x"), ("GLint", "y"), ("GLint", "z")]),
    "glRasterPos3iv": ("void", [("const GLint *", "v")]),
    "glRasterPos3s": ("void", [("GLshort", "x"), ("GLshort", "y"), ("GLshort", "z")]),
    "glRasterPos3sv": ("void", [("const GLshort *", "v")]),
    "glRasterPos4d": ("void", [("GLdouble", "x"), ("GLdouble", "y"), ("GLdouble", "z"), ("GLdouble", "w")]),
    "glRasterPos4dv": ("void", [("const GLdouble *", "v")]),
    "glRasterPos4f": ("void", [("GLfloat", "x"), ("GLfloat", "y"), ("GLfloat", "z"), ("GLfloat", "w")]),
    "glRasterPos4fv": ("void", [("const GLfloat *", "v")]),
    "glRasterPos4i": ("void", [("GLint", "x"), ("GLint", "y"), ("GLint", "z"), ("GLint", "w")]),
    "glRasterPos4iv": ("void", [("const GLint *", "v")]),
    "glRasterPos4s": ("void", [("GLshort", "x"), ("GLshort", "y"), ("GLshort", "z"), ("GLshort", "w")]),
    "glRasterPos4sv": ("void", [("const GLshort *", "v")]),
    "glReadBuffer": ("void", [("GLenum", "mode")]),
    "glReadPixels": ("void", [("GLint", "x"), ("GLint", "y"), ("GLsizei", "width"), ("GLsizei", "height"), ("GLenum", "format"), ("GLenum", "type"), ("GLvoid *", "pixels")]),
    "glRectd": ("void", [("GLdouble", "x1"), ("GLdouble", "y1"), ("GLdouble", "x2"), ("GLdouble", "y2")]),
    "glRectdv": ("void", [("const GLdouble *", "v1"), ("const GLdouble *", "v2")]),
    "glRectf": ("void", [("GLfloat", "x1"), ("GLfloat", "y1"), ("GLfloat", "x2"), ("GLfloat", "y2")]),
    "glRectfv": ("void", [("const GLfloat *", "v1"), ("const GLfloat *", "v2")]),
    "glRecti": ("void", [("GLint", "x1"), ("GLint", "y1"), ("GLint", "x2"), ("GLint", "y2")]),
    "glRectiv": ("void", [("const GLint *", "v1"), ("const GLint *", "v2")]),
    "glRects": ("void", [("GLshort", "x1"), ("GLshort", "y1"), ("GLshort", "x2"), ("GLshort", "y2")]),
    "glRectsv": ("void", [("const GLshort *", "v1"), ("const GLshort *", "v2")]),
    "glRenderMode": ("GLint", [("GLenum", "mode")]),
    "glRotated": ("void", [("GLdouble", "angle"), ("GLdouble", "x"), ("GLdouble", "y"), ("GLdouble", "z")]),
    "glRotatef": ("void", [("GLfloat", "angle"), ("GLfloat", "x"), ("GLfloat", "y"), ("GLfloat", "z")]),
    "glScaled": ("void", [("GLdouble", "x"), ("GLdouble", "y"), ("GLdouble", "z")]),
    "glScalef": ("void", [("GLfloat", "x"), ("GLfloat", "y"), ("GLfloat", "z")]),
    "glScissor": ("void", [("GLint", "x"), ("GLint", "y"), ("GLsizei", "width"), ("GLsizei", "height")]),
    "glSelectBuffer": ("void", [("GLsizei", "size"), ("GLuint *", "buffer")]),
    "glShadeModel": ("void", [("GLenum", "mode")]),
    "glStencilFunc": ("void", [("GLenum", "func"), ("GLint", "ref"), ("GLuint", "mask")]),
    "glStencilMask": ("void", [("GLuint", "mask")]),
    "glStencilOp": ("void", [("GLenum", "fail"), ("GLenum", "zfail"), ("GLenum", "zpass")]),
    "glTexCoord1d": ("void", [("GLdouble", "s")]),
    "glTexCoord1dv": ("void", [("const GLdouble *", "v")]),
    "glTexCoord1f": ("void", [("GLfloat", "s")]),
    "glTexCoord1fv": ("void", [("const GLfloat *", "v")]),
    "glTexCoord1i": ("void", [("GLint", "s")]),
    "glTexCoord1iv": ("void", [("const GLint *", "v")]),
    "glTexCoord1s": ("void", [("GLshort", "s")]),
    "glTexCoord1sv": ("void", [("const GLshort *", "v")]),
    "glTexCoord2d": ("void", [("GLdouble", "s"), ("GLdouble", "t")]),
    "glTexCoord2dv": ("void", [("const GLdouble *", "v")]),
    "glTexCoord2f": ("void", [("GLfloat", "s"), ("GLfloat", "t")]),
    "glTexCoord2fv": ("void", [("const GLfloat *", "v")]),
    "glTexCoord2i": ("void", [("GLint", "s"), ("GLint", "t")]),
    "glTexCoord2iv": ("void", [("const GLint *", "v")]),
    "glTexCoord2s": ("void", [("GLshort", "s"), ("GLshort", "t")]),
    "glTexCoord2sv": ("void", [("const GLshort *", "v")]),
    "glTexCoord3d": ("void", [("GLdouble", "s"), ("GLdouble", "t"), ("GLdouble", "r")]),
    "glTexCoord3dv": ("void", [("const GLdouble *", "v")]),
    "glTexCoord3f": ("void", [("GLfloat", "s"), ("GLfloat", "t"), ("GLfloat", "r")]),
    "glTexCoord3fv": ("void", [("const GLfloat *", "v")]),
    "glTexCoord3i": ("void", [("GLint", "s"), ("GLint", "t"), ("GLint", "r")]),
    "glTexCoord3iv": ("void", [("const GLint *", "v")]),
    "glTexCoord3s": ("void", [("GLshort", "s"), ("GLshort", "t"), ("GLshort", "r")]),
    "glTexCoord3sv": ("void", [("const GLshort *", "v")]),
    "glTexCoord4d": ("void", [("GLdouble", "s"), ("GLdouble", "t"), ("GLdouble", "r"), ("GLdouble", "q")]),
    "glTexCoord4dv": ("void", [("const GLdouble *", "v")]),
    "glTexCoord4f": ("void", [("GLfloat", "s"), ("GLfloat", "t"), ("GLfloat", "r"), ("GLfloat", "q")]),
    "glTexCoord4fv": ("void", [("const GLfloat *", "v")]),
    "glTexCoord4i": ("void", [("GLint", "s"), ("GLint", "t"), ("GLint", "r"), ("GLint", "q")]),
    "glTexCoord4iv": ("void", [("const GLint *", "v")]),
    "glTexCoord4s": ("void", [("GLshort", "s"), ("GLshort", "t"), ("GLshort", "r"), ("GLshort", "q")]),
    "glTexCoord4sv": ("void", [("const GLshort *", "v")]),
    "glTexCoordPointer": ("void", [("GLint", "size"), ("GLenum", "type"), ("GLsizei", "stride"), ("const GLvoid *", "pointer")]),
    "glTexEnvf": ("void", [("GLenum", "target"), ("GLenum", "pname"), ("GLfloat", "param")]),
    "glTexEnvfv": ("void", [("GLenum", "target"), ("GLenum", "pname"), ("const GLfloat *", "params")]),
    "glTexEnvi": ("void", [("GLenum", "target"), ("GLenum", "pname"), ("GLint", "param")]),
    "glTexEnviv": ("void", [("GLenum", "target"), ("GLenum", "pname"), ("const GLint *", "params")]),
    "glTexGend": ("void", [("GLenum", "coord"), ("GLenum", "pname"), ("GLdouble", "param")]),
    "glTexGendv": ("void", [("GLenum", "coord"), ("GLenum", "pname"), ("const GLdouble *", "params")]),
    "glTexGenf": ("void", [("GLenum", "coord"), ("GLenum", "pname"), ("GLfloat", "param")]),
    "glTexGenfv": ("void", [("GLenum", "coord"), ("GLenum", "pname"), ("const GLfloat *", "params")]),
    "glTexGeni": ("void", [("GLenum", "coord"), ("GLenum", "pname"), ("GLint", "param")]),
    "glTexGeniv": ("void", [("GLenum", "coord"), ("GLenum", "pname"), ("const GLint *", "params")]),
    "glTexImage1D": ("void", [("GLenum", "target"), ("GLint", "level"), ("GLint", "internalformat"), ("GLsizei", "width"), ("GLint", "border"), ("GLenum", "format"), ("GLenum", "type"), ("const GLvoid *", "pixels")]),
    "glTexImage2D": ("void", [("GLenum", "target"), ("GLint", "level"), ("GLint", "internalformat"), ("GLsizei", "width"), ("GLsizei", "height"), ("GLint", "border"), ("GLenum", "format"), ("GLenum", "type"), ("const GLvoid *", "pixels")]),
    "glTexParameterf": ("void", [("GLenum", "target"), ("GLenum", "pname"), ("GLfloat", "param")]),
    "glTexParameterfv": ("void", [("GLenum", "target"), ("GLenum", "pname"), ("const GLfloat *", "params")]),
    "glTexParameteri": ("void", [("GLenum", "target"), ("GLenum", "pname"), ("GLint", "param")]),
    "glTexParameteriv": ("void", [("GLenum", "target"), ("GLenum", "pname"), ("const GLint *", "params")]),
    "glTexSubImage1D": ("void", [("GLenum", "target"), ("GLint", "level"), ("GLint", "xoffset"), ("GLsizei", "width"), ("GLenum", "format"), ("GLenum", "type"), ("const GLvoid *", "pixels")]),
    "glTexSubImage2D": ("void", [("GLenum", "target"), ("GLint", "level"), ("GLint", "xoffset"), ("GLint", "yoffset"), ("GLsizei", "width"), ("GLsizei", "height"), ("GLenum", "format"), ("GLenum", "type"), ("const GLvoid *", "pixels")]),
    "glTranslated": ("void", [("GLdouble", "x"), ("GLdouble", "y"), ("GLdouble", "z")]),
    "glTranslatef": ("void", [("GLfloat", "x"), ("GLfloat", "y"), ("GLfloat", "z")]),
    "glVertex2d": ("void", [("GLdouble", "x"), ("GLdouble", "y")]),
    "glVertex2dv": ("void", [("const GLdouble *", "v")]),
    "glVertex2f": ("void", [("GLfloat", "x"), ("GLfloat", "y")]),
    "glVertex2fv": ("void", [("const GLfloat *", "v")]),
    "glVertex2i": ("void", [("GLint", "x"), ("GLint", "y")]),
    "glVertex2iv": ("void", [("const GLint *", "v")]),
    "glVertex2s": ("void", [("GLshort", "x"), ("GLshort", "y")]),
    "glVertex2sv": ("void", [("const GLshort *", "v")]),
    "glVertex3d": ("void", [("GLdouble", "x"), ("GLdouble", "y"), ("GLdouble", "z")]),
    "glVertex3dv": ("void", [("const GLdouble *", "v")]),
    "glVertex3f": ("void", [("GLfloat", "x"), ("GLfloat", "y"), ("GLfloat", "z")]),
    "glVertex3fv": ("void", [("const GLfloat *", "v")]),
    "glVertex3i": ("void", [("GLint", "x"), ("GLint", "y"), ("GLint", "z")]),
    "glVertex3iv": ("void", [("const GLint *", "v")]),
    "glVertex3s": ("void", [("GLshort", "x"), ("GLshort", "y"), ("GLshort", "z")]),
    "glVertex3sv": ("void", [("const GLshort *", "v")]),
    "glVertex4d": ("void", [("GLdouble", "x"), ("GLdouble", "y"), ("GLdouble", "z"), ("GLdouble", "w")]),
    "glVertex4dv": ("void", [("const GLdouble *", "v")]),
    "glVertex4f": ("void", [("GLfloat", "x"), ("GLfloat", "y"), ("GLfloat", "z"), ("GLfloat", "w")]),
    "glVertex4fv": ("void", [("const GLfloat *", "v")]),
    "glVertex4i": ("void", [("GLint", "x"), ("GLint", "y"), ("GLint", "z"), ("GLint", "w")]),
    "glVertex4iv": ("void", [("const GLint *", "v")]),
    "glVertex4s": ("void", [("GLshort", "x"), ("GLshort", "y"), ("GLshort", "z"), ("GLshort", "w")]),
    "glVertex4sv": ("void", [("const GLshort *", "v")]),
    "glVertexPointer": ("void", [("GLint", "size"), ("GLenum", "type"), ("GLsizei", "stride"), ("const GLvoid *", "pointer")]),
    "glViewport": ("void", [("GLint", "x"), ("GLint", "y"), ("GLsizei", "width"), ("GLsizei", "height")]),
    # WGL
    "wglChoosePixelFormat": ("int", [("HDC", "hdc"), ("const PIXELFORMATDESCRIPTOR *", "ppfd")]),
    "wglCopyContext": ("BOOL", [("HGLRC", "hglrcSrc"), ("HGLRC", "hglrcDst"), ("UINT", "mask")]),
    "wglCreateContext": ("HGLRC", [("HDC", "hdc")]),
    "wglCreateLayerContext": ("HGLRC", [("HDC", "hdc"), ("int", "iLayerPlane")]),
    "wglDeleteContext": ("BOOL", [("HGLRC", "hglrc")]),
    "wglDescribeLayerPlane": ("BOOL", [("HDC", "hdc"), ("int", "iPixelFormat"), ("int", "iLayerPlane"), ("UINT", "nBytes"), ("LPLAYERPLANEDESCRIPTOR", "plpd")]),
    "wglDescribePixelFormat": ("int", [("HDC", "hdc"), ("int", "iPixelFormat"), ("UINT", "nBytes"), ("LPPIXELFORMATDESCRIPTOR", "ppfd")]),
    "wglGetCurrentContext": ("HGLRC", []),
    "wglGetCurrentDC": ("HDC", []),
    "wglGetLayerPaletteEntries": ("int", [("HDC", "hdc"), ("int", "iLayerPlane"), ("int", "iStart"), ("int", "cEntries"), ("COLORREF *", "pcr")]),
    "wglGetPixelFormat": ("int", [("HDC", "hdc")]),
    "wglGetProcAddress": ("PROC", [("LPCSTR", "lpszProc")]),
    "wglMakeCurrent": ("BOOL", [("HDC", "hdc"), ("HGLRC", "hglrc")]),
    "wglRealizeLayerPalette": ("BOOL", [("HDC", "hdc"), ("int", "iLayerPlane"), ("BOOL", "bRealize")]),
    "wglSetLayerPaletteEntries": ("int", [("HDC", "hdc"), ("int", "iLayerPlane"), ("int", "iStart"), ("int", "cEntries"), ("const COLORREF *", "pcr")]),
    "wglSetPixelFormat": ("BOOL", [("HDC", "hdc"), ("int", "iPixelFormat"), ("const PIXELFORMATDESCRIPTOR *", "ppfd")]),
    "wglShareLists": ("BOOL", [("HGLRC", "hglrc1"), ("HGLRC", "hglrc2")]),
    "wglSwapBuffers": ("BOOL", [("HDC", "hdc")]),
    "wglSwapLayerBuffers": ("BOOL", [("HDC", "hdc"), ("UINT", "planes")]),
    "wglSwapMultipleBuffers": ("DWORD", [("UINT", "nBuffers"), ("const WGLSWAP *", "pBuffers")]),
    "wglUseFontBitmapsA": ("BOOL", [("HDC", "hdc"), ("DWORD", "first"), ("DWORD", "count"), ("DWORD", "listBase")]),
    "wglUseFontBitmapsW": ("BOOL", [("HDC", "hdc"), ("DWORD", "first"), ("DWORD", "count"), ("DWORD", "listBase")]),
    "wglUseFontOutlinesA": ("BOOL", [("HDC", "hdc"), ("DWORD", "first"), ("DWORD", "count"), ("DWORD", "listBase"), ("FLOAT", "deviation"), ("FLOAT", "extrusion"), ("int", "format"), ("LPGLYPHMETRICSFLOAT", "lpgmf")]),
    "wglUseFontOutlinesW": ("BOOL", [("HDC", "hdc"), ("DWORD", "first"), ("DWORD", "count"), ("DWORD", "listBase"), ("FLOAT", "deviation"), ("FLOAT", "extrusion"), ("int", "format"), ("LPGLYPHMETRICSFLOAT", "lpgmf")]),
}

# glPrioritizeTextures uses GLclampf - add typedef in header or use float
# We use GLfloat for GLclampf in the proxy (same ABI).
# wglDescribeLayerPlane uses LPLAYERPLANEDESCRIPTOR, wglSwapMultipleBuffers uses WGLSWAP, wglUseFontOutlines uses LPGLYPHMETRICSFLOAT - Windows headers provide these.

def main():
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    def_path = os.path.join(repo_root, "src", "addons", "display_commander", "proxy_dll", "exports.def")
    out_path = os.path.join(repo_root, "src", "addons", "display_commander", "proxy_dll", "opengl32_proxy.cpp")

    names = []
    with open(def_path, "r", encoding="utf-8") as f:
        in_opengl = False
        for line in f:
            line = line.strip()
            if "; opengl32.dll" in line:
                in_opengl = True
                continue
            if in_opengl:
                if line.startswith(";") and "opengl32" not in line.lower():
                    break
                m = re.match(r"^(gl\w+|wgl\w+)\s+", line)
                if m:
                    names.append(m.group(1))

    # Build output
    lines = [
        "/*",
        " * OpenGL32 Proxy Functions",
        " * Forwards gl* and wgl* calls to the real system opengl32.dll.",
        " * Generated by scripts/gen_opengl32_proxy.py - do not edit by hand.",
        " */",
        "",
        "#include <Windows.h>",
        "#include <wingdi.h>",
        "#include <string>",
        "",
        "#include \"opengl32_proxy_init.hpp\"",
        "#include \"opengl32_proxy_gl.h\"",
        "#include \"../utils/logging.hpp\"",
        "",
        "static HMODULE g_opengl32_module = nullptr;",
        "",
        "static bool LoadRealOpenGL32() {",
        "    if (g_opengl32_module != nullptr) return true;",
        "    WCHAR system_path[MAX_PATH];",
        "    if (GetSystemDirectoryW(system_path, MAX_PATH) == 0) {",
        "        return false;",
        "    }",
        "    std::wstring path = std::wstring(system_path) + L\"\\\\opengl32.dll\";",
        "    g_opengl32_module = LoadLibraryW(path.c_str());",
        "    if (g_opengl32_module == nullptr) {",
        "        LogError(\"[opengl32_proxy] Failed to load opengl32.dll from system directory\");",
        "        return false;",
        "    }",
        "    LogInfo(\"[opengl32_proxy] Loaded opengl32.dll (system)\");",
        "    return true;",
        "}",
        "",
        "void LoadRealOpenGL32FromDllMain() { LoadRealOpenGL32(); }",
        "",
    ]

    for name in names:
        if name not in SIGS:
            raise SystemExit("Missing signature for: " + name)
        ret, params = SIGS[name]
        param_decl = ", ".join("%s %s" % (t, n) for t, n in params)
        param_names = ", ".join(n for _, n in params)
        if params:
            param_list = ", ".join(t for t, _ in params)
        else:
            param_list = "void"
        ret_void = ret == "void"
        if ret_void:
            call = "if (fn) fn(%s);" % param_names if param_names else "if (fn) fn();"
            ret_expr = ""
        else:
            call = "return fn(%s);" % param_names if param_names else "return fn();"
            ret_expr = "return (%s)0;" % ret

        lines.append("extern \"C\" %s APIENTRY %s(%s) {" % (ret, name, param_decl))
        lines.append("    if (!LoadRealOpenGL32()) %s" % ("return;" if ret_void else ("return (%s)0;" % ret)))
        lines.append("    typedef %s (APIENTRY *PFN)(%s);" % (ret, param_list))
        lines.append("    PFN fn = (PFN)GetProcAddress(g_opengl32_module, \"%s\");" % name)
        lines.append("    if (!fn) %s" % ("return;" if ret_void else ("return (%s)0;" % ret)))
        lines.append("    %s" % call)
        lines.append("}")
        lines.append("")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print("Wrote %s (%d stubs)" % (out_path, len(names)))

if __name__ == "__main__":
    main()
