#!/usr/bin/env python3
"""
Generate proxy DLL .cpp and update exports.def from a Wine .spec file.
Generic: pass DLL name and spec file path.

  python scripts/gen_d3d11_proxy.py d3d11 [spec_file]
  python scripts/gen_d3d11_proxy.py d3d11 scripts/specs/d3d11.spec

If spec_file is omitted and dll is d3d11, uses embedded d3d11.spec.
Wine spec format:
  @ stdcall Name(ptr long ...)       -> forward to real DLL
  @ stdcall Name(ptr) gdi32.Name     -> forward to real DLL then gdi32 (d3d11 only)
  @ stub Name                        -> return 0 (LONG) or E_FAIL (HRESULT)
"""

import argparse
import os
import re

# Embedded d3d11.spec (Wine) when no spec file given
D3D11_SPEC_EMBEDDED = """
@ stdcall D3D11CoreCreateDevice(ptr ptr long ptr long ptr)
@ stub D3D11CoreCreateLayeredDevice
@ stub D3D11CoreGetLayeredDeviceSize
@ stdcall D3D11CoreRegisterLayers()
@ stdcall D3D11CreateDevice(ptr long ptr long ptr long long ptr ptr ptr)
@ stdcall D3D11CreateDeviceAndSwapChain(ptr long ptr long ptr long long ptr ptr ptr ptr ptr)
@ stdcall D3D11On12CreateDevice(ptr long ptr long ptr long long ptr ptr ptr)
@ stdcall D3DKMTCheckVidPnExclusiveOwnership(ptr) gdi32.D3DKMTCheckVidPnExclusiveOwnership
@ stdcall D3DKMTCloseAdapter(ptr) gdi32.D3DKMTCloseAdapter
@ stub D3DKMTCreateAllocation
@ stub D3DKMTCreateContext
@ stdcall D3DKMTCreateDevice(ptr) gdi32.D3DKMTCreateDevice
@ stub D3DKMTCreateSynchronizationObject
@ stub D3DKMTDestroyAllocation
@ stub D3DKMTDestroyContext
@ stdcall D3DKMTDestroyDevice(ptr) gdi32.D3DKMTDestroyDevice
@ stub D3DKMTDestroySynchronizationObject
@ stub D3DKMTEscape
@ stub D3DKMTGetContextSchedulingPriority
@ stub D3DKMTGetDeviceState
@ stub D3DKMTGetDisplayModeList
@ stub D3DKMTGetMultisampleMethodList
@ stub D3DKMTGetRuntimeData
@ stub D3DKMTGetSharedPrimaryHandle
@ stub D3DKMTLock
@ stdcall D3DKMTOpenAdapterFromGdiDisplayName(ptr) gdi32.D3DKMTOpenAdapterFromGdiDisplayName
@ stub D3DKMTOpenAdapterFromHdc
@ stub D3DKMTOpenResource
@ stub D3DKMTPresent
@ stdcall D3DKMTQueryAdapterInfo(ptr) gdi32.D3DKMTQueryAdapterInfo
@ stub D3DKMTQueryAllocationResidency
@ stub D3DKMTQueryResourceInfo
@ stub D3DKMTRender
@ stub D3DKMTSetAllocationPriority
@ stub D3DKMTSetContextSchedulingPriority
@ stub D3DKMTSetDisplayMode
@ stub D3DKMTSetDisplayPrivateDriverFormat
@ stub D3DKMTSetGammaRamp
@ stdcall D3DKMTSetVidPnSourceOwner(ptr) gdi32.D3DKMTSetVidPnSourceOwner
@ stub D3DKMTSignalSynchronizationObject
@ stub D3DKMTUnlock
@ stub D3DKMTWaitForSynchronizationObject
@ stub D3DKMTWaitForVerticalBlankEvent
@ stub OpenAdapter10
@ stub OpenAdapter10_2
"""


def wine_to_c(wine_type):
    m = wine_type.strip().lower()
    if m == "ptr":
        return "LPVOID"
    if m == "long":
        return "LONG"
    if m == "str":
        return "LPCSTR"
    if m == "wstr":
        return "LPCWSTR"
    return "LPVOID"


def parse_spec(spec_text):
    """Yield (name, is_stub, params_list, use_gdi32_fallback)."""
    for line in spec_text.strip().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        m = re.match(r"@\s+stub\s+(\w+)\s*$", line)
        if m:
            yield (m.group(1), True, [], False)
            continue
        m = re.match(r"@\s+stdcall\s+(\w+)\s*\((.*?)\)\s*(?:\s+gdi32\.\w+)?\s*$", line)
        if m:
            name = m.group(1)
            params_str = m.group(2).strip()
            use_gdi32 = "gdi32." in line
            if not params_str:
                params = []
            else:
                parts = re.split(r"[\s,]+", params_str)
                params = [wine_to_c(p) for p in parts if p]
            yield (name, False, params, use_gdi32)
            continue


def return_type(name, dll_name):
    """D3D11* -> HRESULT; else LONG."""
    if dll_name.lower() == "d3d11" and name.startswith("D3D11"):
        return "HRESULT"
    return "LONG"


def gen_proxy_cpp(entries, dll_name):
    dll_lower = dll_name.lower()
    var = dll_lower.replace(".", "_")  # e.g. d3d11
    lines = [
        "/*",
        " * %s proxy. Generated by scripts/gen_d3d11_proxy.py - do not edit by hand." % (dll_name + ".dll",),
        " */",
        "",
        "#ifndef WIN32_LEAN_AND_MEAN",
        "#define WIN32_LEAN_AND_MEAN",
        "#endif",
        "#include <Windows.h>",
        "#include <string>",
        "",
        "static HMODULE g_%s_module = nullptr;" % var,
    ]
    if dll_lower == "d3d11":
        lines += [
            "static HMODULE g_gdi32_module = nullptr;",
            "",
            "static bool LoadRealD3D11() {",
            "    if (g_d3d11_module != nullptr) return true;",
            "    WCHAR system_path[MAX_PATH];",
            "    if (GetSystemDirectoryW(system_path, MAX_PATH) == 0) return false;",
            "    std::wstring path = std::wstring(system_path) + L\"\\\\d3d11.dll\";",
            "    g_d3d11_module = LoadLibraryW(path.c_str());",
            "    return g_d3d11_module != nullptr;",
            "}",
            "",
            "static HMODULE LoadRealGdi32() {",
            "    if (g_gdi32_module != nullptr) return g_gdi32_module;",
            "    WCHAR system_path[MAX_PATH];",
            "    if (GetSystemDirectoryW(system_path, MAX_PATH) == 0) return nullptr;",
            "    std::wstring path = std::wstring(system_path) + L\"\\\\gdi32.dll\";",
            "    g_gdi32_module = LoadLibraryW(path.c_str());",
            "    return g_gdi32_module;",
            "}",
            "",
            "static FARPROC GetD3D11OrGdi32Proc(const char* name) {",
            "    if (LoadRealD3D11()) {",
            "        FARPROC fn = GetProcAddress(g_d3d11_module, name);",
            "        if (fn != nullptr) return fn;",
            "    }",
            "    if (LoadRealGdi32())",
            "        return GetProcAddress(g_gdi32_module, name);",
            "    return nullptr;",
            "}",
            "",
        ]
    else:
        lines += [
            "",
            "static bool LoadReal%s() {" % (dll_name.replace(".", "").title(),),
            "    if (g_%s_module != nullptr) return true;" % var,
            "    WCHAR system_path[MAX_PATH];",
            "    if (GetSystemDirectoryW(system_path, MAX_PATH) == 0) return false;",
            "    std::wstring path = std::wstring(system_path) + L\"\\\\%s.dll\";" % dll_lower,
            "    g_%s_module = LoadLibraryW(path.c_str());" % var,
            "    return g_%s_module != nullptr;" % var,
            "}",
            "",
        ]
    for name, is_stub, params, use_gdi32 in entries:
        ret = return_type(name, dll_name)
        if is_stub:
            if (dll_lower == "d3d11" and (name.startswith("D3DKMT") or name.startswith("OpenAdapter"))) or dll_lower != "d3d11":
                params = ["LPVOID"]
            else:
                params = []
        n = len(params)
        param_names = ["p%u" % i for i in range(n)]
        param_decl = ", ".join("%s %s" % (t, n) for t, n in zip(params, param_names))
        param_list = ", ".join(params) if params else "void"
        if is_stub:
            fail = "return E_FAIL;" if ret == "HRESULT" else "return 0;"
            lines.append("extern \"C\" %s WINAPI %s(%s) {" % (ret, name, param_decl))
            if param_names:
                lines.append("    (void)%s;" % param_names[0])
            lines.append("    %s" % fail)
            lines.append("}")
        else:
            if dll_lower == "d3d11" and use_gdi32:
                call_get = "GetD3D11OrGdi32Proc(\"%s\")" % name
            else:
                call_get = "LoadReal%s() ? GetProcAddress(g_%s_module, \"%s\") : nullptr" % (dll_name.replace(".", "").title(), var, name)
            load_fn = "LoadRealD3D11" if dll_lower == "d3d11" else ("LoadReal%s" % dll_name.replace(".", "").title())
            lines.append("extern \"C\" %s WINAPI %s(%s) {" % (ret, name, param_decl))
            if ret == "HRESULT":
                lines.append("    if (!%s()) return E_FAIL;" % load_fn)
            elif dll_lower == "d3d11" and use_gdi32:
                lines.append("    if (!LoadRealD3D11() && !LoadRealGdi32()) return 0;")
            else:
                lines.append("    if (!%s()) return 0;" % load_fn)
            lines.append("    typedef %s (WINAPI *PFN)(%s);" % (ret, param_list))
            lines.append("    PFN fn = (PFN)(%s);" % call_get)
            lines.append("    if (!fn) return %s;" % ("E_FAIL" if ret == "HRESULT" else "0"))
            lines.append("    return fn(%s);" % ", ".join(param_names))
            lines.append("}")
        lines.append("")
    return "\n".join(lines)


def update_exports_def(def_path, dll_name, export_names):
    """Replace the section '; dll_name.dll exports' in def_path with the given export list."""
    with open(def_path, "r", encoding="utf-8") as f:
        lines = f.readlines()
    marker = "; %s.dll exports" % dll_name.lower().replace(".dll", "")
    start = None
    end = None
    for i, line in enumerate(lines):
        stripped = line.strip()
        if marker in line and stripped.startswith(";"):
            start = i + 1
            continue
        if start is not None and end is None and stripped.startswith(";") and "exports" in stripped:
            # Next section comment (e.g. "; d3d12.dll exports")
            end = i
            break
    if start is None:
        return False
    if end is None:
        end = len(lines)
    new_section = ["\t%s PRIVATE\n" % name for name in export_names]
    new_lines = lines[:start] + new_section + ["\n"] + lines[end:]
    with open(def_path, "w", encoding="utf-8") as f:
        f.writelines(new_lines)
    return True


def main():
    parser = argparse.ArgumentParser(description="Generate proxy .cpp and update exports.def from Wine .spec")
    parser.add_argument("dll", help="DLL name (e.g. d3d11)")
    parser.add_argument("spec", nargs="?", default=None, help="Path to .spec file (default: embedded d3d11.spec when dll is d3d11)")
    parser.add_argument("--no-def", action="store_true", help="Do not update exports.def")
    args = parser.parse_args()
    dll_name = args.dll.replace(".dll", "").strip()
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    if args.spec:
        spec_path = os.path.join(repo_root, args.spec) if not os.path.isabs(args.spec) else args.spec
        if not os.path.isfile(spec_path):
            spec_path = args.spec
        with open(spec_path, "r", encoding="utf-8") as f:
            spec_text = f.read()
    else:
        if dll_name.lower() != "d3d11":
            parser.error("spec file required when dll is not d3d11")
        spec_text = D3D11_SPEC_EMBEDDED
    entries = list(parse_spec(spec_text))
    names = [e[0] for e in entries]
    out_cpp = os.path.join(repo_root, "src", "addons", "display_commander", "proxy_dll", "%s_proxy.cpp" % dll_name.lower())
    cpp = gen_proxy_cpp(entries, dll_name)
    with open(out_cpp, "w", encoding="utf-8") as f:
        f.write(cpp)
    print("Wrote %s (%d exports)" % (out_cpp, len(names)))
    if not args.no_def:
        def_path = os.path.join(repo_root, "src", "addons", "display_commander", "proxy_dll", "exports.def")
        if update_exports_def(def_path, dll_name, names):
            print("Updated %s section in %s" % (dll_name + ".dll", def_path))
        else:
            print("Warning: could not find '; %s.dll exports' section in %s" % (dll_name, def_path))


if __name__ == "__main__":
    main()
