#!/usr/bin/env python3
"""
Extract full ABI (extern "C" function declarations) from Vulkan headers.
Generates a .hpp that includes the official headers and declares every vk*
API with the exact same signature, so the vulkan-1 proxy can include it and
ensure its stubs match the ABI.

Usage:
  python scripts/gen_vulkan_proxy_abi.py [--win32] [--output FILE]
  python scripts/gen_vulkan_proxy_abi.py --win32 -o src/addons/display_commander/proxy_dll/vulkan_proxy_abi.hpp

The generated header:
  - Includes vulkan_core.h (and vulkan_win32.h if --win32) for types and VKAPI_CALL.
  - Declares extern "C" RET VKAPI_CALL vkName(PARAMS); for each API.
  - Excludes callback typedefs (AllocationFunction, FreeFunction, etc.).
  - Only processes single-line typedefs (API entry points are one line in the headers).
"""

import argparse
import os
import re

# Callback typedefs: not API entry points, exclude from ABI declarations.
PFN_CALLBACKS = {
    "vkAllocationFunction",
    "vkFreeFunction",
    "vkReallocationFunction",
    "vkInternalAllocationNotification",
    "vkInternalFreeNotification",
    "vkVoidFunction",
}

# Single-line pattern: typedef RET (VKAPI_PTR *PFN_vkName)(PARAMS);
# Captures: (1) return type, (2) vkName, (3) parameter list.
_TYPEDEF_RE = re.compile(
    r"typedef\s+(.+?)\s+\(VKAPI_PTR\s+\*PFN_(vk[A-Za-z0-9]+)\)\s*\((.*)\)\s*;\s*$"
)


def extract_from_content(content: str, path: str) -> list[tuple[str, str, str]]:
    """Extract (ret, name, params) from PFN_vk* typedefs. Only single-line."""
    out = []
    for line in content.splitlines():
        line = line.rstrip()
        if "PFN_vk" not in line or "typedef" not in line:
            continue
        if not line.endswith(");"):
            # Multiline typedef (e.g. callbacks); skip.
            continue
        m = _TYPEDEF_RE.match(line)
        if not m:
            continue
        ret, name, params = m.group(1).strip(), m.group(2), m.group(3).strip()
        if name in PFN_CALLBACKS:
            continue
        out.append((ret, name, params))
    return out


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate vulkan_proxy_abi.hpp from Vulkan headers."
    )
    parser.add_argument(
        "--win32",
        action="store_true",
        help="Include vulkan_win32.h and emit declarations from it.",
    )
    parser.add_argument(
        "-o",
        "--output",
        default=os.path.join(
            os.path.dirname(__file__),
            "..",
            "src",
            "addons",
            "display_commander",
            "proxy_dll",
            "vulkan_proxy_abi.hpp",
        ),
        help="Output .hpp path.",
    )
    parser.add_argument(
        "--headers-dir",
        default=os.path.join(
            os.path.dirname(__file__),
            "..",
            "external",
            "vulkan-headers",
            "include",
            "vulkan",
        ),
        help="Directory containing vulkan_core.h.",
    )
    args = parser.parse_args()

    headers_dir = os.path.normpath(args.headers_dir)
    core_h = os.path.join(headers_dir, "vulkan_core.h")
    if not os.path.isfile(core_h):
        raise SystemExit(f"Header not found: {core_h}")

    # Collect (ret, name, params) with source so we can prefer win32 over core for duplicates.
    core_decls: list[tuple[str, str, str]] = []
    with open(core_h, "r", encoding="utf-8", errors="replace") as f:
        core_decls = extract_from_content(f.read(), core_h)
    win32_decls: list[tuple[str, str, str]] = []
    if args.win32:
        win32_h = os.path.join(headers_dir, "vulkan_win32.h")
        if os.path.isfile(win32_h):
            with open(win32_h, "r", encoding="utf-8", errors="replace") as f:
                win32_decls = extract_from_content(f.read(), win32_h)

    # Deduplicate by name: prefer win32 over core so HANDLE/PFN from vulkan_win32.h are used.
    by_name: dict[str, tuple[str, str, str]] = {}
    for r, n, p in core_decls:
        by_name[n] = (r, n, p)
    for r, n, p in win32_decls:
        by_name[n] = (r, n, p)
    unique = sorted(by_name.values(), key=lambda x: x[1])

    out_path = os.path.normpath(args.output)
    out_dir = os.path.dirname(out_path)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)

    # Include path: relative to addon or absolute. Use angle brackets so
    # the build can add -I external/vulkan-headers/include.
    include_core = "#include <vulkan/vulkan_core.h>"
    include_win32 = "#include <vulkan/vulkan_win32.h>"

    lines = [
        "// Generated by scripts/gen_vulkan_proxy_abi.py - do not edit.",
        "// Full ABI declarations from Khronos Vulkan headers; include this in the",
        "// vulkan-1 proxy to ensure stub signatures match the official API.",
        "//",
        "#pragma once",
        "",
        include_core,
        "",
    ]
    if args.win32:
        lines.append("#ifdef VK_USE_PLATFORM_WIN32_KHR")
        lines.append("#ifndef WIN32_LEAN_AND_MEAN")
        lines.append("#define WIN32_LEAN_AND_MEAN")
        lines.append("#endif")
        lines.append("#include <Windows.h>  // HANDLE, HINSTANCE, HWND for vulkan_win32.h")
        lines.append(include_win32)
        lines.append("#endif")
        lines.append("")
    lines.append("#ifdef __cplusplus")
    lines.append('extern "C" {')
    lines.append("#endif")
    lines.append("")

    for ret, name, params in unique:
        # Same signature as the typedef: RET VKAPI_CALL vkName(PARAMS);
        lines.append(f"{ret} VKAPI_CALL {name}({params});")
        lines.append("")

    lines.append("#ifdef __cplusplus")
    lines.append("}")
    lines.append("#endif")
    lines.append("")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Wrote {len(unique)} extern declarations to {out_path}")


if __name__ == "__main__":
    main()
