#!/usr/bin/env python3
"""
Generate the full vulkan-1 proxy .cpp from the Vulkan headers (same ABI source as
vulkan_proxy_abi.hpp). Each stub has the correct signature, loads the real
function with GetProcAddress, casts to the official PFN type, and forwards.

Usage:
  python scripts/gen_vulkan_proxy_from_abi.py [--win32] [--output-cpp FILE] [--output-def FILE]
  python scripts/gen_vulkan_proxy_from_abi.py --win32

Outputs:
  - vulkan-1_proxy.cpp: full proxy with LoadRealVulkan1 + one stub per API.
  - Optionally: a .def fragment or updated exports.def vulkan block (--output-def).

The generated .cpp includes vulkan_proxy_abi.hpp (which pulls in vulkan_core.h)
and uses Windows.h for LoadLibraryW/GetProcAddress. Stubs use VKAPI_CALL and
real types so the ABI matches the official loader.
"""

import argparse
import os
import re

# Reuse the same extraction and callback exclusion as gen_vulkan_proxy_abi
from gen_vulkan_proxy_abi import (
    PFN_CALLBACKS,
    extract_from_content,
)

_TYPEDEF_RE = re.compile(
    r"typedef\s+(.+?)\s+\(VKAPI_PTR\s+\*PFN_(vk[A-Za-z0-9]+)\)\s*\((.*)\)\s*;\s*$"
)


def param_names_from_params(params: str) -> list[str]:
    """Extract parameter names from a comma-separated param list (no nested parens)."""
    params = params.strip()
    if not params or params == "void":
        return []
    names = []
    for part in params.split(","):
        part = part.strip()
        if not part:
            continue
        # Last token is the identifier (e.g. "const VkInstanceCreateInfo* pCreateInfo" -> pCreateInfo)
        # Strip array brackets so "blendConstants[4]" -> "blendConstants" (pass array, not single element).
        token = part.split()[-1]
        if "[" in token:
            token = token.split("[", 1)[0]
        names.append(token)
    return names


def failure_return(ret: str) -> str:
    """Return statement when LoadRealVulkan1 or GetProcAddress fails."""
    ret = ret.strip()
    if ret == "void":
        return "return;"
    if "VkResult" in ret:
        return "return VK_ERROR_INITIALIZATION_FAILED;"
    if "*" in ret or "PFN_" in ret or "Function" in ret:
        return "return nullptr;"
    return "return 0;"


def collect_apis(headers_dir: str, win32: bool) -> list[tuple[str, str, str]]:
    """Collect (ret, name, params) from vulkan_core.h and optionally vulkan_win32.h."""
    decls = []
    core_h = os.path.join(headers_dir, "vulkan_core.h")
    if not os.path.isfile(core_h):
        raise SystemExit(f"Header not found: {core_h}")
    with open(core_h, "r", encoding="utf-8", errors="replace") as f:
        decls.extend(extract_from_content(f.read(), core_h))
    if win32:
        win32_h = os.path.join(headers_dir, "vulkan_win32.h")
        if os.path.isfile(win32_h):
            with open(win32_h, "r", encoding="utf-8", errors="replace") as f:
                decls.extend(extract_from_content(f.read(), win32_h))
    seen = set()
    unique = []
    for r, n, p in decls:
        if n not in seen:
            seen.add(n)
            unique.append((r, n, p))
    unique.sort(key=lambda x: x[1])
    return unique


def generate_proxy_cpp(apis: list[tuple[str, str, str]], out_path: str, win32: bool) -> None:
    """Write vulkan-1_proxy.cpp with includes, loader, and one stub per API."""
    lines = [
        "// Generated by scripts/gen_vulkan_proxy_from_abi.py - do not edit.",
        "// Full vulkan-1 proxy: each stub forwards to the real vulkan-1.dll with correct ABI.",
        "//",
        "// Source Code <Display Commander>",
        "",
    ]
    if win32:
        lines.append("#define VK_USE_PLATFORM_WIN32_KHR 1")
        lines.append("")
    lines.extend([
        "#include \"vulkan_proxy_abi.hpp\"",
        "",
        "// Libraries <standard C++>",
        "#include <string>",
        "",
        "// Libraries <Windows.h>",
        "#ifndef WIN32_LEAN_AND_MEAN",
        "#define WIN32_LEAN_AND_MEAN",
        "#endif",
        "#include <Windows.h>",
        "",
        "static HMODULE g_vulkan_1_module = nullptr;",
        "",
        "static bool LoadRealVulkan1() {",
        "    if (g_vulkan_1_module != nullptr) return true;",
        "    WCHAR system_path[MAX_PATH];",
        "    if (GetSystemDirectoryW(system_path, MAX_PATH) == 0) return false;",
        "    std::wstring path = std::wstring(system_path) + L\"\\\\vulkan-1.dll\";",
        "    g_vulkan_1_module = LoadLibraryW(path.c_str());",
        "    return g_vulkan_1_module != nullptr;",
        "}",
        "",
        "extern \"C\" {",
        "",
    ])
    for ret, name, params in apis:
        names = param_names_from_params(params)
        args = ", ".join(names)
        fail = failure_return(ret)
        pfn_type = f"PFN_{name}"
        # One declaration + body
        sig = f"{ret} VKAPI_CALL {name}({params})"
        lines.append(f"{sig} {{")
        lines.append("    if (!LoadRealVulkan1()) " + fail)
        lines.append(f"    {pfn_type} fn = ({pfn_type})GetProcAddress(g_vulkan_1_module, \"" + name + "\");")
        lines.append("    if (!fn) " + fail)
        if ret.strip() == "void":
            if args:
                lines.append(f"    fn({args});")
            else:
                lines.append("    fn();")
            lines.append("    return;")
        else:
            if args:
                lines.append(f"    return fn({args});")
            else:
                lines.append("    return fn();")
        lines.append("}")
        lines.append("")
    lines.append("} // extern \"C\"")
    lines.append("")
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Wrote {len(apis)} stubs to {out_path}")


def generate_exports_def_fragment(apis: list[tuple[str, str, str]], out_path: str) -> None:
    """Write a fragment: one line per export for the vulkan block (e.g. for pasting into exports.def)."""
    lines = [
        "\t; vulkan-1.dll exports (from scripts/gen_vulkan_proxy_from_abi.py + Vulkan headers)",
        "",
    ]
    for _r, name, _p in apis:
        lines.append(f"\t{name} PRIVATE")
    lines.append("")
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Wrote {len(apis)} export lines to {out_path}")


def update_exports_def(apis: list[tuple[str, str, str]], def_path: str) -> None:
    """Replace the vulkan-1.dll export block in exports.def with the full API list."""
    with open(def_path, "r", encoding="utf-8") as f:
        content = f.read()
    # Start: first line that is "; vulkan-1.dll" (with leading tab)
    # End: last "vk* PRIVATE" line before "; ReShade loader"
    start_marker = "\t; vulkan-1.dll exports"
    end_marker = "\t; ReShade loader API"
    i = content.find(start_marker)
    j = content.find(end_marker)
    if i == -1 or j == -1 or j <= i:
        raise SystemExit(f"Could not find vulkan block in {def_path} (start_marker/end_marker)")
    # Build new block (same format as existing: comment + one line per export)
    block_lines = [
        "\t; vulkan-1.dll exports (from scripts/gen_vulkan_proxy_from_abi.py + Vulkan headers)",
        "",
    ]
    for _r, name, _p in apis:
        block_lines.append(f"\t{name} PRIVATE")
    block_lines.append("")
    new_block = "\n".join(block_lines)
    new_content = content[:i] + new_block + content[j:]
    with open(def_path, "w", encoding="utf-8") as f:
        f.write(new_content)
    print(f"Updated vulkan block in {def_path} ({len(apis)} exports)")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate full vulkan-1 proxy .cpp from Vulkan headers (ABI)."
    )
    parser.add_argument("--win32", action="store_true", help="Include vulkan_win32.h APIs.")
    parser.add_argument(
        "--output-cpp",
        default=os.path.join(
            os.path.dirname(__file__),
            "..",
            "src",
            "addons",
            "display_commander",
            "proxy_dll",
            "vulkan-1_proxy.cpp",
        ),
        help="Output proxy .cpp path.",
    )
    parser.add_argument(
        "--output-def",
        default=None,
        help="If set, write exports fragment (vulkan block) to this file.",
    )
    parser.add_argument(
        "--update-exports-def",
        default=None,
        metavar="PATH",
        help="If set, replace the vulkan block in this exports.def file in place.",
    )
    parser.add_argument(
        "--headers-dir",
        default=os.path.join(
            os.path.dirname(__file__),
            "..",
            "external",
            "vulkan-headers",
            "include",
            "vulkan",
        ),
        help="Directory containing vulkan_core.h.",
    )
    args = parser.parse_args()

    headers_dir = os.path.normpath(args.headers_dir)
    apis = collect_apis(headers_dir, args.win32)

    out_cpp = os.path.normpath(args.output_cpp)
    generate_proxy_cpp(apis, out_cpp, args.win32)

    if args.output_def:
        generate_exports_def_fragment(apis, os.path.normpath(args.output_def))
    if args.update_exports_def:
        update_exports_def(apis, os.path.normpath(args.update_exports_def))


if __name__ == "__main__":
    main()
