/*
 * bcrypt.dll proxy. Generated by scripts/gen_proxy_from_spec.py from Wine bcrypt.spec.
 * Regenerate: python scripts/gen_proxy_from_spec.py bcrypt scripts/specs/bcrypt.spec
 */

// Source Code <Display Commander> // follow this order for includes in all files + add this comment at the top
#include "../utils/detour_call_tracker.hpp"
#include "../utils/timing.hpp"

// Libraries <standard C++>
#include <string>

// Libraries <Windows.h> — before other Windows headers
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <Windows.h>

static HMODULE g_bcrypt_module = nullptr;

static bool LoadRealBcrypt() {
    if (g_bcrypt_module != nullptr) return true;
    WCHAR system_path[MAX_PATH];
    if (GetSystemDirectoryW(system_path, MAX_PATH) == 0) return false;
    std::wstring path = std::wstring(system_path) + L"\\bcrypt.dll";
    g_bcrypt_module = LoadLibraryW(path.c_str());
    return g_bcrypt_module != nullptr;
}

extern "C" LONG WINAPI BCryptAddContextFunction(LONG p0, LPCWSTR p1, LONG p2, LPCWSTR p3, LONG p4) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealBcrypt()) return 0;
    typedef LONG (WINAPI *PFN)(LONG, LPCWSTR, LONG, LPCWSTR, LONG);
    PFN fn = (PFN)(LoadRealBcrypt() ? GetProcAddress(g_bcrypt_module, "BCryptAddContextFunction") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4);
}

extern "C" LONG WINAPI BCryptAddContextFunctionProvider(LONG p0, LPCWSTR p1, LONG p2, LPCWSTR p3, LPCWSTR p4, LONG p5) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealBcrypt()) return 0;
    typedef LONG (WINAPI *PFN)(LONG, LPCWSTR, LONG, LPCWSTR, LPCWSTR, LONG);
    PFN fn = (PFN)(LoadRealBcrypt() ? GetProcAddress(g_bcrypt_module, "BCryptAddContextFunctionProvider") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5);
}

extern "C" LONG WINAPI BCryptCloseAlgorithmProvider(LPVOID p0, LONG p1) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealBcrypt()) return 0;
    typedef LONG (WINAPI *PFN)(LPVOID, LONG);
    PFN fn = (PFN)(LoadRealBcrypt() ? GetProcAddress(g_bcrypt_module, "BCryptCloseAlgorithmProvider") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" LONG WINAPI BCryptConfigureContext(void) {
    CALL_GUARD(utils::get_now_ns());
    return 0;
}

extern "C" LONG WINAPI BCryptConfigureContextFunction(void) {
    CALL_GUARD(utils::get_now_ns());
    return 0;
}

extern "C" LONG WINAPI BCryptCreateContext(void) {
    CALL_GUARD(utils::get_now_ns());
    return 0;
}

extern "C" LONG WINAPI BCryptCreateHash(LPVOID p0, LPVOID p1, LPVOID p2, LONG p3, LPVOID p4, LONG p5, LONG p6) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealBcrypt()) return 0;
    typedef LONG (WINAPI *PFN)(LPVOID, LPVOID, LPVOID, LONG, LPVOID, LONG, LONG);
    PFN fn = (PFN)(LoadRealBcrypt() ? GetProcAddress(g_bcrypt_module, "BCryptCreateHash") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5, p6);
}

extern "C" LONG WINAPI BCryptDecrypt(LPVOID p0, LPVOID p1, LONG p2, LPVOID p3, LPVOID p4, LONG p5, LPVOID p6, LONG p7, LPVOID p8, LONG p9) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealBcrypt()) return 0;
    typedef LONG (WINAPI *PFN)(LPVOID, LPVOID, LONG, LPVOID, LPVOID, LONG, LPVOID, LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealBcrypt() ? GetProcAddress(g_bcrypt_module, "BCryptDecrypt") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9);
}

extern "C" LONG WINAPI BCryptDeleteContext(void) {
    CALL_GUARD(utils::get_now_ns());
    return 0;
}

extern "C" LONG WINAPI BCryptDeriveKey(LPVOID p0, LPCWSTR p1, LPVOID p2, LPVOID p3, LONG p4, LPVOID p5, LONG p6) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealBcrypt()) return 0;
    typedef LONG (WINAPI *PFN)(LPVOID, LPCWSTR, LPVOID, LPVOID, LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealBcrypt() ? GetProcAddress(g_bcrypt_module, "BCryptDeriveKey") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5, p6);
}

extern "C" LONG WINAPI BCryptDeriveKeyCapi(LPVOID p0, LPVOID p1, LPVOID p2, LONG p3, LONG p4) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealBcrypt()) return 0;
    typedef LONG (WINAPI *PFN)(LPVOID, LPVOID, LPVOID, LONG, LONG);
    PFN fn = (PFN)(LoadRealBcrypt() ? GetProcAddress(g_bcrypt_module, "BCryptDeriveKeyCapi") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4);
}

extern "C" LONG WINAPI BCryptDeriveKeyPBKDF2(LPVOID p0, LPVOID p1, LONG p2, LPVOID p3, LONG p4, DWORD64 p5, LPVOID p6, LONG p7, LONG p8) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealBcrypt()) return 0;
    typedef LONG (WINAPI *PFN)(LPVOID, LPVOID, LONG, LPVOID, LONG, DWORD64, LPVOID, LONG, LONG);
    PFN fn = (PFN)(LoadRealBcrypt() ? GetProcAddress(g_bcrypt_module, "BCryptDeriveKeyPBKDF2") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5, p6, p7, p8);
}

extern "C" LONG WINAPI BCryptDestroyHash(LPVOID p0) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealBcrypt()) return 0;
    typedef LONG (WINAPI *PFN)(LPVOID);
    PFN fn = (PFN)(LoadRealBcrypt() ? GetProcAddress(g_bcrypt_module, "BCryptDestroyHash") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" LONG WINAPI BCryptDestroyKey(LPVOID p0) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealBcrypt()) return 0;
    typedef LONG (WINAPI *PFN)(LPVOID);
    PFN fn = (PFN)(LoadRealBcrypt() ? GetProcAddress(g_bcrypt_module, "BCryptDestroyKey") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" LONG WINAPI BCryptDestroySecret(LPVOID p0) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealBcrypt()) return 0;
    typedef LONG (WINAPI *PFN)(LPVOID);
    PFN fn = (PFN)(LoadRealBcrypt() ? GetProcAddress(g_bcrypt_module, "BCryptDestroySecret") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" LONG WINAPI BCryptDuplicateHash(LPVOID p0, LPVOID p1, LPVOID p2, LONG p3, LONG p4) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealBcrypt()) return 0;
    typedef LONG (WINAPI *PFN)(LPVOID, LPVOID, LPVOID, LONG, LONG);
    PFN fn = (PFN)(LoadRealBcrypt() ? GetProcAddress(g_bcrypt_module, "BCryptDuplicateHash") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4);
}

extern "C" LONG WINAPI BCryptDuplicateKey(LPVOID p0, LPVOID p1, LPVOID p2, LONG p3, LONG p4) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealBcrypt()) return 0;
    typedef LONG (WINAPI *PFN)(LPVOID, LPVOID, LPVOID, LONG, LONG);
    PFN fn = (PFN)(LoadRealBcrypt() ? GetProcAddress(g_bcrypt_module, "BCryptDuplicateKey") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4);
}

extern "C" LONG WINAPI BCryptEncrypt(LPVOID p0, LPVOID p1, LONG p2, LPVOID p3, LPVOID p4, LONG p5, LPVOID p6, LONG p7, LPVOID p8, LONG p9) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealBcrypt()) return 0;
    typedef LONG (WINAPI *PFN)(LPVOID, LPVOID, LONG, LPVOID, LPVOID, LONG, LPVOID, LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealBcrypt() ? GetProcAddress(g_bcrypt_module, "BCryptEncrypt") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9);
}

extern "C" LONG WINAPI BCryptEnumAlgorithms(LONG p0, LPVOID p1, LPVOID p2, LONG p3) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealBcrypt()) return 0;
    typedef LONG (WINAPI *PFN)(LONG, LPVOID, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealBcrypt() ? GetProcAddress(g_bcrypt_module, "BCryptEnumAlgorithms") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" LONG WINAPI BCryptEnumContextFunctionProviders(void) {
    CALL_GUARD(utils::get_now_ns());
    return 0;
}

extern "C" LONG WINAPI BCryptEnumContextFunctions(LONG p0, LPCWSTR p1, LONG p2, LPVOID p3, LPVOID p4) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealBcrypt()) return 0;
    typedef LONG (WINAPI *PFN)(LONG, LPCWSTR, LONG, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealBcrypt() ? GetProcAddress(g_bcrypt_module, "BCryptEnumContextFunctions") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4);
}

extern "C" LONG WINAPI BCryptEnumContexts(void) {
    CALL_GUARD(utils::get_now_ns());
    return 0;
}

extern "C" LONG WINAPI BCryptEnumProviders(void) {
    CALL_GUARD(utils::get_now_ns());
    return 0;
}

extern "C" LONG WINAPI BCryptEnumRegisteredProviders(void) {
    CALL_GUARD(utils::get_now_ns());
    return 0;
}

extern "C" LONG WINAPI BCryptExportKey(LPVOID p0, LPVOID p1, LPCWSTR p2, LPVOID p3, LONG p4, LPVOID p5, LONG p6) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealBcrypt()) return 0;
    typedef LONG (WINAPI *PFN)(LPVOID, LPVOID, LPCWSTR, LPVOID, LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealBcrypt() ? GetProcAddress(g_bcrypt_module, "BCryptExportKey") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5, p6);
}

extern "C" LONG WINAPI BCryptFinalizeKeyPair(LPVOID p0, LONG p1) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealBcrypt()) return 0;
    typedef LONG (WINAPI *PFN)(LPVOID, LONG);
    PFN fn = (PFN)(LoadRealBcrypt() ? GetProcAddress(g_bcrypt_module, "BCryptFinalizeKeyPair") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" LONG WINAPI BCryptFinishHash(LPVOID p0, LPVOID p1, LONG p2, LONG p3) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealBcrypt()) return 0;
    typedef LONG (WINAPI *PFN)(LPVOID, LPVOID, LONG, LONG);
    PFN fn = (PFN)(LoadRealBcrypt() ? GetProcAddress(g_bcrypt_module, "BCryptFinishHash") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" void WINAPI BCryptFreeBuffer(LPVOID p0) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealBcrypt()) return;
    typedef void (WINAPI *PFN)(LPVOID);
    PFN fn = (PFN)(LoadRealBcrypt() ? GetProcAddress(g_bcrypt_module, "BCryptFreeBuffer") : nullptr);
    if (!fn) return;
    fn(p0);
}

extern "C" LONG WINAPI BCryptGenRandom(LPVOID p0, LPVOID p1, LONG p2, LONG p3) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealBcrypt()) return 0;
    typedef LONG (WINAPI *PFN)(LPVOID, LPVOID, LONG, LONG);
    PFN fn = (PFN)(LoadRealBcrypt() ? GetProcAddress(g_bcrypt_module, "BCryptGenRandom") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" LONG WINAPI BCryptGenerateKeyPair(LPVOID p0, LPVOID p1, LONG p2, LONG p3) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealBcrypt()) return 0;
    typedef LONG (WINAPI *PFN)(LPVOID, LPVOID, LONG, LONG);
    PFN fn = (PFN)(LoadRealBcrypt() ? GetProcAddress(g_bcrypt_module, "BCryptGenerateKeyPair") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" LONG WINAPI BCryptGenerateSymmetricKey(LPVOID p0, LPVOID p1, LPVOID p2, LONG p3, LPVOID p4, LONG p5, LONG p6) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealBcrypt()) return 0;
    typedef LONG (WINAPI *PFN)(LPVOID, LPVOID, LPVOID, LONG, LPVOID, LONG, LONG);
    PFN fn = (PFN)(LoadRealBcrypt() ? GetProcAddress(g_bcrypt_module, "BCryptGenerateSymmetricKey") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5, p6);
}

extern "C" LONG WINAPI BCryptGetFipsAlgorithmMode(LPVOID p0) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealBcrypt()) return 0;
    typedef LONG (WINAPI *PFN)(LPVOID);
    PFN fn = (PFN)(LoadRealBcrypt() ? GetProcAddress(g_bcrypt_module, "BCryptGetFipsAlgorithmMode") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" LONG WINAPI BCryptGetProperty(LPVOID p0, LPCWSTR p1, LPVOID p2, LONG p3, LPVOID p4, LONG p5) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealBcrypt()) return 0;
    typedef LONG (WINAPI *PFN)(LPVOID, LPCWSTR, LPVOID, LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealBcrypt() ? GetProcAddress(g_bcrypt_module, "BCryptGetProperty") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5);
}

extern "C" LONG WINAPI BCryptHash(LPVOID p0, LPVOID p1, LONG p2, LPVOID p3, LONG p4, LPVOID p5, LONG p6) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealBcrypt()) return 0;
    typedef LONG (WINAPI *PFN)(LPVOID, LPVOID, LONG, LPVOID, LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealBcrypt() ? GetProcAddress(g_bcrypt_module, "BCryptHash") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5, p6);
}

extern "C" LONG WINAPI BCryptHashData(LPVOID p0, LPVOID p1, LONG p2, LONG p3) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealBcrypt()) return 0;
    typedef LONG (WINAPI *PFN)(LPVOID, LPVOID, LONG, LONG);
    PFN fn = (PFN)(LoadRealBcrypt() ? GetProcAddress(g_bcrypt_module, "BCryptHashData") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" LONG WINAPI BCryptImportKey(LPVOID p0, LPVOID p1, LPCWSTR p2, LPVOID p3, LPVOID p4, LONG p5, LPVOID p6, LONG p7, LONG p8) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealBcrypt()) return 0;
    typedef LONG (WINAPI *PFN)(LPVOID, LPVOID, LPCWSTR, LPVOID, LPVOID, LONG, LPVOID, LONG, LONG);
    PFN fn = (PFN)(LoadRealBcrypt() ? GetProcAddress(g_bcrypt_module, "BCryptImportKey") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5, p6, p7, p8);
}

extern "C" LONG WINAPI BCryptImportKeyPair(LPVOID p0, LPVOID p1, LPCWSTR p2, LPVOID p3, LPVOID p4, LONG p5, LONG p6) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealBcrypt()) return 0;
    typedef LONG (WINAPI *PFN)(LPVOID, LPVOID, LPCWSTR, LPVOID, LPVOID, LONG, LONG);
    PFN fn = (PFN)(LoadRealBcrypt() ? GetProcAddress(g_bcrypt_module, "BCryptImportKeyPair") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5, p6);
}

extern "C" LONG WINAPI BCryptKeyDerivation(LPVOID p0, LPVOID p1, LPVOID p2, LONG p3, LPVOID p4, LONG p5) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealBcrypt()) return 0;
    typedef LONG (WINAPI *PFN)(LPVOID, LPVOID, LPVOID, LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealBcrypt() ? GetProcAddress(g_bcrypt_module, "BCryptKeyDerivation") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5);
}

extern "C" LONG WINAPI BCryptOpenAlgorithmProvider(LPVOID p0, LPCWSTR p1, LPCWSTR p2, LONG p3) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealBcrypt()) return 0;
    typedef LONG (WINAPI *PFN)(LPVOID, LPCWSTR, LPCWSTR, LONG);
    PFN fn = (PFN)(LoadRealBcrypt() ? GetProcAddress(g_bcrypt_module, "BCryptOpenAlgorithmProvider") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" LONG WINAPI BCryptQueryContextConfiguration(void) {
    CALL_GUARD(utils::get_now_ns());
    return 0;
}

extern "C" LONG WINAPI BCryptQueryContextFunctionConfiguration(void) {
    CALL_GUARD(utils::get_now_ns());
    return 0;
}

extern "C" LONG WINAPI BCryptQueryContextFunctionProperty(void) {
    CALL_GUARD(utils::get_now_ns());
    return 0;
}

extern "C" LONG WINAPI BCryptQueryProviderRegistration(void) {
    CALL_GUARD(utils::get_now_ns());
    return 0;
}

extern "C" LONG WINAPI BCryptRegisterConfigChangeNotify(void) {
    CALL_GUARD(utils::get_now_ns());
    return 0;
}

extern "C" LONG WINAPI BCryptRegisterProvider(LPCWSTR p0, LONG p1, LPVOID p2) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealBcrypt()) return 0;
    typedef LONG (WINAPI *PFN)(LPCWSTR, LONG, LPVOID);
    PFN fn = (PFN)(LoadRealBcrypt() ? GetProcAddress(g_bcrypt_module, "BCryptRegisterProvider") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" LONG WINAPI BCryptRemoveContextFunction(LONG p0, LPCWSTR p1, LONG p2, LPCWSTR p3) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealBcrypt()) return 0;
    typedef LONG (WINAPI *PFN)(LONG, LPCWSTR, LONG, LPCWSTR);
    PFN fn = (PFN)(LoadRealBcrypt() ? GetProcAddress(g_bcrypt_module, "BCryptRemoveContextFunction") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" LONG WINAPI BCryptRemoveContextFunctionProvider(LONG p0, LPCWSTR p1, LONG p2, LPCWSTR p3, LPCWSTR p4) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealBcrypt()) return 0;
    typedef LONG (WINAPI *PFN)(LONG, LPCWSTR, LONG, LPCWSTR, LPCWSTR);
    PFN fn = (PFN)(LoadRealBcrypt() ? GetProcAddress(g_bcrypt_module, "BCryptRemoveContextFunctionProvider") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4);
}

extern "C" LONG WINAPI BCryptResolveProviders(void) {
    CALL_GUARD(utils::get_now_ns());
    return 0;
}

extern "C" LONG WINAPI BCryptSecretAgreement(LPVOID p0, LPVOID p1, LPVOID p2, LONG p3) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealBcrypt()) return 0;
    typedef LONG (WINAPI *PFN)(LPVOID, LPVOID, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealBcrypt() ? GetProcAddress(g_bcrypt_module, "BCryptSecretAgreement") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" LONG WINAPI BCryptSetAuditingInterface(void) {
    CALL_GUARD(utils::get_now_ns());
    return 0;
}

extern "C" LONG WINAPI BCryptSetContextFunctionProperty(void) {
    CALL_GUARD(utils::get_now_ns());
    return 0;
}

extern "C" LONG WINAPI BCryptSetProperty(LPVOID p0, LPCWSTR p1, LPVOID p2, LONG p3, LONG p4) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealBcrypt()) return 0;
    typedef LONG (WINAPI *PFN)(LPVOID, LPCWSTR, LPVOID, LONG, LONG);
    PFN fn = (PFN)(LoadRealBcrypt() ? GetProcAddress(g_bcrypt_module, "BCryptSetProperty") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4);
}

extern "C" LONG WINAPI BCryptSignHash(LPVOID p0, LPVOID p1, LPVOID p2, LONG p3, LPVOID p4, LONG p5, LPVOID p6, LONG p7) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealBcrypt()) return 0;
    typedef LONG (WINAPI *PFN)(LPVOID, LPVOID, LPVOID, LONG, LPVOID, LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealBcrypt() ? GetProcAddress(g_bcrypt_module, "BCryptSignHash") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5, p6, p7);
}

extern "C" LONG WINAPI BCryptUnregisterConfigChangeNotify(void) {
    CALL_GUARD(utils::get_now_ns());
    return 0;
}

extern "C" LONG WINAPI BCryptUnregisterProvider(LPCWSTR p0) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealBcrypt()) return 0;
    typedef LONG (WINAPI *PFN)(LPCWSTR);
    PFN fn = (PFN)(LoadRealBcrypt() ? GetProcAddress(g_bcrypt_module, "BCryptUnregisterProvider") : nullptr);
    if (!fn) return 0;
    return fn(p0);
}

extern "C" LONG WINAPI BCryptVerifySignature(LPVOID p0, LPVOID p1, LPVOID p2, LONG p3, LPVOID p4, LONG p5, LONG p6) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealBcrypt()) return 0;
    typedef LONG (WINAPI *PFN)(LPVOID, LPVOID, LPVOID, LONG, LPVOID, LONG, LONG);
    PFN fn = (PFN)(LoadRealBcrypt() ? GetProcAddress(g_bcrypt_module, "BCryptVerifySignature") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5, p6);
}

extern "C" LONG WINAPI GetAsymmetricEncryptionInterface(void) {
    CALL_GUARD(utils::get_now_ns());
    return 0;
}

extern "C" LONG WINAPI GetCipherInterface(void) {
    CALL_GUARD(utils::get_now_ns());
    return 0;
}

extern "C" LONG WINAPI GetHashInterface(void) {
    CALL_GUARD(utils::get_now_ns());
    return 0;
}

extern "C" LONG WINAPI GetRngInterface(void) {
    CALL_GUARD(utils::get_now_ns());
    return 0;
}

extern "C" LONG WINAPI GetSecretAgreementInterface(void) {
    CALL_GUARD(utils::get_now_ns());
    return 0;
}

extern "C" LONG WINAPI GetSignatureInterface(void) {
    CALL_GUARD(utils::get_now_ns());
    return 0;
}
