/*
 * d3d11.dll proxy. Generated by scripts/gen_d3d11_proxy.py - do not edit by hand.
 */

#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <Windows.h>
#include <string>

static HMODULE g_d3d11_module = nullptr;
static HMODULE g_gdi32_module = nullptr;

static bool LoadRealD3D11() {
    if (g_d3d11_module != nullptr) return true;
    WCHAR system_path[MAX_PATH];
    if (GetSystemDirectoryW(system_path, MAX_PATH) == 0) return false;
    std::wstring path = std::wstring(system_path) + L"\\d3d11.dll";
    g_d3d11_module = LoadLibraryW(path.c_str());
    return g_d3d11_module != nullptr;
}

static HMODULE LoadRealGdi32() {
    if (g_gdi32_module != nullptr) return g_gdi32_module;
    WCHAR system_path[MAX_PATH];
    if (GetSystemDirectoryW(system_path, MAX_PATH) == 0) return nullptr;
    std::wstring path = std::wstring(system_path) + L"\\gdi32.dll";
    g_gdi32_module = LoadLibraryW(path.c_str());
    return g_gdi32_module;
}

static FARPROC GetD3D11OrGdi32Proc(const char* name) {
    if (LoadRealD3D11()) {
        FARPROC fn = GetProcAddress(g_d3d11_module, name);
        if (fn != nullptr) return fn;
    }
    if (LoadRealGdi32())
        return GetProcAddress(g_gdi32_module, name);
    return nullptr;
}

extern "C" HRESULT WINAPI D3D11CoreCreateDevice(LPVOID p0, LPVOID p1, LONG p2, LPVOID p3, LONG p4, LPVOID p5) {
    if (!LoadRealD3D11()) return E_FAIL;
    typedef HRESULT (WINAPI *PFN)(LPVOID, LPVOID, LONG, LPVOID, LONG, LPVOID);
    PFN fn = (PFN)(LoadRealD3D11() ? GetProcAddress(g_d3d11_module, "D3D11CoreCreateDevice") : nullptr);
    if (!fn) return E_FAIL;
    return fn(p0, p1, p2, p3, p4, p5);
}

extern "C" HRESULT WINAPI D3D11CoreCreateLayeredDevice() {
    return E_FAIL;
}

extern "C" HRESULT WINAPI D3D11CoreGetLayeredDeviceSize() {
    return E_FAIL;
}

extern "C" HRESULT WINAPI D3D11CoreRegisterLayers() {
    if (!LoadRealD3D11()) return E_FAIL;
    typedef HRESULT (WINAPI *PFN)(void);
    PFN fn = (PFN)(LoadRealD3D11() ? GetProcAddress(g_d3d11_module, "D3D11CoreRegisterLayers") : nullptr);
    if (!fn) return E_FAIL;
    return fn();
}

extern "C" HRESULT WINAPI D3D11CreateDevice(LPVOID p0, LONG p1, LPVOID p2, LONG p3, LPVOID p4, LONG p5, LONG p6, LPVOID p7, LPVOID p8, LPVOID p9) {
    if (!LoadRealD3D11()) return E_FAIL;
    typedef HRESULT (WINAPI *PFN)(LPVOID, LONG, LPVOID, LONG, LPVOID, LONG, LONG, LPVOID, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealD3D11() ? GetProcAddress(g_d3d11_module, "D3D11CreateDevice") : nullptr);
    if (!fn) return E_FAIL;
    return fn(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9);
}

extern "C" HRESULT WINAPI D3D11CreateDeviceAndSwapChain(LPVOID p0, LONG p1, LPVOID p2, LONG p3, LPVOID p4, LONG p5, LONG p6, LPVOID p7, LPVOID p8, LPVOID p9, LPVOID p10, LPVOID p11) {
    if (!LoadRealD3D11()) return E_FAIL;
    typedef HRESULT (WINAPI *PFN)(LPVOID, LONG, LPVOID, LONG, LPVOID, LONG, LONG, LPVOID, LPVOID, LPVOID, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealD3D11() ? GetProcAddress(g_d3d11_module, "D3D11CreateDeviceAndSwapChain") : nullptr);
    if (!fn) return E_FAIL;
    return fn(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11);
}

extern "C" HRESULT WINAPI D3D11On12CreateDevice(LPVOID p0, LONG p1, LPVOID p2, LONG p3, LPVOID p4, LONG p5, LONG p6, LPVOID p7, LPVOID p8, LPVOID p9) {
    if (!LoadRealD3D11()) return E_FAIL;
    typedef HRESULT (WINAPI *PFN)(LPVOID, LONG, LPVOID, LONG, LPVOID, LONG, LONG, LPVOID, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealD3D11() ? GetProcAddress(g_d3d11_module, "D3D11On12CreateDevice") : nullptr);
    if (!fn) return E_FAIL;
    return fn(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9);
}

extern "C" LONG WINAPI D3DKMTCheckVidPnExclusiveOwnership(LPVOID p0) {
    if (!LoadRealD3D11() && !LoadRealGdi32()) return 0;
    typedef LONG (WINAPI *PFN)(LPVOID);
    PFN fn = (PFN)(GetD3D11OrGdi32Proc("D3DKMTCheckVidPnExclusiveOwnership"));
    if (!fn) return 0;
    return fn(p0);
}

extern "C" LONG WINAPI D3DKMTCloseAdapter(LPVOID p0) {
    if (!LoadRealD3D11() && !LoadRealGdi32()) return 0;
    typedef LONG (WINAPI *PFN)(LPVOID);
    PFN fn = (PFN)(GetD3D11OrGdi32Proc("D3DKMTCloseAdapter"));
    if (!fn) return 0;
    return fn(p0);
}

extern "C" LONG WINAPI D3DKMTCreateAllocation(LPVOID p0) {
    (void)p0;
    return 0;
}

extern "C" LONG WINAPI D3DKMTCreateContext(LPVOID p0) {
    (void)p0;
    return 0;
}

extern "C" LONG WINAPI D3DKMTCreateDevice(LPVOID p0) {
    if (!LoadRealD3D11() && !LoadRealGdi32()) return 0;
    typedef LONG (WINAPI *PFN)(LPVOID);
    PFN fn = (PFN)(GetD3D11OrGdi32Proc("D3DKMTCreateDevice"));
    if (!fn) return 0;
    return fn(p0);
}

extern "C" LONG WINAPI D3DKMTCreateSynchronizationObject(LPVOID p0) {
    (void)p0;
    return 0;
}

extern "C" LONG WINAPI D3DKMTDestroyAllocation(LPVOID p0) {
    (void)p0;
    return 0;
}

extern "C" LONG WINAPI D3DKMTDestroyContext(LPVOID p0) {
    (void)p0;
    return 0;
}

extern "C" LONG WINAPI D3DKMTDestroyDevice(LPVOID p0) {
    if (!LoadRealD3D11() && !LoadRealGdi32()) return 0;
    typedef LONG (WINAPI *PFN)(LPVOID);
    PFN fn = (PFN)(GetD3D11OrGdi32Proc("D3DKMTDestroyDevice"));
    if (!fn) return 0;
    return fn(p0);
}

extern "C" LONG WINAPI D3DKMTDestroySynchronizationObject(LPVOID p0) {
    (void)p0;
    return 0;
}

extern "C" LONG WINAPI D3DKMTEscape(LPVOID p0) {
    (void)p0;
    return 0;
}

extern "C" LONG WINAPI D3DKMTGetContextSchedulingPriority(LPVOID p0) {
    (void)p0;
    return 0;
}

extern "C" LONG WINAPI D3DKMTGetDeviceState(LPVOID p0) {
    (void)p0;
    return 0;
}

extern "C" LONG WINAPI D3DKMTGetDisplayModeList(LPVOID p0) {
    (void)p0;
    return 0;
}

extern "C" LONG WINAPI D3DKMTGetMultisampleMethodList(LPVOID p0) {
    (void)p0;
    return 0;
}

extern "C" LONG WINAPI D3DKMTGetRuntimeData(LPVOID p0) {
    (void)p0;
    return 0;
}

extern "C" LONG WINAPI D3DKMTGetSharedPrimaryHandle(LPVOID p0) {
    (void)p0;
    return 0;
}

extern "C" LONG WINAPI D3DKMTLock(LPVOID p0) {
    (void)p0;
    return 0;
}

extern "C" LONG WINAPI D3DKMTOpenAdapterFromGdiDisplayName(LPVOID p0) {
    if (!LoadRealD3D11() && !LoadRealGdi32()) return 0;
    typedef LONG (WINAPI *PFN)(LPVOID);
    PFN fn = (PFN)(GetD3D11OrGdi32Proc("D3DKMTOpenAdapterFromGdiDisplayName"));
    if (!fn) return 0;
    return fn(p0);
}

extern "C" LONG WINAPI D3DKMTOpenAdapterFromHdc(LPVOID p0) {
    (void)p0;
    return 0;
}

extern "C" LONG WINAPI D3DKMTOpenResource(LPVOID p0) {
    (void)p0;
    return 0;
}

extern "C" LONG WINAPI D3DKMTPresent(LPVOID p0) {
    (void)p0;
    return 0;
}

extern "C" LONG WINAPI D3DKMTQueryAdapterInfo(LPVOID p0) {
    if (!LoadRealD3D11() && !LoadRealGdi32()) return 0;
    typedef LONG (WINAPI *PFN)(LPVOID);
    PFN fn = (PFN)(GetD3D11OrGdi32Proc("D3DKMTQueryAdapterInfo"));
    if (!fn) return 0;
    return fn(p0);
}

extern "C" LONG WINAPI D3DKMTQueryAllocationResidency(LPVOID p0) {
    (void)p0;
    return 0;
}

extern "C" LONG WINAPI D3DKMTQueryResourceInfo(LPVOID p0) {
    (void)p0;
    return 0;
}

extern "C" LONG WINAPI D3DKMTRender(LPVOID p0) {
    (void)p0;
    return 0;
}

extern "C" LONG WINAPI D3DKMTSetAllocationPriority(LPVOID p0) {
    (void)p0;
    return 0;
}

extern "C" LONG WINAPI D3DKMTSetContextSchedulingPriority(LPVOID p0) {
    (void)p0;
    return 0;
}

extern "C" LONG WINAPI D3DKMTSetDisplayMode(LPVOID p0) {
    (void)p0;
    return 0;
}

extern "C" LONG WINAPI D3DKMTSetDisplayPrivateDriverFormat(LPVOID p0) {
    (void)p0;
    return 0;
}

extern "C" LONG WINAPI D3DKMTSetGammaRamp(LPVOID p0) {
    (void)p0;
    return 0;
}

extern "C" LONG WINAPI D3DKMTSetVidPnSourceOwner(LPVOID p0) {
    if (!LoadRealD3D11() && !LoadRealGdi32()) return 0;
    typedef LONG (WINAPI *PFN)(LPVOID);
    PFN fn = (PFN)(GetD3D11OrGdi32Proc("D3DKMTSetVidPnSourceOwner"));
    if (!fn) return 0;
    return fn(p0);
}

extern "C" LONG WINAPI D3DKMTSignalSynchronizationObject(LPVOID p0) {
    (void)p0;
    return 0;
}

extern "C" LONG WINAPI D3DKMTUnlock(LPVOID p0) {
    (void)p0;
    return 0;
}

extern "C" LONG WINAPI D3DKMTWaitForSynchronizationObject(LPVOID p0) {
    (void)p0;
    return 0;
}

extern "C" LONG WINAPI D3DKMTWaitForVerticalBlankEvent(LPVOID p0) {
    (void)p0;
    return 0;
}

extern "C" LONG WINAPI OpenAdapter10(LPVOID p0) {
    (void)p0;
    return 0;
}

extern "C" LONG WINAPI OpenAdapter10_2(LPVOID p0) {
    (void)p0;
    return 0;
}
