/*
 * hid.dll proxy. Generated by scripts/gen_proxy_from_spec.py from Wine hid.spec.
 * Regenerate: python scripts/gen_proxy_from_spec.py hid scripts/specs/hid.spec
 * Hand-corrected for official API: device-handle params use HANDLE (not LONG) for 64-bit ABI;
 * HidP_* return LONG (NTSTATUS). See docs/uptodate/hid_proxy_official_comparison.md.
 */

// Source Code <Display Commander> // follow this order for includes in all files + add this comment at the top
#include "../utils/detour_call_tracker.hpp"
#include "../utils/timing.hpp"

// Libraries <standard C++>
#include <string>

// Libraries <Windows.h> — before other Windows headers
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <Windows.h>

static HMODULE g_hid_module = nullptr;

static bool LoadRealHid() {
    if (g_hid_module != nullptr) return true;
    WCHAR system_path[MAX_PATH];
    if (GetSystemDirectoryW(system_path, MAX_PATH) == 0) return false;
    std::wstring path = std::wstring(system_path) + L"\\hid.dll";
    g_hid_module = LoadLibraryW(path.c_str());
    return g_hid_module != nullptr;
}

extern "C" BOOL WINAPI HidD_FlushQueue(LPVOID p0) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealHid()) return FALSE;
    typedef BOOL (WINAPI *PFN)(LPVOID);
    PFN fn = (PFN)(LoadRealHid() ? GetProcAddress(g_hid_module, "HidD_FlushQueue") : nullptr);
    if (!fn) return FALSE;
    return fn(p0);
}

extern "C" BOOL WINAPI HidD_FreePreparsedData(LPVOID p0) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealHid()) return FALSE;
    typedef BOOL (WINAPI *PFN)(LPVOID);
    PFN fn = (PFN)(LoadRealHid() ? GetProcAddress(g_hid_module, "HidD_FreePreparsedData") : nullptr);
    if (!fn) return FALSE;
    return fn(p0);
}

extern "C" BOOL WINAPI HidD_GetAttributes(HANDLE p0, LPVOID p1) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealHid()) return FALSE;
    typedef BOOL (WINAPI *PFN)(HANDLE, LPVOID);
    PFN fn = (PFN)(LoadRealHid() ? GetProcAddress(g_hid_module, "HidD_GetAttributes") : nullptr);
    if (!fn) return FALSE;
    return fn(p0, p1);
}

extern "C" BOOL WINAPI HidD_GetConfiguration(void) {
    CALL_GUARD(utils::get_now_ns());
    return FALSE;
}

extern "C" BOOL WINAPI HidD_GetFeature(HANDLE p0, LPVOID p1, LONG p2) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealHid()) return FALSE;
    typedef BOOL (WINAPI *PFN)(HANDLE, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealHid() ? GetProcAddress(g_hid_module, "HidD_GetFeature") : nullptr);
    if (!fn) return FALSE;
    return fn(p0, p1, p2);
}

extern "C" void WINAPI HidD_GetHidGuid(LPVOID p0) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealHid()) return;
    typedef void (WINAPI *PFN)(LPVOID);
    PFN fn = (PFN)(LoadRealHid() ? GetProcAddress(g_hid_module, "HidD_GetHidGuid") : nullptr);
    if (!fn) return;
    fn(p0);
}

extern "C" BOOL WINAPI HidD_GetIndexedString(LPVOID p0, LONG p1, LPVOID p2, LONG p3) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealHid()) return FALSE;
    typedef BOOL (WINAPI *PFN)(LPVOID, LONG, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealHid() ? GetProcAddress(g_hid_module, "HidD_GetIndexedString") : nullptr);
    if (!fn) return FALSE;
    return fn(p0, p1, p2, p3);
}

extern "C" BOOL WINAPI HidD_GetInputReport(HANDLE p0, LPVOID p1, LONG p2) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealHid()) return FALSE;
    typedef BOOL (WINAPI *PFN)(HANDLE, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealHid() ? GetProcAddress(g_hid_module, "HidD_GetInputReport") : nullptr);
    if (!fn) return FALSE;
    return fn(p0, p1, p2);
}

extern "C" BOOL WINAPI HidD_GetManufacturerString(HANDLE p0, LPVOID p1, LONG p2) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealHid()) return FALSE;
    typedef BOOL (WINAPI *PFN)(HANDLE, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealHid() ? GetProcAddress(g_hid_module, "HidD_GetManufacturerString") : nullptr);
    if (!fn) return FALSE;
    return fn(p0, p1, p2);
}

extern "C" BOOL WINAPI HidD_GetMsGenreDescriptor(void) {
    CALL_GUARD(utils::get_now_ns());
    return FALSE;
}

extern "C" BOOL WINAPI HidD_GetNumInputBuffers(HANDLE p0, LPVOID p1) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealHid()) return FALSE;
    typedef BOOL (WINAPI *PFN)(HANDLE, LPVOID);
    PFN fn = (PFN)(LoadRealHid() ? GetProcAddress(g_hid_module, "HidD_GetNumInputBuffers") : nullptr);
    if (!fn) return FALSE;
    return fn(p0, p1);
}

extern "C" BOOL WINAPI HidD_GetPhysicalDescriptor(HANDLE p0, LPVOID p1, LONG p2) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealHid()) return FALSE;
    typedef BOOL (WINAPI *PFN)(HANDLE, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealHid() ? GetProcAddress(g_hid_module, "HidD_GetPhysicalDescriptor") : nullptr);
    if (!fn) return FALSE;
    return fn(p0, p1, p2);
}

extern "C" BOOL WINAPI HidD_GetPreparsedData(LPVOID p0, LPVOID p1) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealHid()) return FALSE;
    typedef BOOL (WINAPI *PFN)(LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealHid() ? GetProcAddress(g_hid_module, "HidD_GetPreparsedData") : nullptr);
    if (!fn) return FALSE;
    return fn(p0, p1);
}

extern "C" BOOL WINAPI HidD_GetProductString(HANDLE p0, LPVOID p1, LONG p2) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealHid()) return FALSE;
    typedef BOOL (WINAPI *PFN)(HANDLE, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealHid() ? GetProcAddress(g_hid_module, "HidD_GetProductString") : nullptr);
    if (!fn) return FALSE;
    return fn(p0, p1, p2);
}

extern "C" BOOL WINAPI HidD_GetSerialNumberString(HANDLE p0, LPVOID p1, LONG p2) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealHid()) return FALSE;
    typedef BOOL (WINAPI *PFN)(HANDLE, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealHid() ? GetProcAddress(g_hid_module, "HidD_GetSerialNumberString") : nullptr);
    if (!fn) return FALSE;
    return fn(p0, p1, p2);
}

extern "C" BOOL WINAPI HidD_Hello(void) {
    CALL_GUARD(utils::get_now_ns());
    return FALSE;
}

extern "C" BOOL WINAPI HidD_SetConfiguration(void) {
    CALL_GUARD(utils::get_now_ns());
    return FALSE;
}

extern "C" BOOL WINAPI HidD_SetFeature(HANDLE p0, LPVOID p1, LONG p2) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealHid()) return FALSE;
    typedef BOOL (WINAPI *PFN)(HANDLE, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealHid() ? GetProcAddress(g_hid_module, "HidD_SetFeature") : nullptr);
    if (!fn) return FALSE;
    return fn(p0, p1, p2);
}

extern "C" BOOL WINAPI HidD_SetNumInputBuffers(HANDLE p0, LONG p1) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealHid()) return FALSE;
    typedef BOOL (WINAPI *PFN)(HANDLE, LONG);
    PFN fn = (PFN)(LoadRealHid() ? GetProcAddress(g_hid_module, "HidD_SetNumInputBuffers") : nullptr);
    if (!fn) return FALSE;
    return fn(p0, p1);
}

extern "C" BOOL WINAPI HidD_SetOutputReport(HANDLE p0, LPVOID p1, LONG p2) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealHid()) return FALSE;
    typedef BOOL (WINAPI *PFN)(HANDLE, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealHid() ? GetProcAddress(g_hid_module, "HidD_SetOutputReport") : nullptr);
    if (!fn) return FALSE;
    return fn(p0, p1, p2);
}

extern "C" LONG WINAPI HidP_GetButtonCaps(LONG p0, LPVOID p1, LPVOID p2, LPVOID p3) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealHid()) return 0;
    typedef LONG (WINAPI *PFN)(LONG, LPVOID, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealHid() ? GetProcAddress(g_hid_module, "HidP_GetButtonCaps") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" LONG WINAPI HidP_GetCaps(LPVOID p0, LPVOID p1) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealHid()) return 0;
    typedef LONG (WINAPI *PFN)(LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealHid() ? GetProcAddress(g_hid_module, "HidP_GetCaps") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" LONG WINAPI HidP_GetData(LONG p0, LPVOID p1, LPVOID p2, LPVOID p3, LPVOID p4, LONG p5) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealHid()) return 0;
    typedef LONG (WINAPI *PFN)(LONG, LPVOID, LPVOID, LPVOID, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealHid() ? GetProcAddress(g_hid_module, "HidP_GetData") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5);
}

extern "C" LONG WINAPI HidP_GetExtendedAttributes(void) {
    CALL_GUARD(utils::get_now_ns());
    return 0;
}

extern "C" LONG WINAPI HidP_GetLinkCollectionNodes(LPVOID p0, LPVOID p1, LPVOID p2) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealHid()) return 0;
    typedef LONG (WINAPI *PFN)(LPVOID, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealHid() ? GetProcAddress(g_hid_module, "HidP_GetLinkCollectionNodes") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" LONG WINAPI HidP_GetScaledUsageValue(LONG p0, LONG p1, LONG p2, LONG p3, LPVOID p4, LPVOID p5, LPVOID p6, LONG p7) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealHid()) return 0;
    typedef LONG (WINAPI *PFN)(LONG, LONG, LONG, LONG, LPVOID, LPVOID, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealHid() ? GetProcAddress(g_hid_module, "HidP_GetScaledUsageValue") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5, p6, p7);
}

extern "C" LONG WINAPI HidP_GetSpecificButtonCaps(LONG p0, LONG p1, LONG p2, LONG p3, LPVOID p4, LPVOID p5, LPVOID p6) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealHid()) return 0;
    typedef LONG (WINAPI *PFN)(LONG, LONG, LONG, LONG, LPVOID, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealHid() ? GetProcAddress(g_hid_module, "HidP_GetSpecificButtonCaps") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5, p6);
}

extern "C" LONG WINAPI HidP_GetSpecificValueCaps(LONG p0, LONG p1, LONG p2, LONG p3, LPVOID p4, LPVOID p5, LPVOID p6) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealHid()) return 0;
    typedef LONG (WINAPI *PFN)(LONG, LONG, LONG, LONG, LPVOID, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealHid() ? GetProcAddress(g_hid_module, "HidP_GetSpecificValueCaps") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5, p6);
}

extern "C" LONG WINAPI HidP_GetUsageValue(LONG p0, LONG p1, LONG p2, LONG p3, LPVOID p4, LPVOID p5, LPVOID p6, LONG p7) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealHid()) return 0;
    typedef LONG (WINAPI *PFN)(LONG, LONG, LONG, LONG, LPVOID, LPVOID, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealHid() ? GetProcAddress(g_hid_module, "HidP_GetUsageValue") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5, p6, p7);
}

extern "C" LONG WINAPI HidP_GetUsageValueArray(LONG p0, LONG p1, LONG p2, LONG p3, LPVOID p4, LONG p5, LPVOID p6, LPVOID p7, LONG p8) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealHid()) return 0;
    typedef LONG (WINAPI *PFN)(LONG, LONG, LONG, LONG, LPVOID, LONG, LPVOID, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealHid() ? GetProcAddress(g_hid_module, "HidP_GetUsageValueArray") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5, p6, p7, p8);
}

extern "C" LONG WINAPI HidP_GetUsages(LONG p0, LONG p1, LONG p2, LPVOID p3, LPVOID p4, LPVOID p5, LPVOID p6, LONG p7) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealHid()) return 0;
    typedef LONG (WINAPI *PFN)(LONG, LONG, LONG, LPVOID, LPVOID, LPVOID, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealHid() ? GetProcAddress(g_hid_module, "HidP_GetUsages") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5, p6, p7);
}

extern "C" LONG WINAPI HidP_GetUsagesEx(LONG p0, LONG p1, LPVOID p2, LPVOID p3, LPVOID p4, LPVOID p5, LONG p6) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealHid()) return 0;
    typedef LONG (WINAPI *PFN)(LONG, LONG, LPVOID, LPVOID, LPVOID, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealHid() ? GetProcAddress(g_hid_module, "HidP_GetUsagesEx") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5, p6);
}

extern "C" LONG WINAPI HidP_GetValueCaps(LONG p0, LPVOID p1, LPVOID p2, LPVOID p3) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealHid()) return 0;
    typedef LONG (WINAPI *PFN)(LONG, LPVOID, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealHid() ? GetProcAddress(g_hid_module, "HidP_GetValueCaps") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3);
}

extern "C" LONG WINAPI HidP_InitializeReportForID(LONG p0, LONG p1, LPVOID p2, LPVOID p3, LONG p4) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealHid()) return 0;
    typedef LONG (WINAPI *PFN)(LONG, LONG, LPVOID, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealHid() ? GetProcAddress(g_hid_module, "HidP_InitializeReportForID") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4);
}

extern "C" LONG WINAPI HidP_MaxDataListLength(LONG p0, LPVOID p1) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealHid()) return 0;
    typedef LONG (WINAPI *PFN)(LONG, LPVOID);
    PFN fn = (PFN)(LoadRealHid() ? GetProcAddress(g_hid_module, "HidP_MaxDataListLength") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1);
}

extern "C" LONG WINAPI HidP_MaxUsageListLength(LONG p0, LONG p1, LPVOID p2) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealHid()) return 0;
    typedef LONG (WINAPI *PFN)(LONG, LONG, LPVOID);
    PFN fn = (PFN)(LoadRealHid() ? GetProcAddress(g_hid_module, "HidP_MaxUsageListLength") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2);
}

extern "C" LONG WINAPI HidP_SetData(LONG p0, LPVOID p1, LPVOID p2, LPVOID p3, LPVOID p4, LONG p5) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealHid()) return 0;
    typedef LONG (WINAPI *PFN)(LONG, LPVOID, LPVOID, LPVOID, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealHid() ? GetProcAddress(g_hid_module, "HidP_SetData") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5);
}

extern "C" LONG WINAPI HidP_SetScaledUsageValue(LONG p0, LONG p1, LONG p2, LONG p3, LONG p4, LPVOID p5, LPVOID p6, LONG p7) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealHid()) return 0;
    typedef LONG (WINAPI *PFN)(LONG, LONG, LONG, LONG, LONG, LPVOID, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealHid() ? GetProcAddress(g_hid_module, "HidP_SetScaledUsageValue") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5, p6, p7);
}

extern "C" LONG WINAPI HidP_SetUsageValue(LONG p0, LONG p1, LONG p2, LONG p3, LONG p4, LPVOID p5, LPVOID p6, LONG p7) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealHid()) return 0;
    typedef LONG (WINAPI *PFN)(LONG, LONG, LONG, LONG, LONG, LPVOID, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealHid() ? GetProcAddress(g_hid_module, "HidP_SetUsageValue") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5, p6, p7);
}

extern "C" LONG WINAPI HidP_SetUsageValueArray(LONG p0, LONG p1, LONG p2, LONG p3, LPVOID p4, LONG p5, LPVOID p6, LPVOID p7, LONG p8) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealHid()) return 0;
    typedef LONG (WINAPI *PFN)(LONG, LONG, LONG, LONG, LPVOID, LONG, LPVOID, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealHid() ? GetProcAddress(g_hid_module, "HidP_SetUsageValueArray") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5, p6, p7, p8);
}

extern "C" LONG WINAPI HidP_SetUsages(LONG p0, LONG p1, LONG p2, LPVOID p3, LPVOID p4, LPVOID p5, LPVOID p6, LONG p7) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealHid()) return 0;
    typedef LONG (WINAPI *PFN)(LONG, LONG, LONG, LPVOID, LPVOID, LPVOID, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealHid() ? GetProcAddress(g_hid_module, "HidP_SetUsages") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5, p6, p7);
}

extern "C" LONG WINAPI HidP_TranslateUsagesToI8042ScanCodes(LPVOID p0, LONG p1, LONG p2, LPVOID p3, LPVOID p4, LPVOID p5) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealHid()) return 0;
    typedef LONG (WINAPI *PFN)(LPVOID, LONG, LONG, LPVOID, LPVOID, LPVOID);
    PFN fn = (PFN)(LoadRealHid() ? GetProcAddress(g_hid_module, "HidP_TranslateUsagesToI8042ScanCodes") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5);
}

extern "C" LONG WINAPI HidP_UnsetUsages(LONG p0, LONG p1, LONG p2, LPVOID p3, LPVOID p4, LPVOID p5, LPVOID p6, LONG p7) {
    CALL_GUARD(utils::get_now_ns());
    if (!LoadRealHid()) return 0;
    typedef LONG (WINAPI *PFN)(LONG, LONG, LONG, LPVOID, LPVOID, LPVOID, LPVOID, LONG);
    PFN fn = (PFN)(LoadRealHid() ? GetProcAddress(g_hid_module, "HidP_UnsetUsages") : nullptr);
    if (!fn) return 0;
    return fn(p0, p1, p2, p3, p4, p5, p6, p7);
}

extern "C" LONG WINAPI HidP_UsageListDifference(void) {
    CALL_GUARD(utils::get_now_ns());
    return 0;
}
