// Generated by scripts/gen_vulkan_proxy_abi.py - do not edit.
// Full ABI declarations from Khronos Vulkan headers; include this in the
// vulkan-1 proxy to ensure stub signatures match the official API.
//
#pragma once

#include <vulkan/vulkan_core.h>

#ifdef VK_USE_PLATFORM_WIN32_KHR
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <Windows.h>  // HANDLE, HINSTANCE, HWND for vulkan_win32.h
#include <vulkan/vulkan_win32.h>
#endif

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif
