/*
 * WinMM Proxy Functions
 * Forwards winmm calls to the real system winmm.dll (or winmmHooked.dll in same dir).
 * Generated by scripts/gen_winmm_proxy.py - do not edit by hand.
 */

#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <Windows.h>
#include <string>

#include "winmm_proxy_init.hpp"

#ifndef _MMSYSTEM_TYPEDEFS_
#define _MMSYSTEM_TYPEDEFS_
typedef UINT MMRESULT;
typedef DWORD FOURCC;
typedef UINT MCIDEVICEID;
typedef void* HDRVR;
#endif

static HMODULE g_winmm_module = nullptr;

static bool LoadRealWinMM() {
    if (g_winmm_module != nullptr) return true;
    HMODULE hSelf = GetModuleHandleW(L"winmm.dll");
    if (!hSelf) return false;
    WCHAR self_path[MAX_PATH];
    if (GetModuleFileNameW(hSelf, self_path, MAX_PATH) == 0) return false;
    std::wstring dir(self_path);
    size_t last = dir.find_last_of(L"\\/");
    if (last != std::wstring::npos) dir.resize(last + 1);
    std::wstring hooked = dir + L"winmmHooked.dll";
    if (GetFileAttributesW(hooked.c_str()) != INVALID_FILE_ATTRIBUTES) {
        g_winmm_module = LoadLibraryW(hooked.c_str());
    }
    if (g_winmm_module == nullptr) {
        WCHAR system_path[MAX_PATH];
        if (GetSystemDirectoryW(system_path, MAX_PATH) == 0) return false;
        std::wstring path = std::wstring(system_path) + L"\\winmm.dll";
        g_winmm_module = LoadLibraryW(path.c_str());
    }
    return g_winmm_module != nullptr;
}

void LoadRealWinMMFromDllMain() { (void)LoadRealWinMM(); }

extern "C" LRESULT WINAPI CloseDriver(LPVOID hDriver, LPVOID lParam1, LPVOID lParam2) {
    if (!LoadRealWinMM()) return (LRESULT)0;
    typedef LRESULT (WINAPI *PFN)(LPVOID, LPVOID, LPVOID);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "CloseDriver");
    if (!fn) return (LRESULT)0;
    return fn(hDriver, lParam1, lParam2);
}

extern "C" LRESULT WINAPI DefDriverProc(DWORD_PTR dwDriverIdentifier, HANDLE hdrvr, UINT uMsg, LPARAM lParam1, LPARAM lParam2) {
    if (!LoadRealWinMM()) return (LRESULT)0;
    typedef LRESULT (WINAPI *PFN)(DWORD_PTR, HANDLE, UINT, LPARAM, LPARAM);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "DefDriverProc");
    if (!fn) return (LRESULT)0;
    return fn(dwDriverIdentifier, hdrvr, uMsg, lParam1, lParam2);
}

extern "C" BOOL WINAPI DriverCallback(DWORD_PTR dwCallback, DWORD dwFlags, HANDLE hDevice, DWORD dwMsg, DWORD_PTR dwUser, DWORD_PTR dwParam1, DWORD_PTR dwParam2) {
    if (!LoadRealWinMM()) return (BOOL)0;
    typedef BOOL (WINAPI *PFN)(DWORD_PTR, DWORD, HANDLE, DWORD, DWORD_PTR, DWORD_PTR, DWORD_PTR);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "DriverCallback");
    if (!fn) return (BOOL)0;
    return fn(dwCallback, dwFlags, hDevice, dwMsg, dwUser, dwParam1, dwParam2);
}

extern "C" LRESULT WINAPI DrvClose(LPVOID hDriver, LPVOID lParam1, LPVOID lParam2) {
    if (!LoadRealWinMM()) return (LRESULT)0;
    typedef LRESULT (WINAPI *PFN)(LPVOID, LPVOID, LPVOID);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "DrvClose");
    if (!fn) return (LRESULT)0;
    return fn(hDriver, lParam1, lParam2);
}

extern "C" LRESULT WINAPI DrvDefDriverProc(DWORD_PTR dwDriverIdentifier, HANDLE hdrvr, UINT uMsg, LPARAM lParam1, LPARAM lParam2) {
    if (!LoadRealWinMM()) return (LRESULT)0;
    typedef LRESULT (WINAPI *PFN)(DWORD_PTR, HANDLE, UINT, LPARAM, LPARAM);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "DrvDefDriverProc");
    if (!fn) return (LRESULT)0;
    return fn(dwDriverIdentifier, hdrvr, uMsg, lParam1, lParam2);
}

extern "C" HMODULE WINAPI DrvGetModuleHandle(HANDLE hDrv) {
    if (!LoadRealWinMM()) return (HMODULE)0;
    typedef HMODULE (WINAPI *PFN)(HANDLE);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "DrvGetModuleHandle");
    if (!fn) return (HMODULE)0;
    return fn(hDrv);
}

extern "C" HDRVR WINAPI DrvOpen(LPCWSTR szDriverName, LPCWSTR szSectionName, LPARAM lParam2) {
    if (!LoadRealWinMM()) return (HDRVR)0;
    typedef HDRVR (WINAPI *PFN)(LPCWSTR, LPCWSTR, LPARAM);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "DrvOpen");
    if (!fn) return (HDRVR)0;
    return fn(szDriverName, szSectionName, lParam2);
}

extern "C" HDRVR WINAPI DrvOpenA(LPCSTR szDriverName, LPCSTR szSectionName, LPARAM lParam2) {
    if (!LoadRealWinMM()) return (HDRVR)0;
    typedef HDRVR (WINAPI *PFN)(LPCSTR, LPCSTR, LPARAM);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "DrvOpenA");
    if (!fn) return (HDRVR)0;
    return fn(szDriverName, szSectionName, lParam2);
}

extern "C" LRESULT WINAPI DrvSendMessage(HDRVR hDriver, UINT message, LPARAM lParam1, LPARAM lParam2) {
    if (!LoadRealWinMM()) return (LRESULT)0;
    typedef LRESULT (WINAPI *PFN)(HDRVR, UINT, LPARAM, LPARAM);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "DrvSendMessage");
    if (!fn) return (LRESULT)0;
    return fn(hDriver, message, lParam1, lParam2);
}

extern "C" DWORD WINAPI GetDriverFlags(HDRVR hDriver) {
    if (!LoadRealWinMM()) return (DWORD)0;
    typedef DWORD (WINAPI *PFN)(HDRVR);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "GetDriverFlags");
    if (!fn) return (DWORD)0;
    return fn(hDriver);
}

extern "C" HMODULE WINAPI GetDriverModuleHandle(HANDLE hDrv) {
    if (!LoadRealWinMM()) return (HMODULE)0;
    typedef HMODULE (WINAPI *PFN)(HANDLE);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "GetDriverModuleHandle");
    if (!fn) return (HMODULE)0;
    return fn(hDrv);
}

extern "C" void WINAPI NotifyCallbackData(HANDLE hTask, DWORD_PTR dwCallback, DWORD_PTR dwCallbackData) {
    if (!LoadRealWinMM()) return;
    typedef void (WINAPI *PFN)(HANDLE, DWORD_PTR, DWORD_PTR);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "NotifyCallbackData");
    if (!fn) return;
    if (fn) fn(hTask, dwCallback, dwCallbackData);
}

extern "C" HDRVR WINAPI OpenDriver(LPCWSTR szDriverName, LPCWSTR szSectionName, LPARAM lParam2) {
    if (!LoadRealWinMM()) return (HDRVR)0;
    typedef HDRVR (WINAPI *PFN)(LPCWSTR, LPCWSTR, LPARAM);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "OpenDriver");
    if (!fn) return (HDRVR)0;
    return fn(szDriverName, szSectionName, lParam2);
}

extern "C" HDRVR WINAPI OpenDriverA(LPCSTR szDriverName, LPCSTR szSectionName, LPARAM lParam2) {
    if (!LoadRealWinMM()) return (HDRVR)0;
    typedef HDRVR (WINAPI *PFN)(LPCSTR, LPCSTR, LPARAM);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "OpenDriverA");
    if (!fn) return (HDRVR)0;
    return fn(szDriverName, szSectionName, lParam2);
}

extern "C" BOOL WINAPI PlaySound(LPCSTR pszSound, HMODULE hmod, DWORD fdwSound) {
    if (!LoadRealWinMM()) return (BOOL)0;
    typedef BOOL (WINAPI *PFN)(LPCSTR, HMODULE, DWORD);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "PlaySound");
    if (!fn) return (BOOL)0;
    return fn(pszSound, hmod, fdwSound);
}

extern "C" BOOL WINAPI PlaySoundA(LPCSTR pszSound, HMODULE hmod, DWORD fdwSound) {
    if (!LoadRealWinMM()) return (BOOL)0;
    typedef BOOL (WINAPI *PFN)(LPCSTR, HMODULE, DWORD);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "PlaySoundA");
    if (!fn) return (BOOL)0;
    return fn(pszSound, hmod, fdwSound);
}

extern "C" BOOL WINAPI PlaySoundW(LPCWSTR pszSound, HMODULE hmod, DWORD fdwSound) {
    if (!LoadRealWinMM()) return (BOOL)0;
    typedef BOOL (WINAPI *PFN)(LPCWSTR, HMODULE, DWORD);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "PlaySoundW");
    if (!fn) return (BOOL)0;
    return fn(pszSound, hmod, fdwSound);
}

extern "C" LRESULT WINAPI SendDriverMessage(HDRVR hDriver, UINT message, LPARAM lParam1, LPARAM lParam2) {
    if (!LoadRealWinMM()) return (LRESULT)0;
    typedef LRESULT (WINAPI *PFN)(HDRVR, UINT, LPARAM, LPARAM);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "SendDriverMessage");
    if (!fn) return (LRESULT)0;
    return fn(hDriver, message, lParam1, lParam2);
}

extern "C" DWORD WINAPI WOW32DriverCallback(DWORD_PTR dwCallback, DWORD dwFlags, HANDLE hDevice, DWORD dwMsg, DWORD_PTR dwUser, DWORD_PTR dwParam1, DWORD_PTR dwParam2) {
    if (!LoadRealWinMM()) return (DWORD)0;
    typedef DWORD (WINAPI *PFN)(DWORD_PTR, DWORD, HANDLE, DWORD, DWORD_PTR, DWORD_PTR, DWORD_PTR);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "WOW32DriverCallback");
    if (!fn) return (DWORD)0;
    return fn(dwCallback, dwFlags, hDevice, dwMsg, dwUser, dwParam1, dwParam2);
}

extern "C" BOOL WINAPI WOW32ResolveMultiMediaHandle(HANDLE hDev, HANDLE * phDev, UINT cDevs) {
    if (!LoadRealWinMM()) return (BOOL)0;
    typedef BOOL (WINAPI *PFN)(HANDLE, HANDLE *, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "WOW32ResolveMultiMediaHandle");
    if (!fn) return (BOOL)0;
    return fn(hDev, phDev, cDevs);
}

extern "C" void WINAPI WOWAppExit() {
    if (!LoadRealWinMM()) return;
    typedef void (WINAPI *PFN)(void);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "WOWAppExit");
    if (!fn) return;
    if (fn) fn();
}

extern "C" LRESULT WINAPI aux32Message(UINT uDeviceID, UINT uMsg, DWORD_PTR dwParam1, DWORD_PTR dwParam2) {
    if (!LoadRealWinMM()) return (LRESULT)0;
    typedef LRESULT (WINAPI *PFN)(UINT, UINT, DWORD_PTR, DWORD_PTR);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "aux32Message");
    if (!fn) return (LRESULT)0;
    return fn(uDeviceID, uMsg, dwParam1, dwParam2);
}

extern "C" UINT WINAPI auxGetDevCapsA(UINT_PTR uDeviceID, LPVOID pac, UINT cbac) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(UINT_PTR, LPVOID, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "auxGetDevCapsA");
    if (!fn) return (UINT)0;
    return fn(uDeviceID, pac, cbac);
}

extern "C" UINT WINAPI auxGetDevCapsW(UINT_PTR uDeviceID, LPVOID pac, UINT cbac) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(UINT_PTR, LPVOID, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "auxGetDevCapsW");
    if (!fn) return (UINT)0;
    return fn(uDeviceID, pac, cbac);
}

extern "C" UINT WINAPI auxGetNumDevs() {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(void);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "auxGetNumDevs");
    if (!fn) return (UINT)0;
    return fn();
}

extern "C" UINT WINAPI auxGetVolume(UINT uDeviceID, LPDWORD pdwVolume) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(UINT, LPDWORD);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "auxGetVolume");
    if (!fn) return (UINT)0;
    return fn(uDeviceID, pdwVolume);
}

extern "C" LRESULT WINAPI auxOutMessage(UINT uDeviceID, UINT uMsg, DWORD_PTR dwParam1, DWORD_PTR dwParam2) {
    if (!LoadRealWinMM()) return (LRESULT)0;
    typedef LRESULT (WINAPI *PFN)(UINT, UINT, DWORD_PTR, DWORD_PTR);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "auxOutMessage");
    if (!fn) return (LRESULT)0;
    return fn(uDeviceID, uMsg, dwParam1, dwParam2);
}

extern "C" UINT WINAPI auxSetVolume(UINT uDeviceID, DWORD dwVolume) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(UINT, DWORD);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "auxSetVolume");
    if (!fn) return (UINT)0;
    return fn(uDeviceID, dwVolume);
}

extern "C" LRESULT WINAPI joy32Message(UINT uJoyID, UINT uMsg, DWORD_PTR dwParam1, DWORD_PTR dwParam2) {
    if (!LoadRealWinMM()) return (LRESULT)0;
    typedef LRESULT (WINAPI *PFN)(UINT, UINT, DWORD_PTR, DWORD_PTR);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "joy32Message");
    if (!fn) return (LRESULT)0;
    return fn(uJoyID, uMsg, dwParam1, dwParam2);
}

extern "C" UINT WINAPI joyConfigChanged(DWORD dwFlags) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(DWORD);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "joyConfigChanged");
    if (!fn) return (UINT)0;
    return fn(dwFlags);
}

extern "C" UINT WINAPI joyGetDevCapsA(UINT_PTR uJoyID, LPVOID pjc, UINT cjc) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(UINT_PTR, LPVOID, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "joyGetDevCapsA");
    if (!fn) return (UINT)0;
    return fn(uJoyID, pjc, cjc);
}

extern "C" UINT WINAPI joyGetDevCapsW(UINT_PTR uJoyID, LPVOID pjc, UINT cjc) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(UINT_PTR, LPVOID, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "joyGetDevCapsW");
    if (!fn) return (UINT)0;
    return fn(uJoyID, pjc, cjc);
}

extern "C" UINT WINAPI joyGetNumDevs() {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(void);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "joyGetNumDevs");
    if (!fn) return (UINT)0;
    return fn();
}

extern "C" UINT WINAPI joyGetPos(UINT uJoyID, LPVOID pji) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(UINT, LPVOID);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "joyGetPos");
    if (!fn) return (UINT)0;
    return fn(uJoyID, pji);
}

extern "C" UINT WINAPI joyGetPosEx(UINT uJoyID, LPVOID pji) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(UINT, LPVOID);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "joyGetPosEx");
    if (!fn) return (UINT)0;
    return fn(uJoyID, pji);
}

extern "C" UINT WINAPI joyGetThreshold(UINT uJoyID, LPUINT puThreshold) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(UINT, LPUINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "joyGetThreshold");
    if (!fn) return (UINT)0;
    return fn(uJoyID, puThreshold);
}

extern "C" UINT WINAPI joyReleaseCapture(UINT uJoyID) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "joyReleaseCapture");
    if (!fn) return (UINT)0;
    return fn(uJoyID);
}

extern "C" UINT WINAPI joySetCapture(HWND hwnd, UINT uJoyID, UINT uPeriod, BOOL fChanged) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HWND, UINT, UINT, BOOL);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "joySetCapture");
    if (!fn) return (UINT)0;
    return fn(hwnd, uJoyID, uPeriod, fChanged);
}

extern "C" UINT WINAPI joySetThreshold(UINT uJoyID, UINT uThreshold) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(UINT, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "joySetThreshold");
    if (!fn) return (UINT)0;
    return fn(uJoyID, uThreshold);
}

extern "C" LRESULT WINAPI mci32Message(UINT uDeviceID, UINT uMsg, DWORD_PTR dwParam1, DWORD_PTR dwParam2) {
    if (!LoadRealWinMM()) return (LRESULT)0;
    typedef LRESULT (WINAPI *PFN)(UINT, UINT, DWORD_PTR, DWORD_PTR);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mci32Message");
    if (!fn) return (LRESULT)0;
    return fn(uDeviceID, uMsg, dwParam1, dwParam2);
}

extern "C" BOOL WINAPI mciDriverNotify(HANDLE hCallback, HANDLE hDevice, UINT uStatus) {
    if (!LoadRealWinMM()) return (BOOL)0;
    typedef BOOL (WINAPI *PFN)(HANDLE, HANDLE, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mciDriverNotify");
    if (!fn) return (BOOL)0;
    return fn(hCallback, hDevice, uStatus);
}

extern "C" UINT WINAPI mciDriverYield(HANDLE hDevice) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mciDriverYield");
    if (!fn) return (UINT)0;
    return fn(hDevice);
}

extern "C" BOOL WINAPI mciExecute(LPCSTR pszCommand) {
    if (!LoadRealWinMM()) return (BOOL)0;
    typedef BOOL (WINAPI *PFN)(LPCSTR);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mciExecute");
    if (!fn) return (BOOL)0;
    return fn(pszCommand);
}

extern "C" UINT WINAPI mciFreeCommandResource(HANDLE hResource) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mciFreeCommandResource");
    if (!fn) return (UINT)0;
    return fn(hResource);
}

extern "C" HANDLE WINAPI mciGetCreatorTask(HANDLE hDevice) {
    if (!LoadRealWinMM()) return (HANDLE)0;
    typedef HANDLE (WINAPI *PFN)(HANDLE);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mciGetCreatorTask");
    if (!fn) return (HANDLE)0;
    return fn(hDevice);
}

extern "C" MCIDEVICEID WINAPI mciGetDeviceIDA(LPCSTR pszElement) {
    if (!LoadRealWinMM()) return (MCIDEVICEID)0;
    typedef MCIDEVICEID (WINAPI *PFN)(LPCSTR);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mciGetDeviceIDA");
    if (!fn) return (MCIDEVICEID)0;
    return fn(pszElement);
}

extern "C" MCIDEVICEID WINAPI mciGetDeviceIDFromElementIDA(DWORD dwElementID, LPSTR lpstrTypeName) {
    if (!LoadRealWinMM()) return (MCIDEVICEID)0;
    typedef MCIDEVICEID (WINAPI *PFN)(DWORD, LPSTR);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mciGetDeviceIDFromElementIDA");
    if (!fn) return (MCIDEVICEID)0;
    return fn(dwElementID, lpstrTypeName);
}

extern "C" MCIDEVICEID WINAPI mciGetDeviceIDFromElementIDW(DWORD dwElementID, LPWSTR lpstrTypeName) {
    if (!LoadRealWinMM()) return (MCIDEVICEID)0;
    typedef MCIDEVICEID (WINAPI *PFN)(DWORD, LPWSTR);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mciGetDeviceIDFromElementIDW");
    if (!fn) return (MCIDEVICEID)0;
    return fn(dwElementID, lpstrTypeName);
}

extern "C" MCIDEVICEID WINAPI mciGetDeviceIDW(LPCWSTR pszElement) {
    if (!LoadRealWinMM()) return (MCIDEVICEID)0;
    typedef MCIDEVICEID (WINAPI *PFN)(LPCWSTR);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mciGetDeviceIDW");
    if (!fn) return (MCIDEVICEID)0;
    return fn(pszElement);
}

extern "C" DWORD_PTR WINAPI mciGetDriverData(HANDLE hDevice) {
    if (!LoadRealWinMM()) return (DWORD_PTR)0;
    typedef DWORD_PTR (WINAPI *PFN)(HANDLE);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mciGetDriverData");
    if (!fn) return (DWORD_PTR)0;
    return fn(hDevice);
}

extern "C" BOOL WINAPI mciGetErrorStringA(UINT uError, LPSTR pszText, UINT cchText) {
    if (!LoadRealWinMM()) return (BOOL)0;
    typedef BOOL (WINAPI *PFN)(UINT, LPSTR, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mciGetErrorStringA");
    if (!fn) return (BOOL)0;
    return fn(uError, pszText, cchText);
}

extern "C" BOOL WINAPI mciGetErrorStringW(UINT uError, LPWSTR pszText, UINT cchText) {
    if (!LoadRealWinMM()) return (BOOL)0;
    typedef BOOL (WINAPI *PFN)(UINT, LPWSTR, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mciGetErrorStringW");
    if (!fn) return (BOOL)0;
    return fn(uError, pszText, cchText);
}

extern "C" LPVOID WINAPI mciGetYieldProc(HANDLE hDevice, LPDWORD pdwYieldData) {
    if (!LoadRealWinMM()) return (LPVOID)0;
    typedef LPVOID (WINAPI *PFN)(HANDLE, LPDWORD);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mciGetYieldProc");
    if (!fn) return (LPVOID)0;
    return fn(hDevice, pdwYieldData);
}

extern "C" HANDLE WINAPI mciLoadCommandResource(HINSTANCE hInst, LPCWSTR lpResId, UINT wType) {
    if (!LoadRealWinMM()) return (HANDLE)0;
    typedef HANDLE (WINAPI *PFN)(HINSTANCE, LPCWSTR, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mciLoadCommandResource");
    if (!fn) return (HANDLE)0;
    return fn(hInst, lpResId, wType);
}

extern "C" UINT WINAPI mciSendCommandA(MCIDEVICEID mciId, UINT uMsg, DWORD_PTR dwParam1, DWORD_PTR dwParam2) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(MCIDEVICEID, UINT, DWORD_PTR, DWORD_PTR);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mciSendCommandA");
    if (!fn) return (UINT)0;
    return fn(mciId, uMsg, dwParam1, dwParam2);
}

extern "C" UINT WINAPI mciSendCommandW(MCIDEVICEID mciId, UINT uMsg, DWORD_PTR dwParam1, DWORD_PTR dwParam2) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(MCIDEVICEID, UINT, DWORD_PTR, DWORD_PTR);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mciSendCommandW");
    if (!fn) return (UINT)0;
    return fn(mciId, uMsg, dwParam1, dwParam2);
}

extern "C" UINT WINAPI mciSendStringA(LPCSTR pszCommand, LPSTR pszReturn, UINT cchReturn, HANDLE hwndCallback) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(LPCSTR, LPSTR, UINT, HANDLE);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mciSendStringA");
    if (!fn) return (UINT)0;
    return fn(pszCommand, pszReturn, cchReturn, hwndCallback);
}

extern "C" UINT WINAPI mciSendStringW(LPCWSTR pszCommand, LPWSTR pszReturn, UINT cchReturn, HANDLE hwndCallback) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(LPCWSTR, LPWSTR, UINT, HANDLE);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mciSendStringW");
    if (!fn) return (UINT)0;
    return fn(pszCommand, pszReturn, cchReturn, hwndCallback);
}

extern "C" DWORD_PTR WINAPI mciSetDriverData(HANDLE hDevice, DWORD_PTR dwData) {
    if (!LoadRealWinMM()) return (DWORD_PTR)0;
    typedef DWORD_PTR (WINAPI *PFN)(HANDLE, DWORD_PTR);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mciSetDriverData");
    if (!fn) return (DWORD_PTR)0;
    return fn(hDevice, dwData);
}

extern "C" void WINAPI mciSetYieldProc(HANDLE hDevice, LPVOID fpYieldProc, DWORD dwYieldData) {
    if (!LoadRealWinMM()) return;
    typedef void (WINAPI *PFN)(HANDLE, LPVOID, DWORD);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mciSetYieldProc");
    if (!fn) return;
    if (fn) fn(hDevice, fpYieldProc, dwYieldData);
}

extern "C" LRESULT WINAPI mid32Message(UINT uDeviceID, UINT uMsg, DWORD_PTR dwParam1, DWORD_PTR dwParam2) {
    if (!LoadRealWinMM()) return (LRESULT)0;
    typedef LRESULT (WINAPI *PFN)(UINT, UINT, DWORD_PTR, DWORD_PTR);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mid32Message");
    if (!fn) return (LRESULT)0;
    return fn(uDeviceID, uMsg, dwParam1, dwParam2);
}

extern "C" UINT WINAPI midiConnect(HANDLE hMidi, HANDLE hMidiOut, LPVOID pReserved) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, HANDLE, LPVOID);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "midiConnect");
    if (!fn) return (UINT)0;
    return fn(hMidi, hMidiOut, pReserved);
}

extern "C" UINT WINAPI midiDisconnect(HANDLE hMidi, HANDLE hMidiOut, LPVOID pReserved) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, HANDLE, LPVOID);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "midiDisconnect");
    if (!fn) return (UINT)0;
    return fn(hMidi, hMidiOut, pReserved);
}

extern "C" UINT WINAPI midiInAddBuffer(HANDLE hMidiIn, LPVOID pMidiInHdr, UINT cbMidiInHdr) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, LPVOID, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "midiInAddBuffer");
    if (!fn) return (UINT)0;
    return fn(hMidiIn, pMidiInHdr, cbMidiInHdr);
}

extern "C" UINT WINAPI midiInClose(HANDLE hMidiIn) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "midiInClose");
    if (!fn) return (UINT)0;
    return fn(hMidiIn);
}

extern "C" UINT WINAPI midiInGetDevCapsA(UINT_PTR uDeviceID, LPVOID pmic, UINT cbmic) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(UINT_PTR, LPVOID, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "midiInGetDevCapsA");
    if (!fn) return (UINT)0;
    return fn(uDeviceID, pmic, cbmic);
}

extern "C" UINT WINAPI midiInGetDevCapsW(UINT_PTR uDeviceID, LPVOID pmic, UINT cbmic) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(UINT_PTR, LPVOID, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "midiInGetDevCapsW");
    if (!fn) return (UINT)0;
    return fn(uDeviceID, pmic, cbmic);
}

extern "C" UINT WINAPI midiInGetErrorTextA(UINT uError, LPSTR pszText, UINT cchText) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(UINT, LPSTR, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "midiInGetErrorTextA");
    if (!fn) return (UINT)0;
    return fn(uError, pszText, cchText);
}

extern "C" UINT WINAPI midiInGetErrorTextW(UINT uError, LPWSTR pszText, UINT cchText) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(UINT, LPWSTR, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "midiInGetErrorTextW");
    if (!fn) return (UINT)0;
    return fn(uError, pszText, cchText);
}

extern "C" UINT WINAPI midiInGetID(HANDLE hMidiIn, LPUINT puDeviceID) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, LPUINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "midiInGetID");
    if (!fn) return (UINT)0;
    return fn(hMidiIn, puDeviceID);
}

extern "C" UINT WINAPI midiInGetNumDevs() {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(void);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "midiInGetNumDevs");
    if (!fn) return (UINT)0;
    return fn();
}

extern "C" DWORD WINAPI midiInMessage(HANDLE hMidiIn, UINT uMsg, DWORD_PTR dwParam1, DWORD_PTR dwParam2) {
    if (!LoadRealWinMM()) return (DWORD)0;
    typedef DWORD (WINAPI *PFN)(HANDLE, UINT, DWORD_PTR, DWORD_PTR);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "midiInMessage");
    if (!fn) return (DWORD)0;
    return fn(hMidiIn, uMsg, dwParam1, dwParam2);
}

extern "C" UINT WINAPI midiInOpen(LPHANDLE phMidiIn, UINT uDeviceID, DWORD_PTR dwCallback, DWORD_PTR dwCallbackInstance, DWORD dwFlags) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(LPHANDLE, UINT, DWORD_PTR, DWORD_PTR, DWORD);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "midiInOpen");
    if (!fn) return (UINT)0;
    return fn(phMidiIn, uDeviceID, dwCallback, dwCallbackInstance, dwFlags);
}

extern "C" UINT WINAPI midiInPrepareHeader(HANDLE hMidiIn, LPVOID pMidiInHdr, UINT cbMidiInHdr) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, LPVOID, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "midiInPrepareHeader");
    if (!fn) return (UINT)0;
    return fn(hMidiIn, pMidiInHdr, cbMidiInHdr);
}

extern "C" UINT WINAPI midiInReset(HANDLE hMidiIn) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "midiInReset");
    if (!fn) return (UINT)0;
    return fn(hMidiIn);
}

extern "C" UINT WINAPI midiInStart(HANDLE hMidiIn) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "midiInStart");
    if (!fn) return (UINT)0;
    return fn(hMidiIn);
}

extern "C" UINT WINAPI midiInStop(HANDLE hMidiIn) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "midiInStop");
    if (!fn) return (UINT)0;
    return fn(hMidiIn);
}

extern "C" UINT WINAPI midiInUnprepareHeader(HANDLE hMidiIn, LPVOID pMidiInHdr, UINT cbMidiInHdr) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, LPVOID, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "midiInUnprepareHeader");
    if (!fn) return (UINT)0;
    return fn(hMidiIn, pMidiInHdr, cbMidiInHdr);
}

extern "C" UINT WINAPI midiOutCacheDrumPatches(HANDLE hMidiOut, UINT uPatch, LPVOID pwkya, UINT uFlags) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, UINT, LPVOID, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "midiOutCacheDrumPatches");
    if (!fn) return (UINT)0;
    return fn(hMidiOut, uPatch, pwkya, uFlags);
}

extern "C" UINT WINAPI midiOutCachePatches(HANDLE hMidiOut, UINT uBank, LPVOID pwpa, UINT uFlags) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, UINT, LPVOID, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "midiOutCachePatches");
    if (!fn) return (UINT)0;
    return fn(hMidiOut, uBank, pwpa, uFlags);
}

extern "C" UINT WINAPI midiOutClose(HANDLE hMidiOut) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "midiOutClose");
    if (!fn) return (UINT)0;
    return fn(hMidiOut);
}

extern "C" UINT WINAPI midiOutGetDevCapsA(UINT_PTR uDeviceID, LPVOID pmoc, UINT cbmoc) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(UINT_PTR, LPVOID, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "midiOutGetDevCapsA");
    if (!fn) return (UINT)0;
    return fn(uDeviceID, pmoc, cbmoc);
}

extern "C" UINT WINAPI midiOutGetDevCapsW(UINT_PTR uDeviceID, LPVOID pmoc, UINT cbmoc) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(UINT_PTR, LPVOID, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "midiOutGetDevCapsW");
    if (!fn) return (UINT)0;
    return fn(uDeviceID, pmoc, cbmoc);
}

extern "C" UINT WINAPI midiOutGetErrorTextA(UINT uError, LPSTR pszText, UINT cchText) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(UINT, LPSTR, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "midiOutGetErrorTextA");
    if (!fn) return (UINT)0;
    return fn(uError, pszText, cchText);
}

extern "C" UINT WINAPI midiOutGetErrorTextW(UINT uError, LPWSTR pszText, UINT cchText) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(UINT, LPWSTR, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "midiOutGetErrorTextW");
    if (!fn) return (UINT)0;
    return fn(uError, pszText, cchText);
}

extern "C" UINT WINAPI midiOutGetID(HANDLE hMidiOut, LPUINT puDeviceID) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, LPUINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "midiOutGetID");
    if (!fn) return (UINT)0;
    return fn(hMidiOut, puDeviceID);
}

extern "C" UINT WINAPI midiOutGetNumDevs() {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(void);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "midiOutGetNumDevs");
    if (!fn) return (UINT)0;
    return fn();
}

extern "C" UINT WINAPI midiOutGetVolume(HANDLE hMidiOut, LPDWORD pdwVolume) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, LPDWORD);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "midiOutGetVolume");
    if (!fn) return (UINT)0;
    return fn(hMidiOut, pdwVolume);
}

extern "C" UINT WINAPI midiOutLongMsg(HANDLE hMidiOut, LPVOID pMidiOutHdr, UINT cbMidiOutHdr) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, LPVOID, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "midiOutLongMsg");
    if (!fn) return (UINT)0;
    return fn(hMidiOut, pMidiOutHdr, cbMidiOutHdr);
}

extern "C" DWORD WINAPI midiOutMessage(HANDLE hMidiOut, UINT uMsg, DWORD_PTR dwParam1, DWORD_PTR dwParam2) {
    if (!LoadRealWinMM()) return (DWORD)0;
    typedef DWORD (WINAPI *PFN)(HANDLE, UINT, DWORD_PTR, DWORD_PTR);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "midiOutMessage");
    if (!fn) return (DWORD)0;
    return fn(hMidiOut, uMsg, dwParam1, dwParam2);
}

extern "C" UINT WINAPI midiOutOpen(LPHANDLE phMidiOut, UINT uDeviceID, DWORD_PTR dwCallback, DWORD_PTR dwCallbackInstance, DWORD dwFlags) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(LPHANDLE, UINT, DWORD_PTR, DWORD_PTR, DWORD);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "midiOutOpen");
    if (!fn) return (UINT)0;
    return fn(phMidiOut, uDeviceID, dwCallback, dwCallbackInstance, dwFlags);
}

extern "C" UINT WINAPI midiOutPrepareHeader(HANDLE hMidiOut, LPVOID pMidiOutHdr, UINT cbMidiOutHdr) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, LPVOID, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "midiOutPrepareHeader");
    if (!fn) return (UINT)0;
    return fn(hMidiOut, pMidiOutHdr, cbMidiOutHdr);
}

extern "C" UINT WINAPI midiOutReset(HANDLE hMidiOut) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "midiOutReset");
    if (!fn) return (UINT)0;
    return fn(hMidiOut);
}

extern "C" UINT WINAPI midiOutSetVolume(HANDLE hMidiOut, DWORD dwVolume) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, DWORD);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "midiOutSetVolume");
    if (!fn) return (UINT)0;
    return fn(hMidiOut, dwVolume);
}

extern "C" UINT WINAPI midiOutShortMsg(HANDLE hMidiOut, DWORD dwMsg) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, DWORD);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "midiOutShortMsg");
    if (!fn) return (UINT)0;
    return fn(hMidiOut, dwMsg);
}

extern "C" UINT WINAPI midiOutUnprepareHeader(HANDLE hMidiOut, LPVOID pMidiOutHdr, UINT cbMidiOutHdr) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, LPVOID, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "midiOutUnprepareHeader");
    if (!fn) return (UINT)0;
    return fn(hMidiOut, pMidiOutHdr, cbMidiOutHdr);
}

extern "C" UINT WINAPI midiStreamClose(HANDLE hStream) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "midiStreamClose");
    if (!fn) return (UINT)0;
    return fn(hStream);
}

extern "C" UINT WINAPI midiStreamOpen(LPHANDLE phStream, LPUINT puDeviceID, UINT cMidi, DWORD_PTR dwCallback, DWORD_PTR dwInstance, DWORD fdwOpen) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(LPHANDLE, LPUINT, UINT, DWORD_PTR, DWORD_PTR, DWORD);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "midiStreamOpen");
    if (!fn) return (UINT)0;
    return fn(phStream, puDeviceID, cMidi, dwCallback, dwInstance, fdwOpen);
}

extern "C" UINT WINAPI midiStreamOut(HANDLE hMidiStream, LPVOID pMidiHdr, UINT cbMidiHdr) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, LPVOID, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "midiStreamOut");
    if (!fn) return (UINT)0;
    return fn(hMidiStream, pMidiHdr, cbMidiHdr);
}

extern "C" UINT WINAPI midiStreamPause(HANDLE hStream) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "midiStreamPause");
    if (!fn) return (UINT)0;
    return fn(hStream);
}

extern "C" UINT WINAPI midiStreamPosition(HANDLE hStream, LPVOID pmmt, UINT cbmmt) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, LPVOID, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "midiStreamPosition");
    if (!fn) return (UINT)0;
    return fn(hStream, pmmt, cbmmt);
}

extern "C" UINT WINAPI midiStreamProperty(HANDLE hStream, LPBYTE lpPropertyData, DWORD dwProperty) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, LPBYTE, DWORD);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "midiStreamProperty");
    if (!fn) return (UINT)0;
    return fn(hStream, lpPropertyData, dwProperty);
}

extern "C" UINT WINAPI midiStreamRestart(HANDLE hStream) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "midiStreamRestart");
    if (!fn) return (UINT)0;
    return fn(hStream);
}

extern "C" UINT WINAPI midiStreamStop(HANDLE hStream) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "midiStreamStop");
    if (!fn) return (UINT)0;
    return fn(hStream);
}

extern "C" UINT WINAPI mixerClose(HANDLE hmx) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mixerClose");
    if (!fn) return (UINT)0;
    return fn(hmx);
}

extern "C" UINT WINAPI mixerGetControlDetailsA(HANDLE hmxobj, LPVOID pmxcd, DWORD fdwDetails) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, LPVOID, DWORD);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mixerGetControlDetailsA");
    if (!fn) return (UINT)0;
    return fn(hmxobj, pmxcd, fdwDetails);
}

extern "C" UINT WINAPI mixerGetControlDetailsW(HANDLE hmxobj, LPVOID pmxcd, DWORD fdwDetails) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, LPVOID, DWORD);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mixerGetControlDetailsW");
    if (!fn) return (UINT)0;
    return fn(hmxobj, pmxcd, fdwDetails);
}

extern "C" UINT WINAPI mixerGetDevCapsA(UINT_PTR uMxId, LPVOID pmxcaps, UINT cbmxcaps) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(UINT_PTR, LPVOID, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mixerGetDevCapsA");
    if (!fn) return (UINT)0;
    return fn(uMxId, pmxcaps, cbmxcaps);
}

extern "C" UINT WINAPI mixerGetDevCapsW(UINT_PTR uMxId, LPVOID pmxcaps, UINT cbmxcaps) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(UINT_PTR, LPVOID, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mixerGetDevCapsW");
    if (!fn) return (UINT)0;
    return fn(uMxId, pmxcaps, cbmxcaps);
}

extern "C" UINT WINAPI mixerGetID(HANDLE hmxobj, LPUINT puMxId, DWORD fdwId) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, LPUINT, DWORD);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mixerGetID");
    if (!fn) return (UINT)0;
    return fn(hmxobj, puMxId, fdwId);
}

extern "C" UINT WINAPI mixerGetLineControlsA(HANDLE hmxobj, LPVOID pmxlc, DWORD fdwControls) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, LPVOID, DWORD);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mixerGetLineControlsA");
    if (!fn) return (UINT)0;
    return fn(hmxobj, pmxlc, fdwControls);
}

extern "C" UINT WINAPI mixerGetLineControlsW(HANDLE hmxobj, LPVOID pmxlc, DWORD fdwControls) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, LPVOID, DWORD);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mixerGetLineControlsW");
    if (!fn) return (UINT)0;
    return fn(hmxobj, pmxlc, fdwControls);
}

extern "C" UINT WINAPI mixerGetLineInfoA(HANDLE hmxobj, LPVOID pmxl, DWORD fdwInfo) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, LPVOID, DWORD);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mixerGetLineInfoA");
    if (!fn) return (UINT)0;
    return fn(hmxobj, pmxl, fdwInfo);
}

extern "C" UINT WINAPI mixerGetLineInfoW(HANDLE hmxobj, LPVOID pmxl, DWORD fdwInfo) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, LPVOID, DWORD);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mixerGetLineInfoW");
    if (!fn) return (UINT)0;
    return fn(hmxobj, pmxl, fdwInfo);
}

extern "C" UINT WINAPI mixerGetNumDevs() {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(void);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mixerGetNumDevs");
    if (!fn) return (UINT)0;
    return fn();
}

extern "C" DWORD WINAPI mixerMessage(HANDLE hmx, UINT uMsg, DWORD_PTR dwParam1, DWORD_PTR dwParam2) {
    if (!LoadRealWinMM()) return (DWORD)0;
    typedef DWORD (WINAPI *PFN)(HANDLE, UINT, DWORD_PTR, DWORD_PTR);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mixerMessage");
    if (!fn) return (DWORD)0;
    return fn(hmx, uMsg, dwParam1, dwParam2);
}

extern "C" UINT WINAPI mixerOpen(LPHANDLE phmx, UINT uMxId, DWORD_PTR dwCallback, DWORD_PTR dwInstance, DWORD fdwOpen) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(LPHANDLE, UINT, DWORD_PTR, DWORD_PTR, DWORD);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mixerOpen");
    if (!fn) return (UINT)0;
    return fn(phmx, uMxId, dwCallback, dwInstance, fdwOpen);
}

extern "C" UINT WINAPI mixerSetControlDetails(HANDLE hmxobj, LPVOID pmxcd, DWORD fdwDetails) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, LPVOID, DWORD);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mixerSetControlDetails");
    if (!fn) return (UINT)0;
    return fn(hmxobj, pmxcd, fdwDetails);
}

extern "C" UINT WINAPI mmDrvInstall(LPVOID pDriverInfo, UINT uDriverID, UINT uMsg) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(LPVOID, UINT, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mmDrvInstall");
    if (!fn) return (UINT)0;
    return fn(pDriverInfo, uDriverID, uMsg);
}

extern "C" HANDLE WINAPI mmGetCurrentTask() {
    if (!LoadRealWinMM()) return (HANDLE)0;
    typedef HANDLE (WINAPI *PFN)(void);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mmGetCurrentTask");
    if (!fn) return (HANDLE)0;
    return fn();
}

extern "C" void WINAPI mmTaskBlock(HANDLE hTask) {
    if (!LoadRealWinMM()) return;
    typedef void (WINAPI *PFN)(HANDLE);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mmTaskBlock");
    if (!fn) return;
    if (fn) fn(hTask);
}

extern "C" HANDLE WINAPI mmTaskCreate(LPVOID lpfn, LPVOID lpParam, UINT uPriority) {
    if (!LoadRealWinMM()) return (HANDLE)0;
    typedef HANDLE (WINAPI *PFN)(LPVOID, LPVOID, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mmTaskCreate");
    if (!fn) return (HANDLE)0;
    return fn(lpfn, lpParam, uPriority);
}

extern "C" DWORD WINAPI mmTaskSignal(HANDLE hTask) {
    if (!LoadRealWinMM()) return (DWORD)0;
    typedef DWORD (WINAPI *PFN)(HANDLE);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mmTaskSignal");
    if (!fn) return (DWORD)0;
    return fn(hTask);
}

extern "C" void WINAPI mmTaskYield() {
    if (!LoadRealWinMM()) return;
    typedef void (WINAPI *PFN)(void);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mmTaskYield");
    if (!fn) return;
    if (fn) fn();
}

extern "C" LRESULT WINAPI mmioAdvance(HANDLE hmmio, LPVOID pmmioinfo, UINT fuAdvance) {
    if (!LoadRealWinMM()) return (LRESULT)0;
    typedef LRESULT (WINAPI *PFN)(HANDLE, LPVOID, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mmioAdvance");
    if (!fn) return (LRESULT)0;
    return fn(hmmio, pmmioinfo, fuAdvance);
}

extern "C" UINT WINAPI mmioAscend(HANDLE hmmio, LPVOID pmmcki, UINT fuAscend) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, LPVOID, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mmioAscend");
    if (!fn) return (UINT)0;
    return fn(hmmio, pmmcki, fuAscend);
}

extern "C" UINT WINAPI mmioClose(HANDLE hmmio, UINT fuClose) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mmioClose");
    if (!fn) return (UINT)0;
    return fn(hmmio, fuClose);
}

extern "C" UINT WINAPI mmioCreateChunk(HANDLE hmmio, LPVOID pmmcki, UINT fuCreate) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, LPVOID, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mmioCreateChunk");
    if (!fn) return (UINT)0;
    return fn(hmmio, pmmcki, fuCreate);
}

extern "C" UINT WINAPI mmioDescend(HANDLE hmmio, LPVOID pmmcki, LPVOID pmmckiParent, UINT fuDescend) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, LPVOID, LPVOID, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mmioDescend");
    if (!fn) return (UINT)0;
    return fn(hmmio, pmmcki, pmmckiParent, fuDescend);
}

extern "C" UINT WINAPI mmioFlush(HANDLE hmmio, UINT fuFlush) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mmioFlush");
    if (!fn) return (UINT)0;
    return fn(hmmio, fuFlush);
}

extern "C" UINT WINAPI mmioGetInfo(HANDLE hmmio, LPVOID pmmioinfo, UINT fuInfo) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, LPVOID, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mmioGetInfo");
    if (!fn) return (UINT)0;
    return fn(hmmio, pmmioinfo, fuInfo);
}

extern "C" LPVOID WINAPI mmioInstallIOProc16(FOURCC fccIOProc, LPVOID pIOProc, DWORD dwFlags) {
    if (!LoadRealWinMM()) return (LPVOID)0;
    typedef LPVOID (WINAPI *PFN)(FOURCC, LPVOID, DWORD);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mmioInstallIOProc16");
    if (!fn) return (LPVOID)0;
    return fn(fccIOProc, pIOProc, dwFlags);
}

extern "C" LPVOID WINAPI mmioInstallIOProcA(FOURCC fccIOProc, LPVOID pIOProc, DWORD dwFlags) {
    if (!LoadRealWinMM()) return (LPVOID)0;
    typedef LPVOID (WINAPI *PFN)(FOURCC, LPVOID, DWORD);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mmioInstallIOProcA");
    if (!fn) return (LPVOID)0;
    return fn(fccIOProc, pIOProc, dwFlags);
}

extern "C" LPVOID WINAPI mmioInstallIOProcW(FOURCC fccIOProc, LPVOID pIOProc, DWORD dwFlags) {
    if (!LoadRealWinMM()) return (LPVOID)0;
    typedef LPVOID (WINAPI *PFN)(FOURCC, LPVOID, DWORD);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mmioInstallIOProcW");
    if (!fn) return (LPVOID)0;
    return fn(fccIOProc, pIOProc, dwFlags);
}

extern "C" HANDLE WINAPI mmioOpenA(LPSTR szFilename, LPVOID pmmioinfo, DWORD dwOpenFlags) {
    if (!LoadRealWinMM()) return (HANDLE)0;
    typedef HANDLE (WINAPI *PFN)(LPSTR, LPVOID, DWORD);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mmioOpenA");
    if (!fn) return (HANDLE)0;
    return fn(szFilename, pmmioinfo, dwOpenFlags);
}

extern "C" HANDLE WINAPI mmioOpenW(LPWSTR szFilename, LPVOID pmmioinfo, DWORD dwOpenFlags) {
    if (!LoadRealWinMM()) return (HANDLE)0;
    typedef HANDLE (WINAPI *PFN)(LPWSTR, LPVOID, DWORD);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mmioOpenW");
    if (!fn) return (HANDLE)0;
    return fn(szFilename, pmmioinfo, dwOpenFlags);
}

extern "C" LRESULT WINAPI mmioRead(HANDLE hmmio, LPSTR pch, LONG cch) {
    if (!LoadRealWinMM()) return (LRESULT)0;
    typedef LRESULT (WINAPI *PFN)(HANDLE, LPSTR, LONG);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mmioRead");
    if (!fn) return (LRESULT)0;
    return fn(hmmio, pch, cch);
}

extern "C" UINT WINAPI mmioRenameA(LPCSTR szFilename, LPCSTR szNewFilename, LPVOID pmmioinfo, DWORD dwRenameFlags) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(LPCSTR, LPCSTR, LPVOID, DWORD);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mmioRenameA");
    if (!fn) return (UINT)0;
    return fn(szFilename, szNewFilename, pmmioinfo, dwRenameFlags);
}

extern "C" UINT WINAPI mmioRenameW(LPCWSTR szFilename, LPCWSTR szNewFilename, LPVOID pmmioinfo, DWORD dwRenameFlags) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(LPCWSTR, LPCWSTR, LPVOID, DWORD);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mmioRenameW");
    if (!fn) return (UINT)0;
    return fn(szFilename, szNewFilename, pmmioinfo, dwRenameFlags);
}

extern "C" LONG WINAPI mmioSeek(HANDLE hmmio, LONG lOffset, int iOrigin) {
    if (!LoadRealWinMM()) return (LONG)0;
    typedef LONG (WINAPI *PFN)(HANDLE, LONG, int);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mmioSeek");
    if (!fn) return (LONG)0;
    return fn(hmmio, lOffset, iOrigin);
}

extern "C" LRESULT WINAPI mmioSendMessage(HANDLE hmmio, UINT uMsg, LPARAM lParam1, LPARAM lParam2) {
    if (!LoadRealWinMM()) return (LRESULT)0;
    typedef LRESULT (WINAPI *PFN)(HANDLE, UINT, LPARAM, LPARAM);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mmioSendMessage");
    if (!fn) return (LRESULT)0;
    return fn(hmmio, uMsg, lParam1, lParam2);
}

extern "C" UINT WINAPI mmioSetBuffer(HANDLE hmmio, LPSTR pchBuffer, LONG cchBuffer, UINT fuBuffer) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, LPSTR, LONG, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mmioSetBuffer");
    if (!fn) return (UINT)0;
    return fn(hmmio, pchBuffer, cchBuffer, fuBuffer);
}

extern "C" UINT WINAPI mmioSetInfo(HANDLE hmmio, LPVOID pmmioinfo, UINT fuInfo) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, LPVOID, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mmioSetInfo");
    if (!fn) return (UINT)0;
    return fn(hmmio, pmmioinfo, fuInfo);
}

extern "C" FOURCC WINAPI mmioStringToFOURCCA(LPSTR sz, UINT cch) {
    if (!LoadRealWinMM()) return (FOURCC)0;
    typedef FOURCC (WINAPI *PFN)(LPSTR, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mmioStringToFOURCCA");
    if (!fn) return (FOURCC)0;
    return fn(sz, cch);
}

extern "C" FOURCC WINAPI mmioStringToFOURCCW(LPWSTR sz, UINT cch) {
    if (!LoadRealWinMM()) return (FOURCC)0;
    typedef FOURCC (WINAPI *PFN)(LPWSTR, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mmioStringToFOURCCW");
    if (!fn) return (FOURCC)0;
    return fn(sz, cch);
}

extern "C" LRESULT WINAPI mmioWrite(HANDLE hmmio, LPCSTR pch, LONG cch) {
    if (!LoadRealWinMM()) return (LRESULT)0;
    typedef LRESULT (WINAPI *PFN)(HANDLE, LPCSTR, LONG);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mmioWrite");
    if (!fn) return (LRESULT)0;
    return fn(hmmio, pch, cch);
}

extern "C" UINT WINAPI mmsystemGetVersion() {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(void);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mmsystemGetVersion");
    if (!fn) return (UINT)0;
    return fn();
}

extern "C" LRESULT WINAPI mod32Message(UINT uDeviceID, UINT uMsg, DWORD_PTR dwParam1, DWORD_PTR dwParam2) {
    if (!LoadRealWinMM()) return (LRESULT)0;
    typedef LRESULT (WINAPI *PFN)(UINT, UINT, DWORD_PTR, DWORD_PTR);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mod32Message");
    if (!fn) return (LRESULT)0;
    return fn(uDeviceID, uMsg, dwParam1, dwParam2);
}

extern "C" LRESULT WINAPI mxd32Message(UINT uDeviceID, UINT uMsg, DWORD_PTR dwParam1, DWORD_PTR dwParam2) {
    if (!LoadRealWinMM()) return (LRESULT)0;
    typedef LRESULT (WINAPI *PFN)(UINT, UINT, DWORD_PTR, DWORD_PTR);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "mxd32Message");
    if (!fn) return (LRESULT)0;
    return fn(uDeviceID, uMsg, dwParam1, dwParam2);
}

extern "C" BOOL WINAPI sndPlaySoundA(LPCSTR pszSound, UINT fuSound) {
    if (!LoadRealWinMM()) return (BOOL)0;
    typedef BOOL (WINAPI *PFN)(LPCSTR, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "sndPlaySoundA");
    if (!fn) return (BOOL)0;
    return fn(pszSound, fuSound);
}

extern "C" BOOL WINAPI sndPlaySoundW(LPCWSTR pszSound, UINT fuSound) {
    if (!LoadRealWinMM()) return (BOOL)0;
    typedef BOOL (WINAPI *PFN)(LPCWSTR, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "sndPlaySoundW");
    if (!fn) return (BOOL)0;
    return fn(pszSound, fuSound);
}

extern "C" LRESULT WINAPI tid32Message(UINT uDeviceID, UINT uMsg, DWORD_PTR dwParam1, DWORD_PTR dwParam2) {
    if (!LoadRealWinMM()) return (LRESULT)0;
    typedef LRESULT (WINAPI *PFN)(UINT, UINT, DWORD_PTR, DWORD_PTR);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "tid32Message");
    if (!fn) return (LRESULT)0;
    return fn(uDeviceID, uMsg, dwParam1, dwParam2);
}

extern "C" UINT WINAPI timeBeginPeriod(UINT uPeriod) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "timeBeginPeriod");
    if (!fn) return (UINT)0;
    return fn(uPeriod);
}

extern "C" UINT WINAPI timeEndPeriod(UINT uPeriod) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "timeEndPeriod");
    if (!fn) return (UINT)0;
    return fn(uPeriod);
}

extern "C" UINT WINAPI timeGetDevCaps(LPVOID ptc, UINT cbtc) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(LPVOID, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "timeGetDevCaps");
    if (!fn) return (UINT)0;
    return fn(ptc, cbtc);
}

extern "C" UINT WINAPI timeGetSystemTime(LPVOID pmmt, UINT cbmmt) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(LPVOID, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "timeGetSystemTime");
    if (!fn) return (UINT)0;
    return fn(pmmt, cbmmt);
}

extern "C" DWORD WINAPI timeGetTime() {
    if (!LoadRealWinMM()) return (DWORD)0;
    typedef DWORD (WINAPI *PFN)(void);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "timeGetTime");
    if (!fn) return (DWORD)0;
    return fn();
}

extern "C" UINT WINAPI timeKillEvent(UINT uTimerID) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "timeKillEvent");
    if (!fn) return (UINT)0;
    return fn(uTimerID);
}

extern "C" UINT WINAPI timeSetEvent(UINT uDelay, UINT uResolution, LPVOID lpTimeProc, DWORD_PTR dwUser, UINT fuEvent) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(UINT, UINT, LPVOID, DWORD_PTR, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "timeSetEvent");
    if (!fn) return (UINT)0;
    return fn(uDelay, uResolution, lpTimeProc, dwUser, fuEvent);
}

extern "C" UINT WINAPI waveInAddBuffer(HANDLE hWaveIn, LPVOID pWaveInHdr, UINT cbWaveInHdr) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, LPVOID, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "waveInAddBuffer");
    if (!fn) return (UINT)0;
    return fn(hWaveIn, pWaveInHdr, cbWaveInHdr);
}

extern "C" UINT WINAPI waveInClose(HANDLE hWaveIn) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "waveInClose");
    if (!fn) return (UINT)0;
    return fn(hWaveIn);
}

extern "C" UINT WINAPI waveInGetDevCapsA(UINT_PTR uDeviceID, LPVOID pwic, UINT cbwic) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(UINT_PTR, LPVOID, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "waveInGetDevCapsA");
    if (!fn) return (UINT)0;
    return fn(uDeviceID, pwic, cbwic);
}

extern "C" UINT WINAPI waveInGetDevCapsW(UINT_PTR uDeviceID, LPVOID pwic, UINT cbwic) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(UINT_PTR, LPVOID, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "waveInGetDevCapsW");
    if (!fn) return (UINT)0;
    return fn(uDeviceID, pwic, cbwic);
}

extern "C" UINT WINAPI waveInGetErrorTextA(UINT uError, LPSTR pszText, UINT cchText) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(UINT, LPSTR, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "waveInGetErrorTextA");
    if (!fn) return (UINT)0;
    return fn(uError, pszText, cchText);
}

extern "C" UINT WINAPI waveInGetErrorTextW(UINT uError, LPWSTR pszText, UINT cchText) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(UINT, LPWSTR, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "waveInGetErrorTextW");
    if (!fn) return (UINT)0;
    return fn(uError, pszText, cchText);
}

extern "C" UINT WINAPI waveInGetID(HANDLE hWaveIn, LPUINT puDeviceID) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, LPUINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "waveInGetID");
    if (!fn) return (UINT)0;
    return fn(hWaveIn, puDeviceID);
}

extern "C" UINT WINAPI waveInGetNumDevs() {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(void);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "waveInGetNumDevs");
    if (!fn) return (UINT)0;
    return fn();
}

extern "C" UINT WINAPI waveInGetPosition(HANDLE hWaveIn, LPVOID pmmt, UINT cbmmt) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, LPVOID, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "waveInGetPosition");
    if (!fn) return (UINT)0;
    return fn(hWaveIn, pmmt, cbmmt);
}

extern "C" DWORD WINAPI waveInMessage(HANDLE hWaveIn, UINT uMsg, DWORD_PTR dwParam1, DWORD_PTR dwParam2) {
    if (!LoadRealWinMM()) return (DWORD)0;
    typedef DWORD (WINAPI *PFN)(HANDLE, UINT, DWORD_PTR, DWORD_PTR);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "waveInMessage");
    if (!fn) return (DWORD)0;
    return fn(hWaveIn, uMsg, dwParam1, dwParam2);
}

extern "C" UINT WINAPI waveInOpen(LPHANDLE phWaveIn, UINT uDeviceID, LPVOID pwfx, DWORD_PTR dwCallback, DWORD_PTR dwCallbackInstance, DWORD fdwOpen) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(LPHANDLE, UINT, LPVOID, DWORD_PTR, DWORD_PTR, DWORD);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "waveInOpen");
    if (!fn) return (UINT)0;
    return fn(phWaveIn, uDeviceID, pwfx, dwCallback, dwCallbackInstance, fdwOpen);
}

extern "C" UINT WINAPI waveInPrepareHeader(HANDLE hWaveIn, LPVOID pWaveInHdr, UINT cbWaveInHdr) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, LPVOID, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "waveInPrepareHeader");
    if (!fn) return (UINT)0;
    return fn(hWaveIn, pWaveInHdr, cbWaveInHdr);
}

extern "C" UINT WINAPI waveInReset(HANDLE hWaveIn) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "waveInReset");
    if (!fn) return (UINT)0;
    return fn(hWaveIn);
}

extern "C" UINT WINAPI waveInStart(HANDLE hWaveIn) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "waveInStart");
    if (!fn) return (UINT)0;
    return fn(hWaveIn);
}

extern "C" UINT WINAPI waveInStop(HANDLE hWaveIn) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "waveInStop");
    if (!fn) return (UINT)0;
    return fn(hWaveIn);
}

extern "C" UINT WINAPI waveInUnprepareHeader(HANDLE hWaveIn, LPVOID pWaveInHdr, UINT cbWaveInHdr) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, LPVOID, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "waveInUnprepareHeader");
    if (!fn) return (UINT)0;
    return fn(hWaveIn, pWaveInHdr, cbWaveInHdr);
}

extern "C" UINT WINAPI waveOutBreakLoop(HANDLE hWaveOut) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "waveOutBreakLoop");
    if (!fn) return (UINT)0;
    return fn(hWaveOut);
}

extern "C" UINT WINAPI waveOutClose(HANDLE hWaveOut) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "waveOutClose");
    if (!fn) return (UINT)0;
    return fn(hWaveOut);
}

extern "C" UINT WINAPI waveOutGetDevCapsA(UINT_PTR uDeviceID, LPVOID pwoc, UINT cbwoc) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(UINT_PTR, LPVOID, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "waveOutGetDevCapsA");
    if (!fn) return (UINT)0;
    return fn(uDeviceID, pwoc, cbwoc);
}

extern "C" UINT WINAPI waveOutGetDevCapsW(UINT_PTR uDeviceID, LPVOID pwoc, UINT cbwoc) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(UINT_PTR, LPVOID, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "waveOutGetDevCapsW");
    if (!fn) return (UINT)0;
    return fn(uDeviceID, pwoc, cbwoc);
}

extern "C" UINT WINAPI waveOutGetErrorTextA(UINT uError, LPSTR pszText, UINT cchText) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(UINT, LPSTR, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "waveOutGetErrorTextA");
    if (!fn) return (UINT)0;
    return fn(uError, pszText, cchText);
}

extern "C" UINT WINAPI waveOutGetErrorTextW(UINT uError, LPWSTR pszText, UINT cchText) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(UINT, LPWSTR, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "waveOutGetErrorTextW");
    if (!fn) return (UINT)0;
    return fn(uError, pszText, cchText);
}

extern "C" UINT WINAPI waveOutGetID(HANDLE hWaveOut, LPUINT puDeviceID) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, LPUINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "waveOutGetID");
    if (!fn) return (UINT)0;
    return fn(hWaveOut, puDeviceID);
}

extern "C" UINT WINAPI waveOutGetNumDevs() {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(void);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "waveOutGetNumDevs");
    if (!fn) return (UINT)0;
    return fn();
}

extern "C" UINT WINAPI waveOutGetPitch(HANDLE hWaveOut, LPDWORD pdwPitch) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, LPDWORD);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "waveOutGetPitch");
    if (!fn) return (UINT)0;
    return fn(hWaveOut, pdwPitch);
}

extern "C" UINT WINAPI waveOutGetPlaybackRate(HANDLE hWaveOut, LPDWORD pdwRate) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, LPDWORD);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "waveOutGetPlaybackRate");
    if (!fn) return (UINT)0;
    return fn(hWaveOut, pdwRate);
}

extern "C" UINT WINAPI waveOutGetPosition(HANDLE hWaveOut, LPVOID pmmt, UINT cbmmt) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, LPVOID, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "waveOutGetPosition");
    if (!fn) return (UINT)0;
    return fn(hWaveOut, pmmt, cbmmt);
}

extern "C" UINT WINAPI waveOutGetVolume(HANDLE hWaveOut, LPDWORD pdwVolume) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, LPDWORD);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "waveOutGetVolume");
    if (!fn) return (UINT)0;
    return fn(hWaveOut, pdwVolume);
}

extern "C" DWORD WINAPI waveOutMessage(HANDLE hWaveOut, UINT uMsg, DWORD_PTR dwParam1, DWORD_PTR dwParam2) {
    if (!LoadRealWinMM()) return (DWORD)0;
    typedef DWORD (WINAPI *PFN)(HANDLE, UINT, DWORD_PTR, DWORD_PTR);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "waveOutMessage");
    if (!fn) return (DWORD)0;
    return fn(hWaveOut, uMsg, dwParam1, dwParam2);
}

extern "C" UINT WINAPI waveOutOpen(LPHANDLE phWaveOut, UINT uDeviceID, LPVOID pwfx, DWORD_PTR dwCallback, DWORD_PTR dwCallbackInstance, DWORD fdwOpen) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(LPHANDLE, UINT, LPVOID, DWORD_PTR, DWORD_PTR, DWORD);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "waveOutOpen");
    if (!fn) return (UINT)0;
    return fn(phWaveOut, uDeviceID, pwfx, dwCallback, dwCallbackInstance, fdwOpen);
}

extern "C" UINT WINAPI waveOutPause(HANDLE hWaveOut) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "waveOutPause");
    if (!fn) return (UINT)0;
    return fn(hWaveOut);
}

extern "C" UINT WINAPI waveOutPrepareHeader(HANDLE hWaveOut, LPVOID pWaveOutHdr, UINT cbWaveOutHdr) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, LPVOID, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "waveOutPrepareHeader");
    if (!fn) return (UINT)0;
    return fn(hWaveOut, pWaveOutHdr, cbWaveOutHdr);
}

extern "C" UINT WINAPI waveOutReset(HANDLE hWaveOut) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "waveOutReset");
    if (!fn) return (UINT)0;
    return fn(hWaveOut);
}

extern "C" UINT WINAPI waveOutRestart(HANDLE hWaveOut) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "waveOutRestart");
    if (!fn) return (UINT)0;
    return fn(hWaveOut);
}

extern "C" UINT WINAPI waveOutSetPitch(HANDLE hWaveOut, DWORD dwPitch) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, DWORD);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "waveOutSetPitch");
    if (!fn) return (UINT)0;
    return fn(hWaveOut, dwPitch);
}

extern "C" UINT WINAPI waveOutSetPlaybackRate(HANDLE hWaveOut, DWORD dwRate) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, DWORD);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "waveOutSetPlaybackRate");
    if (!fn) return (UINT)0;
    return fn(hWaveOut, dwRate);
}

extern "C" UINT WINAPI waveOutSetVolume(HANDLE hWaveOut, DWORD dwVolume) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, DWORD);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "waveOutSetVolume");
    if (!fn) return (UINT)0;
    return fn(hWaveOut, dwVolume);
}

extern "C" UINT WINAPI waveOutUnprepareHeader(HANDLE hWaveOut, LPVOID pWaveOutHdr, UINT cbWaveOutHdr) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, LPVOID, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "waveOutUnprepareHeader");
    if (!fn) return (UINT)0;
    return fn(hWaveOut, pWaveOutHdr, cbWaveOutHdr);
}

extern "C" UINT WINAPI waveOutWrite(HANDLE hWaveOut, LPVOID pWaveOutHdr, UINT cbWaveOutHdr) {
    if (!LoadRealWinMM()) return (UINT)0;
    typedef UINT (WINAPI *PFN)(HANDLE, LPVOID, UINT);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "waveOutWrite");
    if (!fn) return (UINT)0;
    return fn(hWaveOut, pWaveOutHdr, cbWaveOutHdr);
}

extern "C" LRESULT WINAPI wid32Message(UINT uDeviceID, UINT uMsg, DWORD_PTR dwParam1, DWORD_PTR dwParam2) {
    if (!LoadRealWinMM()) return (LRESULT)0;
    typedef LRESULT (WINAPI *PFN)(UINT, UINT, DWORD_PTR, DWORD_PTR);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "wid32Message");
    if (!fn) return (LRESULT)0;
    return fn(uDeviceID, uMsg, dwParam1, dwParam2);
}

extern "C" LRESULT WINAPI wod32Message(UINT uDeviceID, UINT uMsg, DWORD_PTR dwParam1, DWORD_PTR dwParam2) {
    if (!LoadRealWinMM()) return (LRESULT)0;
    typedef LRESULT (WINAPI *PFN)(UINT, UINT, DWORD_PTR, DWORD_PTR);
    PFN fn = (PFN)GetProcAddress(g_winmm_module, "wod32Message");
    if (!fn) return (LRESULT)0;
    return fn(uDeviceID, uMsg, dwParam1, dwParam2);
}
